### ISSUE TITLE
Logs: selector of reporting level, asynchronous logging functionality

### ISSUE THREAD

**Issue by Stizerg** [spacemeshos/smapp#1013]
### Environment

* Smapp version: All
* OS: All

### Describe the bug

Currently Smapp is writing to the log file everything that happening with the app. It writes so much, that on an old computer it using 100% of the hard drive writing only logs to the level when db update is in a queue and the chain advances faster, this generates more log messages and as result the node is far behind.
It doesn't effect computers with SSDs much.

Another issue with logs I noticed: if the node is unable to write into log file (for example 'read only' set) the node simply stops. That means that logging is synchronized with what the node is doing, and if writing into log file is slow, the node is slow to sync. It is tested on 2 different weak computers, one with SSD and another with slow HDD.

### Steps to reproduce

Get a really old computer ...

### How to fix 

1. The logging have to be asynchronous and shouldn't effect other functionality of the node.
2. In the settings we need a selector, where we can select how detailed logs we need.
For example:
- Info, Warnings, Errors
- Warnings, Errors
- Errors
- Turn off all logging

This way the user will be able to select the level of reporting according to available resources of computer or required level for troubleshooting.

Thank you!

**Comment by maparr** [comment]
Thank you @Stizerg , I will check this behavior and we will update u about the result.

**Comment by brusherru** [comment]
1. Regarding huge amounts of logs — we had some issues in go-spacemesh, but it is fixed for now.
2. We reduced the size of the logs to 100MB, besides this, it will store 5 archives (about 30MB more) of previous logs. So Smapp won't eat out all your storage.
3. Also, in #1071 was added additional popup that will notify you if you don't have some required permissions, including permissions on writing logs, node config, and node data.

So, I'm closing the issue.
If you think it is still actual, please reopen it and provide fresh details.
Thanks!
