### ISSUE TITLE
Match transaction response from RPC to transaction view on transaction list page 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1018]
Currently response from RPC was changed , transaction template not match transactions list view 
Need to investigate and fix this behaviour.

also analytics block have to be fixed. Now not calculating Send/Received transactions only Rewards ( screenshot 2 )

Steps to reproduce
1. sync node, get rewards 
2. got to wallet page and send / receive / spawn transactions 
3. check transactions list

Current state: 
<img width="698" alt="Screenshot 2022-11-23 at 12 33 27" src="https://user-images.githubusercontent.com/54288612/203551502-1b988ece-62f0-4919-b521-715e316326c7.png">
<img width="1173" alt="Screenshot 2022-11-23 at 12 52 27" src="https://user-images.githubusercontent.com/54288612/203551581-e6eaa80a-f20f-4045-ac7a-cbc3557ac2c3.png">

**Comment by brusherru** [comment]
The rest of the issue was closed within commit https://github.com/spacemeshos/smapp/pull/1033/commits/8b9f28ad514b6d5336262bfa835983585ea4a81e
