### ISSUE TITLE
Allow customisation of node config

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#1019]
### Rationale
At the moment Smapp downloads the default config every time the User connects to the selected network, and copies the` smeshing` field from the previous config file (if exists). This way it does not allows the User to tweak a config file. Let's say he wants to add some boot nodes or poet servers.

### User story
- [ ] Run Smapp
- [ ] Unlock/create the wallet (aka connect to some network)
- [ ] Edit `%APP_DATA%/Spacemesh/node-config.json`, keeping the JSON validity:
        add a boot node, poet server, or just prettify JSON.
- [ ] Restart Smapp, unlock the wallet

Expected: I connect to the network using the node config with my changes.
Actual: My changes are overwritten by default config.

### Solution
We need to store default node-configs with different names (e.g. `config-301.json`).
If this file already exists on the file system — do not overwrite it and just use it.
~~If the file does not exist — then download the default one, and copy the `smeshing` options from the previous config file.
Since we need to know which config was the previous one, we need also to store the path to the config file in the persistent store (use `StoreService`).~~ — we don't need it because reusing smeshing opts is useless on the different networks, so we don't need to copy smeshing opts

Such a solution makes it possible to make edits in the file, meanwhile, it keeps the simplicity of switching to another network.

### Acceptance criteria
- [ ] Smapp downloads the default config for the network if it does not exist
- [ ] User can make changes in the config file and they won't be overwritten by Smapp

**Comment by pigmej** [comment]
@brusherru isn't that done to some extend in one of previous PRs?
