### ISSUE TITLE
Error: Send SMH No handler registered for W_M_SEND_TX

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1026]
### Describe the bug
per title

### Environment

* Smapp version: latest
* Node version: latest
* OS: Windows > 10 | macOS High Sierra > (10.13) | Ubuntu > 20.04

### Steps to reproduce

1. u have some SMH on your wallet
2. create a transaction 
3. click SEND on preview screen
4. see error 

### Example

<img width="959" alt="Screenshot 2022-11-24 at 12 44 06" src="https://user-images.githubusercontent.com/54288612/203787553-6264eca4-8fd4-4722-b0f4-c515c338a540.png">

**Comment by monikasmolarek** [comment]
I reproduced this error. 

Environment: 
Smapp version: v0.2.10-pr.1040
Node version: v0.2.19-beta.0
OS: Windows 10 Home

Steps to reproduce the same:

1. u have some SMH on your wallet
2. Account already spawned
3. create a transaction (the very first SEND transaction from this account)
4. click SEND on preview screen
5. see error

Tried all the possible combinations of the transaction criteria. 
The receiver was loosing the connection to the node every now and then, syncing while trying to execute the transaction. 
Same error after the receiver was all synced.

Same error while trying to send SMH to myself. 
Didn't find anything in logs.

After restart of the application the transaction was successful at the firt attempt, but it was doubled (!)
There are two identical records in the transaction log, the wallet was charged twice and the receiver got 2 identical transactions with doubled amount of SMHs. 

![2022-12-09_00h32_48](https://user-images.githubusercontent.com/89876259/206596793-e30bee12-2b26-467b-b16f-cd4a518eb616.png)

![2022-12-09_01h23_31](https://user-images.githubusercontent.com/89876259/206596821-35016fd0-58f7-42c9-b5e3-d74d088e45c4.png)

![2022-12-09_01h24_28](https://user-images.githubusercontent.com/89876259/206596838-1b841ba3-8490-4ca2-9cc7-f3688c35e375.png)

![2022-12-09_01h28_20](https://user-images.githubusercontent.com/89876259/206596848-b14a6ff5-ca6b-4b0e-8338-20c7afe0511e.png)

**Comment by monikasmolarek** [comment]
Tried to reproduce on: 

Environment:
Smapp version: v0.2.10-pr.1040
Node version: v0.2.19-beta.0
OS: macOS Ventura Version 13.0.1 (22A400)

The transaction successfully sent at the first attempt , no issues whatsoever. No error messages, no problems with the amouts etc. 

<img width="1392" alt="Screenshot 2022-12-09 at 01 52 44" src="https://user-images.githubusercontent.com/89876259/206598495-8757e059-3a63-48cd-965e-129e4e108193.png">

**Comment by monikasmolarek** [comment]
The second SEND transaction from Windows was correct. Nothing got doubled, it was executed at the first attemt, nice and smooth. 
![2022-12-09_02h20_17](https://user-images.githubusercontent.com/89876259/206601887-30b39407-9160-4fbf-b4e6-7856ea823f28.png)
![2022-12-09_02h23_39](https://user-images.githubusercontent.com/89876259/206601932-456574f6-1b69-464c-b8ba-63496b813fbc.png)

**Comment by brusherru** [comment]
@monikasmolarek pls, if you won't be able to reproduce this bug on the new Smapp version — close the issue until we'll catch it again

**Comment by monikasmolarek** [comment]
Closing as recommended. The error did not show up in the latest release; I also checked Sentry and Discord, no reports for this specific issue.

**Comment by maparr** [comment]
@monikasmolarek , @brusherru , last one 53 min ago https://sentry.io/organizations/spacemesh/issues/3255922679/?project=6324919&query=is%3Aunresolved&referrer=issue-stream

I will create and issue on this because all our not registered handlers are based on 1 problem with not updated the Smeshing / Node screen and registered handlers for our Electron app, which should be in the preload file for the Electron. I did research on it and will create 2 issues for our handlers and issues with them.
