### ISSUE TITLE
Mining doesn't proceed.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1034]
### Environment

* Smapp version: 0.2.9 | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 22.04 <= ALL OS have same issues,

### Describe the bug

Problem 1
I deleted all configs and generated a new key, but I still get this error and the status is STOPPED.
I have never seen such an error in 0.2.8.
Windows10, Ubuntu22

Problem 2
After specifying the PoS directory, there was a screen to select CPU and GPU, but Nvidia GPU is no longer displayed there. Of course the recommended drivers are installed; this did not happen with 0.2.8.
Ubuntu22

### Steps to reproduce

1. Wait for sync complete.
2. Check SMESHING
3. There is attached screen shot error and mining stopped.

### Expected behavior

Woring fine.

### Actual behavior

I do 14 PCs. Only 1 PC is working fine. Others are getting same error.

![スクリーンショット 2022-12-05 11 27 50](https://user-images.githubusercontent.com/2483747/205536613-9a19477f-9df5-4bbb-858f-8f175c0bd5d1.png)

### Logs

[spacemesh-log-1e0acdbd58480f738940959cb6c5554e728a739d.txt.zip](https://github.com/spacemeshos/smapp/files/10150220/spacemesh-log-1e0acdbd58480f738940959cb6c5554e728a739d.txt.zip)

### How to fix 

No idea, sorry. This must be necessary to update.

**Comment by maparr** [comment]
Hi @hryksbt , thank u for the report. Our team working right now on this problem with Smeshing screen. We will notify you and the community when it will be done.
