### ISSUE TITLE
I can not select CPU internal GPU and Nvidia's GPU with Ubuntu.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1035]
### Environment

* Smapp version: 0.2.9 | develop
* Node version: v0.x.xx 
* OS: Ubuntu 22

### Describe the bug

GPU is not appeared.
Intel's internal GPU and Nvidia GPU both.

### Steps to reproduce

1.  Create PoS data.
2.  Select size.
3.  Select POS PROCESSOR.

### Expected behavior

Showing up all processor including CPU internal GPU and Nvidia GPU.

### Actual behavior

CPU internal GPU and Nvidia GPU were displayed until 0.2.8.
But after I start to use 0.2.9, they are not showing up.
I installed latest GPU driver.
This is not occurred with Windows 10 and Mac OS. This is occurred only with Ubuntu.

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

![スクリーンショット 2022-12-05 11 36 23](https://user-images.githubusercontent.com/2483747/205537769-92ab5e23-4915-496e-9b83-71d4f7ddc3b6.png)

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

I have no idea.

**Comment by maparr** [comment]
Hi @hryksbt , Thank you for the issue report. I will provide more information on this week about Ubuntu plugins that will help to smesh with GPU.

**Comment by pigmej** [comment]
Hello @hryksbt 

Could you please check the following:

1. https://github.com/spacemeshos/gpu-post/releases/tag/v0.1.27 please download linux build from here, unpack and open terminal in unpacked dir
2. `chmod a+x gpu-setup-test`
3. `export LD_LIBRARY_PATH=.`
4. `gpu-setup-test --list`


And please paste back what the last command outputs. Just please remember about crucial step 3.

**Comment by hryksbt** [comment]
Hello @pigmej 

```
#./gpu-setup-test --list
Available POST compute providers:
  1: [CPU] CPU
```
There are no CPU included GPU and Nvidia's GPU.

**Comment by brusherru** [comment]
Hello @hryksbt,
Thanks for the report!
Can you provide your hardware details? Aka your processor and graphic card models?
It may help us to debug and fix the issue.

**Comment by hryksbt** [comment]
@brusherru Hello,
I have some environment.

Case 1:
Intel Core i5-12600K
This must show up CPU and GPU this is included in CPU.
MSI mother board. Z690 chipset. DDR4.
 
Case 2:
Intel Core i3-12100
This must show up CPU and GPU this is included in CPU.
MSI mother board. Z690 chipset. DDR4.

Case3: 
Intel Core i7-11800M
Nvidia GeForce RTX3080 Laptop
This must show up CPU, GPU this is included in CPU and Nvidia's GPU.
This laptop is made by MSI. DDR4.

**Comment by pigmej** [comment]
@hryksbt if possible, could you please run the command from the above with `export VK_LOADER_DEBUG=all` and paste the output? 

I'm curious about the exact error on your system.

Additionally, if you could install vulkantools (if ubuntu based system, then `sudo apt install vulkan-tools`) and then  paste the output of `vulkan-info` 

Thanks.

**Comment by pigmej** [comment]
@hryksbt anyway if you could double check with most recent gpu-post release?: https://github.com/spacemeshos/gpu-post/releases/tag/v0.1.28

**Comment by hryksbt** [comment]
I downloaded 0.1.28 then executed `gpu-setup-test --list`, that returned same.
I set `export VK_LOADER_DEBUG=all` too.

Result:
```
Available POST compute providers:
  1: [CPU] CPU
```
Then I installed Valkan-Tool, But I got same result.

**Comment by pigmej** [comment]
@hryksbt did you remember to `export LD_LIBRARY_PATH=.` ?

**Comment by hryksbt** [comment]
@pigmej Of course. If I don't use `export LD_LIBRARY_PATH=.` , this command cannot run as you know.
I think this feature must refactor such as mining stop issue.

**Comment by pigmej** [comment]
You should be stil able to use cuda. (apt install cuda).

But yes we're checking why Vulkan based provider is no longer working on Ubuntu.

**Comment by hryksbt** [comment]
@pigmej I didn't need cuda until 0.2.8 version. You should check what affect to hide Vulkan and Nvidia.
All my environments occurred same issue. They are using different CPU and GPU.
I think every people who are using Ubuntu getting same issue.
If you want, I can give you Teamviewer ID/Password. You can debug on my PC.
Please give me DM if you want. I am "Be" in discord.
Thanks.

**Comment by pigmej** [comment]
Ok. 

The issue was nvidia drivers, for hybrid cards 525+ driver is needed. We will update the readme.

Checked with 0.1.28 and now all is good.

**Comment by hryksbt** [comment]
@pigmej Thank you for your kindly support.
I could understand this must match with cuda version.
Have a nice day!
