### ISSUE TITLE
Sentry: add path and tag integration

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1063]
### Rationale

Currently, we are using Sentry and we want to extend to send details about the page and buttons which our community interacts with.

### Prerequisites

The actual version of Sentry already contains the actual version to use 
- [context](https://docs.sentry.io/platforms/javascript/enriching-events/context/) 
- [breadcrumbs](https://docs.sentry.io/platforms/javascript/enriching-events/breadcrumbs/)

### User story

For example what needs to cover with Smeshing screen

- [ ] open the Smehsing screen
- [ ] click Setup proof of space ( this even has to be covered by Sentry)
- [ ] pass the init step and write all details about the buttons and paths that the client pass-through
- [ ] If an error was triggered by Sentry, all details about  the path and last client interaction should be shown in Sentry

**Comment by maparr** [comment]
waiting #1101

**Comment by monikasmolarek** [comment]
As discussed with K, Sentry is not a priority.
