### ISSUE TITLE
Add info about POS data being assigned to the first Account

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1067]
### Rationale

Currently, there is only one coinbase, and Smesher cannot change it easily from the application level. It is possible to reset it/manipulate it by accessing App files that are, by default, hidden. 
It might be confusing for the Smesher that - once he/she creates another account or Wallet, the POS data and Rewards Address always stay the same (the first Account).

In the future, the best case scenario would be for the Smesher to be able to choose all the POS/Smeshing details - including Rewards Address. As for now, it seems very User oriented to add information about the Rewards Address being the first Account, no matter how many Wallets/Accounts there will be. It is crucial, especially for those who would potentially want to delete their first Wallet.

A tooltip on the Smeshing screen (next to the Rewards Address) and information during POS data configuration would be enough for now. 

### Prerequisites

https://github.com/spacemeshos/smapp/issues/1027

### User story

- [ ] I open the Smeshing Screen (running a local node)
- [ ] I create POS data by following all the necessary steps
- [ ] On the confirmation screen, I can see a note that the POS data that was set up will not change no matter how many Wallets or Accounts will be created in the future 
- [ ] I can read similar information on the Smeshing screen anytime I have some doubts about the Rewards Address 

### Acceptance criteria

- [ ] The basic scenario works as described
- [ ] There are no or very few questions/reports from the Community about POS data not being changed after changing Wallets/Accounts

### Out of scope

TBU

### How to implement

A tooltip on the Smeshing screen (next to the Rewards Address) and information during POS data configuration would be enough for now. 

### How to test

Go through the case scenario and check whether the information is displayed correctly and formulated clearly. 
Check whether the Application works as expected - the POS data stays the same after switching Wallets and Accounts.

**Comment by maparr** [comment]
Hi @monikasmolarek , this issue should be resolved in 0.2.10
The Smeshing screen is updating accordingly to what we have from go-spacemesh node. One moment on multi-account, when we have 2 node wallets, information will be taken from the first one because we are able to run only 1 node.
#1073 
I can add additionally the message information like, the node was started from which account or so.

**Comment by monikasmolarek** [comment]
Getting back to this - I created this feature request after our call, during which we discussed this question. Adding a simple phrase on the confirmations screen or in the tooltip on the Smeshing screen would be enough. 
Additionally, I'm also thinking about improving the confirmation/fireworks screen we get after setting up POS directory - there's an information about a desktop notification when the set up is ready - I've never seen any trace of this notif...

**Comment by maparr** [comment]
Hi @monikasmolarek , we can do the notifications as part of #1068 , to make it clear for the end user about the statuses
cc: @brusherru , @pigmej

**Comment by brusherru** [comment]
Or we may add the "specify coinbase for rewards" step in the PoS setup.
There should be input with suggestions and the default coinbase should be pre-selected.

**Comment by monikasmolarek** [comment]
This additional step would be perfect!

**Comment by pigmej** [comment]
Isn't it what is currently in smapp in the most recent release in the step called Spacemesh arguments?

Cc @brusherru

**Comment by monikasmolarek** [comment]
Yeah, no longer valid point. This feature request was created in response to repeating questions from the community, but it's addressed, we can close it now.
