### ISSUE TITLE
Add Smeshing screen set up, during sign up flow. 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1078]
### Rationale

Right now, the user has to wait, till the node will be synced and after synced state, the user has to set up the proof of space folder on the Smeshing screen. I propose to add this folder set up during the wallet creation process. Till the node won't be synced do not attach this folder to the smeshing process, and when node has synced state, re-run the node and to do the smeshing. 
 
 The main point is to keep the client settings separate from the node state, the user can manage his folder and PoS data. But only when the node will be ready to do the smeshing, attach the client attached the folder.
 
 Keep the smeshing PoS selection in some config file or cache.
 
### User story &  Acceptance criteria

Describe the most straightforward usage scenario

- [ ] Open smapp, click create a wallet + node
- [ ] On the last screen of the process ask user to select folder ( same settings / screen as for Smeshing select the proof of space folder )
- [ ] After the process show Node screen, and smeshing screen already with the selected  folder ( from the configuration )
- [ ] Wait when the node will be synced
- [ ] Check if config for smeshing option is ready
- [ ] Run node with the smeshing option

### Additionally 

When syncing is going, still allow to manage the Smeshing folder on the Smeshing screen, but keep the settings in some file or cache. Only when the app ready to do the smeshing , try to start it based on what we have , config or nothing, if nothing to not start the smeshing.

**Comment by maparr** [comment]
Hi @brusherru , what do u think? For clients, the setup process will be faster. For us, we don't need to keep track of the details during the syncing process. And only we have an error from node, show it.

**Comment by brusherru** [comment]
I think we should not do that.
Previously we don't have this limitation of setting up the smeshing and PoS directory without having synced Node.
In PR #1076, I've returned it back and it should work fine.

Moreover, it will introduce more code to maintain, more coupling of concepts (we discussed not so much time ago that it'd be better to distinct Node operations from Wallets, but this idea is controversial), and more edge cases. Aka we'd need to handle cases like what if I'm creating a new wallet, but already set up smeshing on the previous one, add this behavior to restore wallet, and so on.

If no objections — please, close the issue :)
