### ISSUE TITLE
Smapp has earned 0 SMH but has been fully synced since genesis was ready to join

### ISSUE THREAD

**Issue by Proskhmer08** [spacemeshos/smapp#1084]
### Environment

* Smapp version: 0.2.10 | develop
* Node version: v0.2.20-beta.0
* OS: Ubuntu 22.04 LTS

### Describe the bug

Smapp on this mini pc has earned SMH in previous devnets. But in current devnet 312, it has earned zero SMH. In the smapp network tab, there's a green light with status as Synced. Even after a brief logging out and logging back in, the status shortly goes back to synced and at the time of this writing, current layer is 4,300and verified layer is 4299. I can also confirm the layer from another smapp on a Windows. In the Network tab, connected peers show 10.

In the Smeshing tab, PoS has been set up with Smesher ID, Status, Current Epoch, Data Directory, Rewards Address etc. But rewards show zero SMH and wallet balance show 0 SMH. Reward Address in the Smeshing tab matches with the wallet address. 
Nethogs show the the smapp has been receiving data and appears to be normal rate. It looks like over the course of 9-10hours, there's around 1,100MB of received data show via Nethogs

### Steps to reproduce

To reproduce this, I've uninstalled and reinstalled the smapp and created new wallet still ended up with same result which is zero SMH for PoS. I've also tried using the "wipe out" option in the smapp setting to uninstall and reinstall the smapp. I've tried logging out and logging back in. I've also checked the log file and it only has one wallet, node-data only shows one folder with accounts show one file in it as well. 

1.  Close the smapp
2.  Confirm quitting the smapp
3.  Wait 10 seconds
4. Click on smapp icon to open smapp
5. Enter password to log into smapp
6. Wait for smapp to sync again and wait for next epoch for rewards

### Expected behavior

Smapp should shortly go back to fully synced and once the next epoch starts, rewards should be coming in as displayed in the Smeshing tab and wallet tab. 

### Actual behavior

Smapp is fully synced. But 0 SMH has shown up in the Smeshing tab or Wallet tab. 

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

"d898e00cca6e1549a760df69947bc63c544313f30f8800e1ed0f48e5f9c7d160", "module": "nipostBuilder", "errmsg": "poet service is unstable: failed to submit challenge to poet service (response status code: 400, body: {\"code\":3, \"message\":\"challenge is invalid\", \"details\":[]})", "name": "nipostBuilder"}

ERROR	d898e.atxBuilder   	error attempting to publish atx	{"node_id": "d898e00cca6e1549a760df69947bc63c544313f30f8800e1ed0f48e5f9c7d160", "module": "atxBuilder", "sessionId": "4537ffdf-582c-4d63-8ef4-3c674f7bfbb0", "layer_id": 3574, "epoch_id": 59, "errmsg": "create ATX: failed to build NIPost: poet service is unstable: failed to submit challenge to any PoET (<nil>)", "name": "atxBuilder"}

2023-01-16T08:47:08.835-0800	INFO	d898e.sync         	starting sync run #101	{"node_id": "d898e00cca6e1549a760df69947bc63c544313f30f8800e1ed0f48e5f9c7d160", "module": "sync", "sessionId": "32db9437-c399-4bf9-8981-d17806b02728", "sync_state": "synced", "last_synced": "4312", "current": "4313", "latest": "4313", "in_state": "4313", "processed": "4313", "name": "sync"}

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

Awaiting response from the team.

![Screenshot from 2023-01-16 08-34-39](https://user-images.githubusercontent.com/35155781/212727222-49ba5d45-0944-48aa-af57-e4181bcc0835.png)
![Screenshot from 2023-01-16 08-34-48](https://user-images.githubusercontent.com/35155781/212727684-02e69742-750a-4d57-8b47-c179a0194025.png)
![Screenshot from 2023-01-16 08-35-11](https://user-images.githubusercontent.com/35155781/212727886-a4d99c7c-66c2-490a-9c01-63fc6d2597ea.png)

**Comment by brusherru** [comment]
Outdated and most likely not actual :)
