### ISSUE TITLE
Spawning transaction gets stuck and is never effective

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1096]
### Environment

* Smapp version: 0.2.10 PR #1090, #1095  and #1094 
* Node version: 7841cc4
* OS: Windows 10 | macOS Ventura (13.1)

### Describe the bug

I cannot self-spawn my wallet; after some time of the transaction being frozen/pending, the Spawn button gets reactivated, and I can try again and again...with no effect

### Steps to reproduce

1.  Have some SMH and not yet spawned account
2.  Press Spawn, continue with the next steps of this transaction and wait
3.  Check if the transaction was successful 

### Expected behavior

After clicking on Spawn, the transaction should 'unlock" the possibility of sending the transaction to other wallets.

### Actual behavior

After executing the spawn transaction, it gets stuck for a while, other transactions are not possible, the Spawn button gets active again. 

<img width="1680" alt="Screenshot 2023-01-25 at 00 21 50" src="https://user-images.githubusercontent.com/89876259/214443670-9251ac94-e877-4576-b25d-3176a760b7fc.png">

<img width="1680" alt="Screenshot 2023-01-25 at 00 28 25" src="https://user-images.githubusercontent.com/89876259/214444030-dade4275-2c26-45cd-8593-8c99a1975053.png">

### Logs

[app-log.0.2.10.txt](https://github.com/spacemeshos/smapp/files/10494774/app-log.0.2.10.txt)
[spacemesh-log-59e0c8b9.txt](https://github.com/spacemeshos/smapp/files/10494777/spacemesh-log-59e0c8b9.txt)

**Comment by brusherru** [comment]
I bet it is not actual anymore.
If I missed something and it is still actual — feel free to reopen it and provide some fresh details ;)
