### ISSUE TITLE
Smeshing screen got reset by itself to the initial "Set up POS" state after 

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1107]
### Environment

* Smapp version: 0.2.10 | PR #1099 
* Node version: v0.2.21-beta.0
* OS: macOS Ventura 13.1
* Network: 320-short

### Describe the bug

Setup up smeshing after genesis, everything was fine but then after the POS was generated and just “Smeshing” the CPU at 377%. Logs not flooded. But after some ~2-3 hours of smeshing POS screen got kicked out, back to the screen with the setup button.  In logs, lots of beacon not available. 
Timestamp for the logs check - around 2023-01-27T21:10:00. (+8minutes)

### Steps to reproduce

1.  Sync the network fully
2.  Set up POS
3.  Wait for the smeshing process to begin
4. observe the smeshing creen

### Expected behavior

No interruptions, after some time (depending on the network), the rewards should start appearing.

### Actual behavior

CPU usage really high + no rewards, + smeshing screen got reset

### Logs

[app-log.0.2.10-pr.1099.txt](https://github.com/spacemeshos/smapp/files/10522952/app-log.0.2.10-pr.1099.txt)
[spacemesh-log-6e4f4b3b.txt](https://github.com/spacemeshos/smapp/files/10522953/spacemesh-log-6e4f4b3b.txt)

**Comment by brusherru** [comment]
I believe it was fixed :)
