### ISSUE TITLE
Project migration story

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1112]
### Rationale

Keep our app secure and get the latest updates. We need to update our code base, to be able to continue work on features.
Below will be listed issues, that needed to be resolved before we will be able to update yarn.lock without issues.

[code base for reference](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

As part of my work on the [migration](https://github.com/spacemeshos/smapp/pull/1045) during the Sentry issue investigation
I can separate a few modules, that need to be updated before the final migration

- #1111 
- #1110 
- #1108 
- #1113 
- #1114
- #1115
- #1136 

After all these tasks, we need to update electron and electron-* packages, debugger, builder, etc.  [TODO create tasks]
The final step is to update folders and make them consistent, with the Main and Renderer process ( not desktop/app as we have right now) [TODO create a task for this]

**Comment by brusherru** [comment]
I believe we don't need to have these issues such as "Update some packages to the latest version".
Dependabot proposes to us from time to time to update it. That's enough.
