### ISSUE TITLE
Password requirements to be improved

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1157]
### Rationale

Currently we can set any password we like - it must only be at least 1 char long. There are no requirements whatsoever, which is ok in terms of testing convenience. 
For the Mainnet, there are three major aspects to be improved: 
1. Set some passwords complexity requirements policy
2. Improve password changing option - not allowing to change the password to the exact same as current one (which is now possible)
3.  Implement some helper in case of lost password if possible. (security questions? hint?) OR put more emphasis on 12 words backup.

### User story

- [ ] I open Smapp and set a new wallet with a strong password
- [ ] In case I want to change it later on, I can do it in settings
- [ ] If I forget my password (and the wallet was not backed up with 12 words), I can use some help option
- [ ] My wallet is safer (stronger password) and the Spacemesh related experience is better (less frustration and complaints about lost wallet due to the forgotten password)

### Acceptance criteria

- [ ] The basic scenario works as described
- [ ] I am not allowed to set the password weaker than the criteria that Spacemesh chooses as it's policy
- [ ] If I want to change the password, I have to provide a new, strong input.
- [ ] There is an option to remind the forgotten password

### Out of scope

Resetting the passwords using e-mails or any other personal data. 
Storing passwords in any way by Spacemesh to remind them
System's secure credentials storage / keychains etc. 

### How to test

check acceptance criteria

**Comment by brusherru** [comment]
1. YES.
    I believe anyone deserves to have strong passwords, so let's insist on having them :D 
    8 characters min, required upper&lower-case symbols, and at least one special char and one number?
2. Low priority
3. I don't think we need there to have any security questions.
    BUT adding steps to write down and double-check mnemonics on creating a wallet may be helpful for users not familiar with "best practices" in crypto.
    Example: any other wallet, usually on creating a new wallet offers you to write down your 12/24 words and then asks you to type in some words from the list as confirmation that you had backed up mnemonics.
