### ISSUE TITLE
not enough permissions to write a wallet file

### ISSUE THREAD

**Issue by HVNC1** [spacemeshos/smapp#1167]
### Environment

* Smapp version: 0.2.12
* Node version: v0.2.22 beta.0
* OS: Windows 10

### Describe the bug
![image](https://user-images.githubusercontent.com/95166695/221433941-a22e97a6-c5fa-4cb8-987b-96905f25efbd.png)

after deleting the wallet i tried to restore my wallet using mnemonic and got this error

**Comment by monikasmolarek** [comment]
reproduced. 

Steps: 
1. Open smapp, log to your wallet or create one
2. go to settings and delete this wallet
3. you're log out, choose to restore the already existing wallet, choose 12 words
4. proceed with the next steps
5. on the password setup screen, the ENOENT pops up 
6. restart smapp
7. try again to restore the wallet from mnemonics, then the json file is created and everything works as expected

**Comment by HVNC1** [comment]
after point 5 this appears


[image: image.png]

пн, 27 лют. 2023 р. о 21:05 Monika Smolarek ***@***.***> пише:

**Comment by maparr** [comment]
also need to check
<img width="736" alt="Screenshot 2023-03-04 at 11 01 02" src="https://user-images.githubusercontent.com/54288612/222916178-bf3112a8-a43e-4ed3-bb8d-e21b5ded14e3.png">
