### ISSUE TITLE
syncing malicious proofs

### ISSUE THREAD

**Issue by HVNC1** [spacemeshos/smapp#1168]
### Environment

* Smapp version: 0.2.12
* Node version: v0.22.2 beta0
* OS: Windows 10

### Describe the bug

unable to start sync
![image](https://user-images.githubusercontent.com/95166695/221434465-6d6819e1-8c50-439a-930e-6c9c876dff85.png)

### Logs

2023-02-26T22:04:58.532+0200	INFO	1c912.app.1c912.sync	syncing malicious proofs	{"node_id": "1c9121f3b29328b3c21781f8fdd2907d5c7a1b3d7c8c9b156c89986c56dd3452", "module": "app", "node_id": "1c9121f3b29328b3c21781f8fdd2907d5c7a1b3d7c8c9b156c89986c56dd3452", "module": "sync", "sessionId": "398f36da-19ff-4302-89bf-8523d0b75438", "name": "sync"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff6b92b40e2]

goroutine 306 [running]:
github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).GetMalfeasanceProofs(0xc0001e6600, {0x7ff6ba040f18, 0xc001eed500}, {0xc0037aa660, 0x1, 0xc00265f168?})
	D:/a/go-spacemesh/go-spacemesh/fetch/mesh_data.go:72 +0x302
github.com/spacemeshos/go-spacemesh/syncer.fetchMalfeasanceProof({0x7ff6ba040f18, 0xc001eed500}, {0xc00355ad20?, {0x7ff6b9b92e2f?, 0x0?}}, {0x7ff6ba030880?, 0xc000aa8380?}, {0x7ff6ba04c2b0, 0xc0001e6600}, 0xc0036ba980, ...)
	D:/a/go-spacemesh/go-spacemesh/syncer/data_fetch.go:271 +0x222
github.com/spacemeshos/go-spacemesh/syncer.(*DataFetch).PollMaliciousProofs(0xc0014bc870, {0x7ff6ba040f18?, 0xc001eed500})
	D:/a/go-spacemesh/go-spacemesh/syncer/data_fetch.go:106 +0x53e
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).syncMalfeasance(0xc00221a9a0?, {0x7ff6ba040f18?, 0xc001eed500?})
	D:/a/go-spacemesh/go-spacemesh/syncer/syncer.go:497 +0x32
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).synchronize.func1()
	D:/a/go-spacemesh/go-spacemesh/syncer/syncer.go:384 +0x329
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).synchronize(0xc0001e6780, {0x7ff6ba0425d8?, 0xc0008e04c0?})
	D:/a/go-spacemesh/go-spacemesh/syncer/syncer.go:422 +0xa13
github.com/spacemeshos/go-spacemesh/syncer.(*Syncer).Start.func1.1()
	D:/a/go-spacemesh/go-spacemesh/syncer/syncer.go:242 +0x107
golang.org/x/sync/errgroup.(*Group).Go.func1()
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	C:/Users/runneradmin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

[spacemesh-log-a06d8154.txt](https://github.com/spacemeshos/smapp/files/10834626/spacemesh-log-a06d8154.txt)
[app-log.0.2.12.txt](https://github.com/spacemeshos/smapp/files/10834627/app-log.0.2.12.txt)

**Comment by maxglf** [comment]
@HVNC1  thank you for the report. It is important issue. Team is working on it.

**Comment by maparr** [comment]
The fix for the go-spacemesh was merged, https://github.com/spacemeshos/go-spacemesh/pull/4092.
