### ISSUE TITLE
go-spacemesh installation on the self-hosted runners to fix

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1187]
### Environment

* Smapp version: any
* Node version: any 
* OS: self-hosted runners (arm64 linux+mac?)

### Describe the bug

Currently, on the self-hosted runners, the go-spacemesh is being installed/ builds uploaded and not cleared up (?).  
Related to the #1105  changes? 

To be checked. 

reported by NJ (in case more details are needed)

### Steps to reproduce

check GH Actions/ self-hosted runners logs 

### Expected behavior

Self-hosted runners are stateful; therefore, after each run should be left in a cleared/proper state for the next runs.

### Actual behavior

go-spacemesh builds stay there installed?

### Logs

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: The package spacemesh-app needs to be reinstalled, but I can't find an archive for it.
```

```
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
(Reading database ... 156272 files and directories currently installed.)
Removing spacemesh-app (0.2.10-pr.1105) ...
```

### How to fix 
add clean up step to GH Actions ?

**Comment by brusherru** [comment]
Tbh, I have no idea what is this issue about.
Since it is pretty old and we never heard about it again — I guess it is not actual :)
If I miss something — feel free to re-open the issue.
