### ISSUE TITLE
ENOENT while trying to backup wallet to the file

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1191]
### Environment

* Smapp version: 0.2.12 + custom from fix/1167
* Node version: v0.2.23-beta.0
* OS: Windows 10 Home (on Mac seems to be ok)

### Describe the bug
If we open a wallet from file, from any custom directory, if we want to then back it up to the file, we get the error

<img width="677" alt="Screenshot 2023-03-13 at 19 21 16" src="https://user-images.githubusercontent.com/89876259/224794284-92e65755-ddc1-4971-a575-59f440597945.png">
 
### Steps to reproduce

1.  Open Smapp
2.  Click "OPEN AN EXISTING WALLET"
3.  Choose the file located anywhere except the Spacemesh App directory
4. Click "BACKUP YOUR WALLET"
5. Choose the FILE BACKUP

### Expected behavior

The Wallet file should be backed up in the default (Documents) directory, we should get the confirmation screen with the link to the json file location. 

### Actual behavior

https://user-images.githubusercontent.com/89876259/224796193-d2e102bc-6b04-4695-9d8f-35fafc50cb9e.mp4

https://user-images.githubusercontent.com/89876259/224796198-5f7cb02d-2c19-4cb4-a955-c63800c25ab5.mp4

### Logs

```
18:40:00.387 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:40:01.074 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:40:05.544 > SmesherService.IsSmeshing called:   {}
18:40:05.546 > SmesherService.PostSetupStatus called:   {}
18:41:00.394 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:42:00.398 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:42:01.076 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:43:00.409 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:44:00.414 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:44:01.076 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:45:00.425 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:45:05.546 > SmesherService.IsSmeshing called:   {}
18:45:05.548 > SmesherService.PostSetupStatus called:   {}
18:46:00.437 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:46:01.079 > NodeService.Echo called:   {"msg":{"value":"ready"}}

```

### How to fix

**Comment by maparr** [comment]
additionally will try to close 
<img width="685" alt="Screenshot 2023-03-17 at 09 13 59" src="https://user-images.githubusercontent.com/54288612/225929713-09a27aec-2a91-45a2-8249-27b8c0d5271f.png">
