### ISSUE TITLE
GUI not showing rewards comming in - refreshing issue

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1192]
### Environment

* Smapp version: 0.2.13
* Node version:
* OS: Linux (unknown version)

### Describe the bug

Issue reported by Paktra on [Discord](https://discord.com/channels/623195163510046732/691261757921951756/1084913828132831302) and [Sentry](https://spacemesh.sentry.io/issues/3959990188/?project=6324919&query=is%3Aunresolved&referrer=issue-stream). 

The GUI didn’t show the rewards that were actually received. Restarting app refreshed the Rewards list. 

### Steps to reproduce

_Smapp has been interment for a couple of times within the last 24hrs. But it is fully synced for a few hours now. However, the last smeshing rewards is over 21hrs ago. Again, smapp has been fully synced._ 
Back to normal after the Smapp restart

### Expected behavior

The Smeshing tab should show the updates in real time. 

### Actual behavior

No updates until the app restart.

### Logs

Sentry

### How to fix 

related? #1076

**Comment by monikasmolarek** [comment]
Another similar case: 

_Used tap to send some smidge to my new wallet, next morning (9 hrs later) went to spawn wallet, node was synced but no smidge. 
Attempting to spawn wallet anyway resulted in a error due to no funds. 30 min later transactions appeared, with timestamps from many hours before, spawn was then succesful._

[appVersion-app-log.0.2.13-eventId-11194e925a9f483291680405a16e95a0.txt](https://github.com/spacemeshos/smapp/files/10971790/appVersion-app-log.0.2.13-eventId-11194e925a9f483291680405a16e95a0.txt)

**Comment by brusherru** [comment]
Partially fixed: https://github.com/spacemeshos/smapp/pull/1503
Partially should be fixed: https://github.com/spacemeshos/smapp/issues/1514
