### ISSUE TITLE
Add settings screen for PoS generation options

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#1202]
### Rationale
We need to find out and set the best options for PoS proof generation to be able to find out proof and publish it in time.
It depends on the number of nonces, CPU threads, and disk read speed. As a consequence, it also affects the PoS data size.

To do so, we will have a `post-profiler` CLI tool, which accepts nonces and threads as inputs and outputs generation speed in bytes per second. Besides this, probably we'll need to use another tool to check the disk read speed first. The idea is to make it easy enough for users to run benchmarks and choose the best option, and let them fine-tune these settings if they want any time. 

Since it affects PoS data size, it should be a part of PoS data initialization (like an extra step) and also there should be a button to change the settings any time after generation PoS. It should be roughly the same screen.

To enlarge the probability of finding PoS proof in the single run we need to generate proofs for a larger amount of nonces (check the graph below), so in case the User has a slowish CPU he will have to choose fewer nonces, and then he can choose to have a fewer data size (to be able to read it a couple of times and generate nonces in N cycles) or choose less probability of finding proof.

![image](https://user-images.githubusercontent.com/1897530/227571445-9ea42d0e-f59e-4062-9b7e-cde5abadfb2d.png)

Smapp should propose to User select from one of the options (aka constant values, that are used in the benchmarks). And also provide an ability to set their custom values and run benchmark over them.

How it should work:
1. Run `post-profiler` tool with values:
   - `nonces=40 threads=1`
   - `nonces=80 threads=1`
   - `nonces=160 threads=1`
   - `nonces=200 threads=1`
2. Calculate the maximum PoS size for all options: it means that the bigger PoS size with such options would not work at all, since there would not be enough time to read and generate a proof.
3. User selects one of the options, and can also adjust `threads` value and rerun the benchmark. Then it may change the maximum data size.
4. To calculate the maximum data size, we need to evaluate `cycleGap * safetyPeriod * speed`, where
    - `safetyPeriod` is a constant like `0.8` just to have 20% of cycle gap in reserve for being able to generate and publish proof in case of throttling / high CPU usage and etc,
    - `speed` is the output speed (bytes per second) returned by benchmark tool

### Prerequisites
- https://github.com/spacemeshos/post-rs/pull/24
- https://github.com/spacemeshos/go-spacemesh/issues/4314

### User story
- [ ] I run Smapp in local node mode, open Smesher screen
- [ ] I start setting up PoS data
- [ ] After selecting PoS data location it should bring me to the new screen
- [ ] I click on the big button called "Run benchmarks"
- [ ] Wait for 1-3 minutes. It should add benchmark results on the screen in real time.
- [ ] By clicking on the benchmark result it copies options (nonces & threads) to the inputs. And memorize recommended data size for the next step. <-- probably we should hide nonces to avoid confusing Users?
- [ ] I also can change these options manually and click on a smaller button "Run benchmark for this options"
- [ ] When the inputs are filled — I can go next and specify data size, and I'll see their memorized recommended data size.
- [ ] After finishing setting up PoS data I can always tweak PoS generation options by clicking on the button on the Smesher screen: "Tune PoS generation"

### Acceptance criteria
- [ ] The basic scenario works as described
- [ ] User can proceed with PoS initialization without selecting/typing PoS generation options: nonces and threads.

### Out of scope
Cool graphics and extended explanations.

**Comment by pigmej** [comment]
@brusherru https://github.com/spacemeshos/go-spacemesh/pull/4315 ;-)
