### ISSUE TITLE
GPU Vram use even when not smeshing / initializing

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/smapp#1229]
At first reported by the community and reproduced now.

1. You need Nvidia GPU
2. Linux

Fresh smapp setup, nvidia-smi installed

1. run them side by side, (`watch -n 1 nvidia-smi`) prepare smapp, after initial setup, STAY on network screen.
2. Validate the VRAM used by GPU. (should be ~small)
3. Click smashing screen -> observe VRAM being fully used.
![image (2)](https://user-images.githubusercontent.com/496754/233481707-d353420d-9de7-4d1e-8fcc-1c29aa2a3ad7.png)

The logs are from an instance where I reproduced it twice in a row.
[app-log.txt](https://github.com/spacemeshos/smapp/files/11290279/app-log.txt)
[spacemeshlog.txt](https://github.com/spacemeshos/smapp/files/11290281/spacemeshlog.txt)

**Comment by paintmeyellow** [comment]
Same here. Sent the report.
![image](https://user-images.githubusercontent.com/24860764/233723166-becb151b-4a06-4389-a01e-0954ce8e6571.png)

**Comment by pigmej** [comment]
![Screenshot_20230421_225218.png](https://user-images.githubusercontent.com/496754/233768961-5cf765df-5a01-44cf-b9e2-7cfd0f07a365.png)

Report from the community.

**Comment by brusherru** [comment]
I think it is not actual anymore
