### ISSUE TITLE
Add a confirmation modal for POS data deletion

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1235]
### Rationale

Now the "Delete data" button triggers the deletion immediately. If used by any kind of mistake/accident, it will cause quite an unpleasant situation when the Smeshers would have to regenerate POS - which will be expensive in terms of the time and resources usage needed for this process and lost rewards that could have been received otherwise. 

![image](https://user-images.githubusercontent.com/89876259/234634767-df14974a-3d80-43fc-9197-27f3156cd28a.png)

It would be good to implement a modal - an additional step with a confirmation with some kind of "Are you sure you want to delete your POS data?" content and two buttons - to proceed and abort the process. 

### Prerequisites
/

### User story

- [ ] I open the Smeshing screen (having the POS already set up)
- [ ] I click the `Edit` button
- [ ] I click there the `Delete Data` button
- [ ] I get a confirmation popup before my POS data is actually deleted

### Acceptance criteria

- [ ] The basic scenario works as described
- [ ] The pop-up show up each time we click the "Delete data" button
- [ ] The message on the modal is explicit, understandable, and maybe contains some warning about the consequences?
- [ ] If I click the "Cancel" button, the POS data stays untouched, and the Smeshing process continues with no issue
- [ ] Once I click the "Confirm" button, the POS data is deleted, and the Smeshing screen gets back to the initial state. The smeshing process ends. 
- [ ] no regression

### Out of scope
/
### How to implement
/
### How to test

as above

**Comment by maparr** [comment]
it closed in #1258
