### ISSUE TITLE
Error in key derivation

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#1237]
The same mnemonic in `smcli wallet create` and smapp is now producing two different keys:

```
./smcli wallet read ~/.config/Spacemesh/my_wallet_2023-04-18T17-14-24.445Z.json -p
Enter wallet password:
2023/04/26 17:05:08 Warning: wallet file iterations count lower than recommended
+-------------------------------------------------------------------------------------------------------------+
| Wallet Contents                                                                                             |
+----------------------+----------------------+---------------------+--------------+--------------------------+
| PUBKEY               | PRIVKEY              | PATH                | NAME         | CREATED                  |
+----------------------+----------------------+---------------------+--------------+--------------------------+
| a6c95349c8224..b7d82 | afa0ffdb92ef5..5228a | m/44'/540'/0'/0'/0' | Main Account | 2023-04-18T17-14-24.445Z |
+----------------------+----------------------+---------------------+--------------+--------------------------+
Mnemonic: abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon

> ./smcli wallet read ~/.spacemesh/wallet_2023-04-26T20-55-55.891Z.json -p
Enter wallet password:
+------------------------------------------------------------------------------------------------------------+
| Wallet Contents                                                                                            |
+----------------------+----------------------+---------------------+-------------+--------------------------+
| PUBKEY               | PRIVKEY              | PATH                | NAME        | CREATED                  |
+----------------------+----------------------+---------------------+-------------+--------------------------+
| 06ea119a4bf7a..46ecc | a35668e1ce0eb..46ecc | m/44'/540'/0'/0'    | Master Key  | 2023-04-26T20-55-53.806Z |
| d4c1a605f1468..cb905 | 74c16d3e7148d..cb905 | m/44'/540'/0'/0'/0' | Child Key 0 | 2023-04-26T20-55-53.806Z |
+----------------------+----------------------+---------------------+-------------+--------------------------+
Mnemonic: abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon
```

I've verified that the behavior of `smcli` is correct as it matches the behavior of the solana keygen tool and the ledger hardware wallet, so something is wrong in smapp. I suspect the error is here:

https://github.com/spacemeshos/smapp/blob/e250ff64aa591e07b9a7ce2633c52ee9e620cbad/desktop/main/bip32-key-derivation.ts#L16-L23

Note how smapp uses the _first_ 32 bytes as the secret key. Here's the corresponding go code:

https://github.com/spacemeshos/smcli/blob/669ec023f8478e3f22090c9d4f1b090ed94bf25d/wallet/bip32.go#L71-L81

If you look at what `ed25519.PrivateKey.Public()` is doing, you can see it's using the first 32 bytes as the public key:

https://cs.opensource.google/go/go/+/master:src/crypto/ed25519/ed25519.go;l=55-60;drc=84609d874e19e9d2419e07b72e8c8e2d24dcfc3a

We need to reconcile this behavior.

**Comment by lrettig** [comment]
Is it possible to use a similar, battle-tested ed25519 library on the smapp side to avoid errors here?

**Comment by brusherru** [comment]
> Is it possible to use a similar, battle-tested ed25519 library on the smapp side to avoid errors here?

Of course, we can switch to any other ed25519 library or even use the stdlib `crypto`.
Then we'll be able to remove the https://github.com/spacemeshos/ed25519-WASM dependency from Smapp (which is just bundled, btw 🤢 )

**Comment by brusherru** [comment]
@lrettig do I need to store the Master key in the wallet file as well?
Or do you leave it here just for debugging?

**Comment by lrettig** [comment]
> @lrettig do I need to store the Master key in the wallet file as well? Or do you leave it here just for debugging?

No, that's not required - we may remove it on the smcli side as well. Just the `m/44'/540'/0'/0'/0'` "child" key is sufficient. Thanks!
