### ISSUE TITLE
regression - return/enter on wallet creation - password step

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1253]
### Environment

* Smapp version: 0.3.4 |  pr1226, 1234
* Node version: 
* OS: any

### Describe the bug

hitting Return / Enter on the CREATE YOUR WALLET step 

- doesn’t proceed to the next screen
- ❗️**does** create a new wallet file each time we hit Enter/Return 
- if the _Verify Password_ input field isn't focused, hitting Return/Enter doesn’t work 

https://github.com/spacemeshos/smapp/assets/89876259/ae8214f3-3c03-405b-a802-861b7a871df7

### Steps to reproduce

1.  Open SMAPP and start to create a new Wallet
2.  Pn the 4th screen, CREATE YOUR WALLET, put any password, and move to the next field (tab or cursor click)- repeat the password correctly in the verification field. Don’t "unclick" this field, keep it focused.
3. Click Return / Enter 
4. Click anywhere on the screen to deactivate the password verification field and click Enter again

### Expected behavior

If a password is correctly set, clicking Enter/Return should create a new Wallet and at the same time move the User to the next screen. Additionally, it shouldn’t work only if the input field is active. Having this screen open, hitting Enter should always try to trigger the [NEXT] button action. 

### Actual behavior

as explained above

**Comment by brusherru** [comment]
I don't think we need to listen for ENTER keypress anytime being on this screen.
But both input fields should listen for it. Also, the first input should have an autofocus.

In other words:
- First input should be focused by default
- Pressing ENTER, while any of the inputs are focused, should lead to the next screen
- There should be no different handlers for the ENTER keypress and the next button

**Comment by monikasmolarek** [comment]
Totally agree. 
And additionally, I would suggest rephrasing `'Create your wallet with a password. You will need it to access latter'`, cause it's not super correct and not bringing too much of the added value. 
Maybe `"With this step, your Wallet will be created. Set up a password you will be using to access it later. Remember, there will be no way to recover the lost password."  `
WDYT?
