### ISSUE TITLE
Unable to by pass the Proof of Generation Settings.

### ISSUE THREAD

**Issue by Proskhmer08** [spacemeshos/smapp#1274]
### Environment

* Smapp version: 0.3.7 | develop
* Node version: testnet-05
* OS: Windows 10 
* 
### Describe the bug

After node is fully synced and after setting up POS, I was able to successfully run the benchmarks from Proof Generation Settings. But Smeshing tab shows red with status of waiting for node to be fully synced. However, the Network tab is green with status as synced.

So then I logged out of the smapp and logged back in. Now the Smeshing tab shows I have to re-setup my POS. So I move forward with selecting the drive for POS but after completing all the benchmark again for Proof Generation Settings, I am unable to move past this page and complete the POS setup. If I switch tab to Network tab, and return to Smeshing tab, I have to redo the POS setup again but the cycle repeats and gets stuck at the Proof Generation Settings.

### Steps to reproduce

Same as above

### Expected behavior

The smapp should show that the POS was set up and the smapp should start smeshing.

### Actual behavior

Smapp is not smeshing and unable to move past the Proof Generation Settings. 

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.
<img width="778" alt="Screenshot 2023-06-09 at 8 30 15 AM" src="https://github.com/spacemeshos/smapp/assets/35155781/8545d9e8-7b9a-4a2a-86b1-fbfd5ce504bd">

**Comment by monikasmolarek** [comment]
Not applicable anymore
