### ISSUE TITLE
check for empty string on tx send amount

### ISSUE THREAD

**Issue by tjb-altf4** [spacemeshos/smapp#1276]
### Environment
* Smapp version: 0.3.7 | develop
* Node version: v0.3.7-beta.0
* OS: Ubuntu 22.04

### Describe the bug
Tx send amount validation allows empty string.
Empty string is implicitly converted to a "zero" transaction amount.

### Steps to reproduce
1. Smapp > Wallet > Send
2. Add receive address, but leave "Amount" empty
3. Next >Send

### Expected behavior
Input validation should prompt user to enter a tx amount (even if it needs to be "0" zero).
Behaviour should be similar to the input validation shown on "To" tx receive address entry field, and should also be a blocking action.

### Actual behavior
Empty "Amount" in send tx results in an unexpected "0" zero amount to be sent.
Lack of input validation treats blank field the same as an explicitly set "0" zero amount.

### Other
also raised on discord: https://discord.com/channels/623195163510046732/691261757921951756/1117260721282109490

**Comment by monikasmolarek** [comment]
Hey @tjb-altf4, Thank you for testing Smapp and reporting bugs! 
This one, however, is a point we are aware of, and it is meant to work like that. Users might want to be able to send such 0 transactions as a confirmation of something or authorization.
It will be more useful and understandable with other account types and smart contracts in the future.
