### ISSUE TITLE
Display MiB/s next to hash/s when working with GPUs

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/smapp#1308]
Currently we use hash/second as an unit. We should also show MiB/s.

One hash == one label, one label 16B so the math is simple there :)

**Comment by monikasmolarek** [comment]
I would add the below suggestion to work on both together: 

_On [the progress indicator] of the smesher interface when generating the initialization data, include a calculated rough estimate of the initialization speed and estimated time of completion. For example: `11.92 GiB / 800 GiB, 1.49% - ~22 GiB/hr - ~36 hours left`_
