### ISSUE TITLE
Node Activity Log issues

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1348]
### Environment

Smapp version: 0.3.15
Node version: v0.3.13-beta.0 (devnet402short)
OS: Windows 10 | macOS ventura (13)

### Describe the bug

- After Smapp restart the status log cleares out: 

https://github.com/spacemeshos/smapp/assets/89876259/6bd04110-382d-4b46-80fd-bf97c9ebbe00

- duplicates in the Node Activity Log

<img width="1442" alt="Screenshot 2023-07-13 at 04 59 10" src="https://github.com/spacemeshos/smapp/assets/89876259/30b1f097-2f55-4892-bfd3-f0e9e114367e">
<img width="1442" alt="Screenshot 2023-07-13 at 04 57 00" src="https://github.com/spacemeshos/smapp/assets/89876259/3e48cdf7-da06-42af-9849-7993dffda492">
<img width="1442" alt="Screenshot 2023-07-13 at 05 25 59" src="https://github.com/spacemeshos/smapp/assets/89876259/0239771e-1633-45dc-9407-d569862b1975">

And additional thing, but I could not reproduce it (it happened only on Windows after deleting data and setting it up again):

![DBW4pIeHH4](https://github.com/spacemeshos/smapp/assets/89876259/341d9379-675a-4874-9bd9-337cc28ba230)
![q5ISrOBe9J](https://github.com/spacemeshos/smapp/assets/89876259/f21d5c3c-6897-4a2a-a106-f6d8f11b90e6)
![JDjF0fZfwV](https://github.com/spacemeshos/smapp/assets/89876259/cdcdcc32-7cbe-4aab-9632-1d8d3e56f679)

### Steps to reproduce

1.  set up smesher
2.  observe the activity logs
3.  delete the pos data and set up again from scratch
4. observe the activity logs
5. restart application and check the node activity log

### Expected behavior

There shouldn’t be duplicates (doubled lines and the whole chunks of history repeated.
After the restart I assume the smesher activity history should be still available in the log, now it disappears 

### Actual behavior
as above

### Logs
[spacemesh-log-bfd22af5.txt](https://github.com/spacemeshos/smapp/files/12035085/spacemesh-log-bfd22af5.txt)
[app-log.0.3.15.txt](https://github.com/spacemeshos/smapp/files/12035086/app-log.0.3.15.txt)

**Comment by brusherru** [comment]
> After Smapp restart the status log cleares out:

It is expected behavior.
Smapp does not store this log and Node will send all the actual events once it is connected again.
Most likely that's how you caught "duplicates" ;)

> duplicates in the Node Activity Log

I'll get rid of duplicated 👌

**Comment by brusherru** [comment]
> it happened only on Windows after deleting data and setting it up again

Seems like something failed in producing PoS data (need node logs), which then causes some problems in Smapp...
This is unrelated to Activity Logs, but Smapp should handle such cases properly. At least it should not fail on ENOENT :)

**Comment by brusherru** [comment]
Not actual anymore.
