### ISSUE TITLE
Don't prompt to backup mnemonic after restore from mnemonic

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#1358]
### Environment

* Smapp version: 1.0.3

### Describe the bug

Smapp should not prompt the user to backup mnemonic immediately after restoring wallet from mnemonic

### Steps to reproduce

Restore a wallet from a mnemonic

**Comment by maparr** [comment]
additionally, we have RESTORE EXISTING WALLET link on the NEW WALLET select page, which confused users, which used mnemonic to restore the wallet.

Need to remove it.

**Comment by brusherru** [comment]
Seems it is done.
