### ISSUE TITLE
Feature Proposal: smapp increase hash power display

### ISSUE THREAD

**Issue by robandfender** [spacemeshos/smapp#1366]
Function description:
After Smapp is started, after selecting GPU/CPU to create a POS solution, it is recommended to display the hash power on the UI to let everyone know the latest value of the hash power set by you.

Hash power unit:
EH/s、PH/s、TH/s、GH/s、MH/s、KH/s、H/s

**Comment by monikasmolarek** [comment]
Kind of duplicates the #1308
