### ISSUE TITLE
Misinterpretation in display of TiB in POST

### ISSUE THREAD

**Issue by kalekoi** [spacemeshos/smapp#1367]
### Environment

* Smapp version: 1.0.4 
* Node version: v1.0.2
* OS: Windows 11 

### Describe the bug

In progress, when creating the POST, it tells me 1.91 TiB / 13054.75 TiB, 0.01%, when the total should be 13 TiB, the percentage is also incorrect, I'm afraid it's a real number and I'll never complete the task, I wanted to know fix it without erasing the advance.

![Captura de pantalla 2023-07-15 200842](https://github.com/spacemeshos/smapp/assets/159061/55de7245-a7b6-460d-85b4-de5ea58794d4)

**Comment by brusherru** [comment]
@kalekoi thanks for the report!
Could you check the `"smeshing-opts-numunits"` property in your `node-config.json` just to be sure?

**Comment by kalekoi** [comment]
smeshing-opts-numunits":208876,

**Comment by poszu** [comment]
@kalekoi that's around 13PB. To fix it, you can do:
 - shutdown smapp
 - open node-config.\<network id\>.json
 - decrease `smeshing-opts-numunits`. One unit is 64GiB
 - save and start smapp

Cc @brusherru

**Comment by kalekoi** [comment]
Ok, solved, thanks for the quick help
