### ISSUE TITLE
Auto Updating

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#137]
1. Add signature step to app packing
2. Setup auto update on wallet restart
3. Setup auto update once in time period (24 hours)
4. Add UI in settings tab to control auto update, check for update and manual update

**Comment by avive** [comment]
- App should periodically check for app updates while it is running (every 24 hours) and also on new app session (app start after quitting)
- If the app main window is minimized and there's an update available - automatically update.
- If the app main window is open and there's an update available - notify the user and prompt to update.
- An updated app, after being installed needs to have the capability to delete all existing node data including post, start the node, set the coinbase account on it (main user wallet account), and prompt the user to setup block producing / post again via the node tab.

**Comment by avive** [comment]
Let's put auto updating on hold for now.

**Comment by IlyaVi** [comment]
reopening, better leave it in tech debt not to loose tasks left to implement

**Comment by avive** [comment]
fine but please don't work on it yet.

**Comment by brusherru** [comment]
Outdated. See an actual issue: #863

**Comment by brusherru** [comment]
Outdated. See an actual issue: #863
