### ISSUE TITLE
Main Network THE SPACEMESH NODE SOFTWARE HAS UNEXPECTEDLY QUIT. CLICK ON 'RESTART NODE' TO START IT.

### ISSUE THREAD

**Issue by ndcc5** [spacemeshos/smapp#1375]
Newly installed Windows 10 system, not virtual machine, running wallet prompts error.
c++ has been installed.
![M3GI ZV%9WKP`CQWC`A0PFI](https://github.com/spacemeshos/smapp/assets/6286019/9f937504-a7f0-4bef-858b-cdc9ce2d3a71)
By the way, the log file is empty.

**Comment by pigmej** [comment]
do you have proper support for OpenCL ?

**Comment by ndcc5** [comment]
sloved
