### ISSUE TITLE
Stop smeshing clean up smeshing-proving-opts in config 

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1385]
### Environment

* Smapp version: latest

### Describe the bug
 per title 
 
trigger an issue with go-spacemesh node 

### Steps to reproduce

1. Start smapp
2. Start smeshing and select nonces and threads 
3. See these values in node-config.json in the APP_FOLDER
4. Stop smeshing
5. See the smeshing-proving-opts in node-config.json empty 

### Expected behavior

smeshing-proving-opts property should not be rewritten after stop smeshing 
### Actual behavior

smeshing-proving-opts property is empty in the node-config.json

**Comment by pigmej** [comment]
@maparr, where are we with that?
