### ISSUE TITLE
UNEXPECTEDLY QUIT error

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1389]
### Environment

* Smapp version: 1.0.5 | develop
* OS: Windows 10

### Describe the bug

After I update from 1.0.4 to 1.0.5, PoS data creating is failed.
Please check attached screen shot and log.

### Steps to reproduce

1.  Override install 1.0.5.
2.  Start Smapp.

### Expected behavior

Running fine.

### Actual behavior

Showing error and can't proceed.
I have tried RESTART NODE and restart Smapp. But nothing solved.

### Logs
![スクリーンショット 2023-07-21 2 13 44](https://github.com/spacemeshos/smapp/assets/2483747/1199bc15-7028-4804-a085-5b4e1d08b0a7)
![スクリーンショット 2023-07-21 2 13 51](https://github.com/spacemeshos/smapp/assets/2483747/2a7b473a-4a60-4771-af5f-5b8510914042)

[Uploading log.txt…]()

**Comment by brusherru** [comment]
@hryksbt seems log file was not uploaded :( Could you upload it, please?

**Comment by hryksbt** [comment]
[log.txt](https://github.com/spacemeshos/smapp/files/12112470/log.txt)
Here you are.

**Comment by brusherru** [comment]
@hryksbt thanks for the report and for the quick response!
We just made a little investigation with the team and can't find any issues in the codebase.

Please, try to do these steps:
1. Run `chkdsk` (scan disk) against disk with PoS data
2. If the check disk does not find any errors, then try to rename `postdata_5.bin` into `postdata_5.bak`, it should reinitialize only  this file and keep others

And please, let me know does it help or not 🙏

**Comment by brusherru** [comment]
If someone faced the same problem — please write a comment and attach your logs 🙏

**Comment by AshenCZ** [comment]
Same. Ater update form 1.0.4 to 1.0.5
I tried going back to version 1.0.4 but the problem persists.

[app-log.1.0.4.old.txt](https://github.com/spacemeshos/smapp/files/12113688/app-log.1.0.4.old.txt)
[app-log.1.0.4.txt](https://github.com/spacemeshos/smapp/files/12113698/app-log.1.0.4.txt)

[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12113687/spacemesh-log-7c8cef2b.txt)

**Comment by hryksbt** [comment]
@brusherru Thank you for your kindly support.
I have deleted once then started to create again.
If I face same trouble again, I will try what you mentioned.
Thank you.

**Comment by AshenCZ** [comment]
After wipe data, deleting all Spacemesh folders from user\appdata and a clean install of 1.0.5 I was able to mount my old wallet and use the PoST data already generated. 
I am now at the status "Waiting on PoET registration windows in 3 days". So I think everything is working as it should.
