### ISSUE TITLE
Network cannot be established after update 1.0.5.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1390]
### Environment

* Smapp version: 1.0.5 | develop
* OS: Ubuntu 20.04

### Describe the bug

Network cannot be established. But OS network is working fine.

### Steps to reproduce

1. Update from 1.0.3 to 1.0.5
2. Start Smapp
3. Login to wallet with password

### Expected behavior

Network connection works and PoS creation works.

### Actual behavior

Network connection doesn't works so PoS creation doesn't work.

### Logs
Attached
![スクリーンショット 2023-07-21 21 18 38](https://github.com/spacemeshos/smapp/assets/2483747/ad572374-e2c9-4541-baec-ce626f8e6ee9)
[network.txt.zip](https://github.com/spacemeshos/smapp/files/12123565/network.txt.zip)

**Comment by hryksbt** [comment]
After OS reboot, it works fine.
Please inspect the reason.

**Comment by superphiz** [comment]
Are you sure you're on Ubuntu 20.04? I thought the minimum requirement was 22.04. I don't think it would cause this bug, but worth checking.
