### ISSUE TITLE
Get rid of throttle PoS creation option: "Pause when someone is using this computer"

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1393]
### Environment

* Smapp version: 1.0.5
* Node version: v1.0.2
* OS: Windows 10 | macOSVentura 

### Describe the bug

The "_Pause smeshing when someone’s using computer_" option does not work? 

I have never noticed any behavior confirming that this feature works. (for example status change, button "resume" appearing, resources usage change etc.). 

Tested it with an online GPU stress test.  

### Steps to reproduce

1.  Set up smeshing, toggle the "PAUSE WHEN SOMEONE IS USING THIS COMPUTER" option
2.  Wait until the node restarts and generating data begins
3.  run any kind of software/test requiring quite a significant GPU work.
4. Observe smapp and activity monitor /task manager

### Expected behavior

The POS data generation process should be paused when the GPU is being used by another process.

### Actual behavior

the POS data continues to be generated no matter what is happening with the GPU usage.

<img width="1680" alt="Screenshot 2023-07-22 at 02 32 52" src="https://github.com/spacemeshos/smapp/assets/89876259/74da8e0b-8355-4b6b-a67f-ff8465dba9df">
<img width="1442" alt="Screenshot 2023-07-22 at 02 21 32" src="https://github.com/spacemeshos/smapp/assets/89876259/71f72f16-56a9-44f1-96cc-26f96d42f9b6">

**Comment by brusherru** [comment]
Okay. It is not working on the go-spacemesh side. And probably it won't be fixed.
So let's get rid of this option in Smapp.
