### ISSUE TITLE
Free disk space incorrectly calculated

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1400]
### Environment

* Smapp version: 1.0.7
* Node version: v1.0.6
* OS: macOs Ventura 13.4

### Describe the bug

Smapp shows incorrect values in terms of the free space in the chosen location. 

<img width="1680" alt="Screenshot 2023-07-25 at 00 00 22" src="https://github.com/spacemeshos/smapp/assets/89876259/e5df3e31-6603-4e1a-b69e-98b39778a5de">

### Steps to reproduce

Just try to set up POS and verify if the amount of free disk space is correctly reflected in Smapp

### Expected behavior

correct value 

### Actual behavior

^^

### How to fix 
maybe worth to be combined with #1399

**Comment by brusherru** [comment]
We need to update `check-disk-space` package to the latest one.
And hopefully, it will fix the issue.
