### ISSUE TITLE
Autostart to fix 

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1403]
### Environment

* Smapp version: 1.0.7
* Node version: v1.0.6
* OS: macOS

### Describe the bug

After computer reboot  Smapp is launched at the system start (even if we don't toggle the autostart option) and gets stuck on the loading screen (not always, I happens to log in). 
When the sautostart is toggled, the login and node start are ok. 

https://github.com/spacemeshos/smapp/assets/89876259/a0ba7cc2-fdce-4242-9949-01cc2cbf5c2c

### Steps to reproduce

1.  Use Smapp
2.  Close Smapp
3.  Restart your computer
4. wait a bit for smapp to show up
5. log in to your wallet

### Expected behavior

If we don’t toggle the autostart option in settings - don't start on the system startup
if we log in to wallet, the node should run, smapp should open on the wallet overview screen

### Actual behavior

Smapp autostarts and gets stuck

### Logs

[app-log.1.0.7.txt](https://github.com/spacemeshos/smapp/files/12155712/app-log.1.0.7.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12155713/spacemesh-log-7c8cef2b.txt)

**Comment by brusherru** [comment]
We need to confirm whether is it actual or not, and then close or prioritize the issue.

**Comment by monikasmolarek** [comment]
@brusherru it is still actual - app opening even if autostart is off. Regarding the part where it gets stuck with a loading screen, it still happens, but I haven’t found the reason/way to reproduce it (yet?).
