### ISSUE TITLE
Network not working "The Spacemesh node software has unexpectedly quit. Click on 'restart node' to start it." 

### ISSUE THREAD

**Issue by selimyo** [spacemeshos/smapp#1416]
### Environment

* Smapp version: 1.0.9
* Node version: Blank since Node not starting
* OS: Windows 11

### Steps to reproduce

The issue started after setting up my wallet, being connected and starting to smesh/init successfully. I left my app open for just a few hours (3-4) and then noticed the network error. I've been trying to fix ever since (over a week now) by restarting the app, restarting the PC, reinstalling the app, adding ports to be open, checking on firewall, checking GPU and Intel drivers, installing latest visual c++, making sure my time is synced correctly, and granting the app admin rights.

What’s happening now?

![image](https://github.com/spacemeshos/smapp/assets/66976493/b48c5ab0-ebe4-4431-8873-be93e25d8758)

### Logs

[app-log.1.0.9.txt](https://github.com/spacemeshos/smapp/files/12225647/app-log.1.0.9.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12225665/spacemesh-log-7c8cef2b.txt)

Would really appreciate your help with this! I was very excited to be a part of Spacemesh Genesis and I even bought a spare PC to keep on at all times, but I'm cut out of participating for now and it sucks to not even understand the reason behind this.

**Comment by ciciban74** [comment]
I have the same problem, did you solve it?

**Comment by selimyo** [comment]
> I have the same problem, did you solve it?

No, not yet sorry. One person with a similar issue told me it was only fixed for them by using an entirely different computer.

**Comment by brusherru** [comment]
Oops. Sorry, missed your issue :(
Seems like `postdata_metadata.json` file inside your PoS directory was corrupted somehow...
Hopefully, it is not actual anymore?

**Comment by monikasmolarek** [comment]
Outdated
