### ISSUE TITLE
Should not benchmark POST providers / query for providers unless needed

### ISSUE THREAD

**Issue by poszu** [spacemeshos/smapp#1428]
### Environment

* Smapp version: develop
* Node version: doesn't matter
* OS: doesn't matter

### Describe the bug

Smapp queries POST setup providers GRPC endpoint with `benchmark = true` on boot.

### Steps to reproduce

Run Smapp and observe node logs.

### Expected behavior

Smapp should not run benchmark (it probably doesn't need to query POST providers either) unless a user wants to setup POST initialization.

### Actual behavior

Smapp queries POST setup providers GRPC endpoint with `benchmark = true` on boot.

### Logs

N/A

### How to fix 

N/A

**Comment by brusherru** [comment]
Fixed by https://github.com/spacemeshos/smapp/pull/1512
