### ISSUE TITLE
Implement: export the transactions log

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1434]
### Rationale

It might be useful to have the possibility to export the transactions history

### Prerequisites

#1433 

### User story

1. I open the Wallet screen and click on the “All transactions” button.
2. In the Transaction log screen I want to have an option to export my transactions.
3. Nice to have: the export option gives various formats (csv, xml, JSON, PDF…?)
4. I want to be able to select multiple filter criteria to narrow the results to be exported.
5. I want to cancel the process at any moment.
6. I want to be able to select the directory and name for the file to be saved.

### Acceptance criteria

- [ ] The basic scenario works as described
- [ ] If I cancel the process, I get back to the default transactions log 
- [ ] the generated file contains the correct set of data (correct timeframes/filtering)
- [ ] the records are saved correctly (formats and values of the transactions details)
- [ ] Once exported I get any sort of confirmation
- [ ] If there was any error, I get the appropriate info/modal

### Out of scope

taking over any kind of responsibility regarding the exported files' security.

**Comment by brusherru** [comment]
Some community members asking about exporting rewards.
The point is that it will be much easier to calculate taxes by having a spreadsheet (csv) of reward amounts and dates.

\+ I'm not sure that #1433 is actually a prerequisite... I think it is a separate enhancement.

So probably we need to prioritize the issue? 🤔

**Comment by brusherru** [comment]
Also, I think we should not overcomplicate and do the simplest solution:
- Allow to export only transactions or only rewards
- Export only in .csv format
- Export all fields without an option to choose which ones
