### ISSUE TITLE
no rewards

### ISSUE THREAD

**Issue by HVNC1** [spacemeshos/smapp#1438]
Smapp version: 1.0.14
OS: Windows 10 

smasher id 0xe20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4

Log file
[spacemesh-log-7c8cef2b.zip](https://github.com/spacemeshos/smapp/files/12327278/spacemesh-log-7c8cef2b.zip)

**Comment by dshulyak** [comment]
could you please upload more recent logs for this node?

it generated this proposal couple of hours ago, i want to understand details 

> {"L":"INFO","T":"2023-08-12T11:35:06.156Z","N":"9787b.proposalListener","M":"new ballot","node_id":"9787b82b2f7495406f8642446928feee3e3e52a351c5a6706ca6ce9bbc13e81e","module":"proposalListener","requestId":"9b378acf-3ea4-43d0-ba70-d6420111a71c","proposal_id":"58f81a2a3a","ballot_id":"e4dad0e256","layer_id":8395,"ballot_id":"e4dad0e256","layer_id":8395,"epoch_id":2,"smesher":"e20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4","opinion hash":"198d114718","base_ballot":"448847d2a2","support":0,"against":51,"abstain":1,"atx_id":"1e224c0eb8","ref_ballot":"e3617f3a07","active_set_size":0,"beacon":"00000000","votes":{"base":"448847d2a2","support":[],"against":[{"id":"0419e00194","layer":8393,"height":0},{"id":"9b17fc171f","layer":8392,"height":0},{"id":"7ab88041bd","layer":8391,"height":0},{"id":"5bbda93527","layer":8390,"height":0},{"id":"2f495e3b67","layer":8389,"height":0},{"id":"53163836a8","layer":8388,"height":0},{"id":"8c6e177d74","layer":8387,"height":0},{"id":"b7559fc688","layer":8386,"height":0},{"id":"127dbc2480","layer":8385,"height":0},{"id":"ca63ff6b24","layer":8384,"height":0},{"id":"758b347987","layer":8383,"height":0},{"id":"4fa054d507","layer":8382,"height":0},{"id":"6c95b0d4da","layer":8381,"height":0},{"id":"a5c07c1096","layer":8380,"height":0},{"id":"71faabe82c","layer":8379,"height":0},{"id":"067f96320e","layer":8378,"height":0},{"id":"a45defaf73","layer":8377,"height":0},{"id":"83baeaf622","layer":8376,"height":0},{"id":"5581cae37a","layer":8375,"height":0},{"id":"25f01a0a50","layer":8374,"height":0},{"id":"384c4727a9","layer":8373,"height":0},{"id":"d4748043a3","layer":8372,"height":0},{"id":"db5f8f6b2c","layer":8371,"height":0},{"id":"814a94053e","layer":8370,"height":0},{"id":"69188e6a2e","layer":8369,"height":0},{"id":"63041f372d","layer":8368,"height":0},{"id":"278364e9b2","layer":8367,"height":0},{"id":"54bd505ff3","layer":8366,"height":0},{"id":"0f6277fe5a","layer":8365,"height":0},{"id":"c2b58f0dfd","layer":8364,"height":0},{"id":"8da442095e","layer":8363,"height":0},{"id":"a9a683b64c","layer":8362,"height":0},{"id":"b401975590","layer":8361,"height":0},{"id":"b55ac96b9f","layer":8360,"height":0},{"id":"876f5e30cc","layer":8359,"height":0},{"id":"fe21d185bf","layer":8358,"height":0},{"id":"85544c5482","layer":8357,"height":0},{"id":"541d5b6bef","layer":8356,"height":0},{"id":"465ae61307","layer":8355,"height":0},{"id":"2a1a937568","layer":8354,"height":0},{"id":"a72ec860da","layer":8353,"height":0},{"id":"70aeb378b8","layer":8352,"height":0},{"id":"19a94dd013","layer":8351,"height":0},{"id":"fed70cfa01","layer":8350,"height":0},{"id":"7c82cf4ec0","layer":8349,"height":0},{"id":"f7545df8c4","layer":8348,"height":0},{"id":"e7f5d7617c","layer":8347,"height":0},{"id":"fb44bc175b","layer":8346,"height":0},{"id":"a60b61577a","layer":8345,"height":0},{"id":"12ac763a8c","layer":8344,"height":0},{"id":"8f8bfe1dfe","layer":8343,"height":0}],"abstain":["8394"]},"name":"proposalListener"}

**Comment by dshulyak** [comment]
rewards for this account https://explorer.spacemesh.io/accounts/sm1qqqqqq8k0p7d5rmvhl39kx5u6s7ghlpnrq6x54su8klj6/rewards 

i see that you are using same coinbase for two atxs, but this one definitely was rewarded

**Comment by HVNC1** [comment]
[spacemesh-log-7c8cef2b (2).zip](https://github.com/spacemeshos/smapp/files/12327463/spacemesh-log-7c8cef2b.2.zip)

**Comment by HVNC1** [comment]
0xe20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4 no rewards

**Comment by HVNC1** [comment]
0xd8a3b915ae120815af73dccdda7d093886cb3bb1135514c98bf6d564dcce9feb rawards its ok
same coinbase

**Comment by HVNC1** [comment]
> rewards for this account https://explorer.spacemesh.io/accounts/sm1qqqqqq8k0p7d5rmvhl39kx5u6s7ghlpnrq6x54su8klj6/rewards
> 
> i see that you are using same coinbase for two atxs, but this one definitely was rewarded

I tried to install the new version but it didn't help

**Comment by HVNC1** [comment]
https://github.com/spacemeshos/smapp/pull/1436
This version

**Comment by dshulyak** [comment]
> {"L":"INFO","T":"2023-08-12T13:45:01.973Z","N":"9787b.proposalListener","M":"new ballot","node_id":"9787b82b2f7495406f8642446928feee3e3e52a351c5a6706ca6ce9bbc13e81e","module":"proposalListener","requestId":"30f0b470-a864-47d6-b84b-d20d1d70a6fc","proposal_id":"**c9aef0a3d7**","ballot_id":"e140fdabc0","layer_id":8421,"ballot_id":"e140fdabc0","layer_id":8421,"epoch_id":2,"smesher":"**e20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4**","opinion hash":"61bf4985d7","base_ballot":"6f38be38ff","support":1,"against":0,"abstain":0,"atx_id":"1e224c0eb8","ref_ballot":"e3617f3a07","active_set_size":0,"beacon":"00000000","votes":{"base":"6f38be38ff","support":[{"id":"58005c624f","layer":8420,"height":0}],"against":[],"abstain":[]},"name":"proposalListener"}

> 2023-08-12T15:47:06.858+0200	INFO	fd68b.hare	consensus process terminated	{"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "hare", "protocol": "hr1_tickloop", "sessionId": "32d51efb-c6a6-4a1c-8ba0-78e877c38705", "event": true, "current_set": "d031d996ce,4228de3f47,54b9c4469f,8892738d6d,08cfaf9f2d,3845db0468,c9aef0a3d7,38feb76516,52fd73d3e3,7f3060f0dd,857fffe5b2,8a294912e1,084ee77ec0,1aae9ea4e0,201a66c18c,a36d093137,ba69c70157,**c9e2daae8f**,cdb497729a,e6ab3259f4,8e91827983,959d361217,9722514f77,8096ade9e7,8b8643f320,93b2bd0412,9b109701c4,0d5a28e2df,659632849c,7ef536a512,d1fa3d0eeb,f8b10fbb05,788709a244,7cef57095c,b0f0c808f8,a3b3382567,355c681af4,3b2e65c134,4e78b0f5b0", "current_round": 3, "layer_id": 8421, "notify_count": {"honest_count": 101, "num_honest": 95, "dishonest_count": 0, "num_dishonest": 0, "num_ke": 0, "ke_count": 0}, "set_size": 39, "name": "hare"}


you got rewards in layer 8421, just now. there must be something wrong with UI, i understand that parsing logs is not the most pleasent thing.

**Comment by HVNC1** [comment]
> > {"L":"INFO","T":"2023-08-12T13:45:01.973Z","N":"9787b.proposalListener","M":"новий бюлетень","node_id":" 9787b82b2f7495406f8642446928feee3e3e52a351c5a6706ca6ce9bbc13e81e","module":"proposalListener","requestId":"30f0b470-a864-47d6-b84b-d20d1d70a6fc"," offer_id":" c9aef0a3d7 ","ballot_id":"e140fdabc0","layer_id":8421 **,** " ballot_id":"e140fdabc0","layer_id":8421,"epoch_id":2,"smesher":" e20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4 ","хеш думки":"61 bf4985d7","base_ballot":" **6f38be38ff** ","підтримка":1,"проти":0,"утримався":0,"atx_id":"1e224c0eb8","ref_ballot":"e3617f3a07","active_set_size":0,"beacon":"00000000","votes":{" base":"6f38be38ff","support":[{"id":"58005c624f","layer":8420,"height":0}],"against":[],"abstain":[]}, "name":"proposalListener"}"abstain":[]},"name":"proposalListener"}"abstain":[]},"name":"proposalListener"}
> 
> > 2023-08-12T15:47:06.858+0200 INFO fd68b.hare Консенсусний процес припинено {"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "hare ", "протокол": "hr1_tickloop", "sessionId": "32d51efb- c6a6-4a1c-8ba0-78e877c38705", "event": true, "current_set": "d031d996ce,4228de3f47,54b9c4469f,8892738d6d,08cfaf9f2d,3845db0468,c9aef0a3d7,38feb765 16,52fd73d3e3,7f3060f0dd,857fffe5b2,8a294912e1,084ee77ec0,1aae9ea4e0,201a66c18c, a36d093137,ba69c70157, **c9e2daae8f**,cdb497729a,e6ab3259f4,8e91827983,959d361217,9722514f77,8096ade9e7,8b8643f320,93b2bd0412,9b109701c4,0d5a28e2df,659632849c, 7ef536a512,d1fa3d0eeb,f8b10fbb05,788709a244,7cef57095c,b0f0c808f8,a3b3382567,355c681af4,3b2e65c134,4e78b0f5b0", "current_round": 3, "layer_id": 8421, "notify_count": {"honest_count": 101, "num_honest": 95, "dishonest_count": 0, "num_dihonest": 0, "num_ke": 0, "ke_count": 0}, "set_size ": 39, "name": "заєць"}
> 
> щойно ви отримали нагороди в шарі 8421. Мабуть, щось не так з інтерфейсом користувача, я розумію, що розбір журналів — не найприємніша річ.

https://explorer.spacemesh.io/smeshers/0xe20905c6e85cd32f7a35e3a915c3e99aa6f19e978cf43b9e40e0efda9e9c26f4
not rewards

**Comment by HVNC1** [comment]
https://explorer.spacemesh.io/smeshers/0xd8a3b915ae120815af73dccdda7d093886cb3bb1135514c98bf6d564dcce9feb
 another node gets the rewards

**Comment by dshulyak** [comment]
@kacpersaw @brusherru please take a look. thats a ui problem

**Comment by diomark** [comment]
I have the same issue with half my nodes:( blocks where i'm supposdly eligible have passed but no rewards.

**Comment by YogurtDance** [comment]
Maybe same issue, I can see these logs `Published proposal. Rewards will be received, once proposal is included into the block.` from grpc `spacemesh.v1.AdminService.EventsStream` and my POST is eligibilities for these layer, but I didn't get any rewards since layer 8258.
https://explorer.spacemesh.io/accounts/sm1qqqqqqpsdqyw5cy84pkcfl0gm26yg7u7kjrznwg3ralvd/rewards
Is there anything wrong with my network/config or go-spacemesh or block network? What can I do?

![image](https://github.com/spacemeshos/smapp/assets/87231192/0e237a5f-3146-4cfb-9d1e-56fe90968caf)

**Comment by ndcc5** [comment]
"2023-08-12T15:10:00.973804300Z",
  "help": "Published proposal. Rewards will be received, once proposal is included into the block.",
  "proposal": {
    "layer": 8438,
    "proposal": "77XuAxyPlJYGftJ96Q2vVCNPX8Q="
  }
}

**But there's no reward.**
this is my log file
[log.csv](https://github.com/spacemeshos/smapp/files/12327962/log.csv)

**Comment by scj85** [comment]
I have the same issue. No reward for my node (256 GB).
https://explorer.spacemesh.io/smeshers/0xe2d279e52ded8a8b4f8d229e04b3e64767f7895e64c866bdeb9fdfb1154645a6

My activation:
https://explorer.spacemesh.io/atxs/0xeffc4139b67beb5d15460f4bfddaaa6eaf2c6ca7108a122a57e3aabf13e65bb6

I have already published 2 proposals (not all visible on the logs). I successfully registered this post data from this node before 24th July.

After that, I accidentally produced the second post data (1.75 TB) with the same SmecherID and ran both nodes (with the same SmecherID, but with different post data). I was keeping them online during the second PoET round and after that for a while. 

Could it be the reason that my node is not getting rewards? In the Explorer I can see only my first 256 GB node data. So all seems to be fine there. But no rewards 😦

Now I am keeping online only the first one (256 GB).
When I realized that they have the same SmecherID I just switched off the second duplicated one.

I also noticed that my internet upload speed was very weak like 0.3 Mbps. I fixed it now.

Here is my log:
[spacemesh-log-7c8cef2b-part1.zip](https://github.com/spacemeshos/smapp/files/12328301/spacemesh-log-7c8cef2b-part1.zip)
[spacemesh-log-7c8cef2b-part2.zip](https://github.com/spacemeshos/smapp/files/12328264/spacemesh-log-7c8cef2b-part2.zip)
[spacemesh-log-7c8cef2b-part3.zip](https://github.com/spacemeshos/smapp/files/12328312/spacemesh-log-7c8cef2b-part3.zip)
[spacemesh-log-7c8cef2b-part4.zip](https://github.com/spacemeshos/smapp/files/12328315/spacemesh-log-7c8cef2b-part4.zip)

Grpcurl output:
```
{
  "timestamp": "2023-08-12T07:14:51.302728300Z",
  "help": "Node computed randomness beacon, it will be used to determine eligibility to participate in the consensus.",
  "beacon": {
    "epoch": 2,
    "beacon": "4+M4ng=="
  }
}
{
  "timestamp": "2023-08-12T07:14:51.483982500Z",
  "help": "Node computed randomness beacon, it will be used to determine eligibility to participate in the consensus.",
  "beacon": {
    "epoch": 2,
    "beacon": "4+M4ng=="
  }
}
{
  "timestamp": "2023-08-12T07:15:01.844633500Z",
  "help": "Node started post data initialization. Note that init is noop if node restarted when init was ready.",
  "initStart": {
    "smesher": "4tJ55S3tiotPjSKeBLPmR2f3iV5kyGa965/fsRVGRaY=",
    "commitment": "nuv/Ajq7F8y3dcYC2q3o7XCPClDTFJpCgBGE9bdPKGU="
  }
}
{
  "timestamp": "2023-08-12T07:15:02.781422700Z",
  "help": "Node completed post data initialization.",
  "initComplete": {

  }
}
{
  "timestamp": "2023-08-12T07:15:02.809138600Z",
  "help": "Node needs to wait for poet to complete in publish epoch. Once completed, node fetches proof from poet and runs post on that proof. After that publish an ATX that will be eligible for rewards in target epoch.",
  "poetWaitProof": {
    "publish": 2,
    "target": 3,
    "wait": "737097.190861400s"
  }
}
{
  "timestamp": "2023-08-12T08:05:03.103431900Z",
  "help": "Computed eligibilities for the epoch. Rewards will be received after publishing proposals at specified layers. Total amount of rewards in SMH will be based on other participants in the layer.",
  "eligibilities": {
    "epoch": 2,
    "beacon": "4+M4ng==",
    "atx": "7/xBObZ7610VRg9L/dqqbq8sbKcQihIqV+OqvxPmW7Y=",
    "activeSetSize": 2368,
    "eligibilities": [
      {"layer": 11211,"count": 1},
      {"layer": 11218,"count": 1},
      {"layer": 11133,"count": 1},
      {"layer": 11439,"count": 1},
      {"layer": 8373,"count": 1},
      {"layer": 11408,"count": 1},
      {"layer": 10598,"count": 1},
      {"layer": 11944,"count": 1},
      {"layer": 11591,"count": 1},
      {"layer": 9920,"count": 1},
      {"layer": 11209,"count": 1},
      {"layer": 11422,"count": 1},
      {"layer": 8629,"count": 1},
      {"layer": 11554,"count": 1},
      {"layer": 10381,"count": 1},
      {"layer": 9297,"count": 1},
      {"layer": 8529,"count": 1},
      {"layer": 9765,"count": 1},
      {"layer": 9168,"count": 1},
      {"layer": 11314,"count": 1},
      {"layer": 8300,"count": 1},
      {"layer": 8840,"count": 1},
      {"layer": 11891,"count": 1},
      {"layer": 9307,"count": 1
      }
    ]
  }
}
{
  "timestamp": "2023-08-12T09:45:00.969431800Z",
  "help": "Published proposal. Rewards will be received, once proposal is included into the block.",
  "proposal": {
    "layer": 8373,
    "proposal": "qknRjqTHC62ShTJ3EOuRgLSoWos="
  }
}
```

**Comment by haibochu** [comment]
> I have the same issue. No reward for my node (256 GB). https://explorer.spacemesh.io/smeshers/0xe2d279e52ded8a8b4f8d229e04b3e64767f7895e64c866bdeb9fdfb1154645a6
> 
> I have already published 2 proposals (not all visible on the logs). I successfully registered this post data from this node before 24th July.
> 
> After that, I accidentally produced the second post data (1.75 TB) with the same SmecherID and ran both nodes (with the same SmecherID, but with different post data). I was keeping them online during the second PoET round and after that for a while.
> 
> Could it be the reason that my node is not getting rewards? In the Explorer I can see only my first 256 GB node data. So all seems to be fine there. But no rewards 😦
> 
> Now I am keeping online only the first one (256 GB). When I realized that they have the same SmecherID I just switched off the second duplicated one.
> 
> I also noticed that my internet upload speed was very weak like 0.3 Mbps. I fixed it now.
> 
> Here is my log: [spacemesh-log-7c8cef2b-part1.zip](https://github.com/spacemeshos/smapp/files/12328301/spacemesh-log-7c8cef2b-part1.zip) [spacemesh-log-7c8cef2b-part2.zip](https://github.com/spacemeshos/smapp/files/12328264/spacemesh-log-7c8cef2b-part2.zip) [spacemesh-log-7c8cef2b-part3.zip](https://github.com/spacemeshos/smapp/files/12328312/spacemesh-log-7c8cef2b-part3.zip) [spacemesh-log-7c8cef2b-part4.zip](https://github.com/spacemeshos/smapp/files/12328315/spacemesh-log-7c8cef2b-part4.zip)
> 
> Grpcurl output:
> 
> ```
> {
>   "timestamp": "2023-08-12T07:14:51.302728300Z",
>   "help": "Node computed randomness beacon, it will be used to determine eligibility to participate in the consensus.",
>   "beacon": {
>     "epoch": 2,
>     "beacon": "4+M4ng=="
>   }
> }
> {
>   "timestamp": "2023-08-12T07:14:51.483982500Z",
>   "help": "Node computed randomness beacon, it will be used to determine eligibility to participate in the consensus.",
>   "beacon": {
>     "epoch": 2,
>     "beacon": "4+M4ng=="
>   }
> }
> {
>   "timestamp": "2023-08-12T07:15:01.844633500Z",
>   "help": "Node started post data initialization. Note that init is noop if node restarted when init was ready.",
>   "initStart": {
>     "smesher": "4tJ55S3tiotPjSKeBLPmR2f3iV5kyGa965/fsRVGRaY=",
>     "commitment": "nuv/Ajq7F8y3dcYC2q3o7XCPClDTFJpCgBGE9bdPKGU="
>   }
> }
> {
>   "timestamp": "2023-08-12T07:15:02.781422700Z",
>   "help": "Node completed post data initialization.",
>   "initComplete": {
> 
>   }
> }
> {
>   "timestamp": "2023-08-12T07:15:02.809138600Z",
>   "help": "Node needs to wait for poet to complete in publish epoch. Once completed, node fetches proof from poet and runs post on that proof. After that publish an ATX that will be eligible for rewards in target epoch.",
>   "poetWaitProof": {
>     "publish": 2,
>     "target": 3,
>     "wait": "737097.190861400s"
>   }
> }
> {
>   "timestamp": "2023-08-12T08:05:03.103431900Z",
>   "help": "Computed eligibilities for the epoch. Rewards will be received after publishing proposals at specified layers. Total amount of rewards in SMH will be based on other participants in the layer.",
>   "eligibilities": {
>     "epoch": 2,
>     "beacon": "4+M4ng==",
>     "atx": "7/xBObZ7610VRg9L/dqqbq8sbKcQihIqV+OqvxPmW7Y=",
>     "activeSetSize": 2368,
>     "eligibilities": [
>       {"layer": 11211,"count": 1},
>       {"layer": 11218,"count": 1},
>       {"layer": 11133,"count": 1},
>       {"layer": 11439,"count": 1},
>       {"layer": 8373,"count": 1},
>       {"layer": 11408,"count": 1},
>       {"layer": 10598,"count": 1},
>       {"layer": 11944,"count": 1},
>       {"layer": 11591,"count": 1},
>       {"layer": 9920,"count": 1},
>       {"layer": 11209,"count": 1},
>       {"layer": 11422,"count": 1},
>       {"layer": 8629,"count": 1},
>       {"layer": 11554,"count": 1},
>       {"layer": 10381,"count": 1},
>       {"layer": 9297,"count": 1},
>       {"layer": 8529,"count": 1},
>       {"layer": 9765,"count": 1},
>       {"layer": 9168,"count": 1},
>       {"layer": 11314,"count": 1},
>       {"layer": 8300,"count": 1},
>       {"layer": 8840,"count": 1},
>       {"layer": 11891,"count": 1},
>       {"layer": 9307,"count": 1
>       }
>     ]
>   }
> }
> {
>   "timestamp": "2023-08-12T09:45:00.969431800Z",
>   "help": "Published proposal. Rewards will be received, once proposal is included into the block.",
>   "proposal": {
>     "layer": 8373,
>     "proposal": "qknRjqTHC62ShTJ3EOuRgLSoWos="
>   }
> }
> ```

#1440 
me too

**Comment by ndcc5** [comment]
![1691920376940](https://github.com/spacemeshos/smapp/assets/6286019/e70d0d76-9047-46ec-b20a-f7ffef0016c7)
![1691920418025](https://github.com/spacemeshos/smapp/assets/6286019/7b00dfc0-7683-4b59-9056-3abb41b67e5e)
I selected 8661 layers when the number appeared in my log section, there were developers to see what was wrong.
[8661.txt](https://github.com/spacemeshos/smapp/files/12329261/8661.txt)

**Comment by HVNC1** [comment]
As far as I understand, those who created several files with the same hash ID do not receive rewards
I get rewards, but because of a visual bug in the explorer and the program, I thought I wasn't getting them

**Comment by scj85** [comment]
> As far as I understand, those who created several files with the same hash ID do not receive rewards I get rewards, but because of a visual bug in the explorer and the program, I thought I wasn't getting them

I think so, but my second post data are not visible in the explorer. Seems to be they have not been published. I can see there is only my first generated post data. 
But would be great to verify it somehow. If that is the real issue.

**Comment by GAMBADA1939** [comment]
No rewards, please check:
Smapp version: 1.0.14
OS: Ubuntu 22.4.3

smesher id : 0x83f0358233f7348bfa45b41fd8a5288d1d42b1ec74e805b2c591bd4a76978bd6

Log file:
[spacemesh-log-7c8cef2b.zip](https://github.com/spacemeshos/smapp/files/12330163/spacemesh-log-7c8cef2b.zip)

**Comment by scj85** [comment]
@HVNC1 / @ndcc5 we will not get any rewards for these nodes, unfortunately.
See this:
https://github.com/spacemeshos/go-spacemesh/issues/4832#issuecomment-1676426214

We all have the same information in your logs.

**Comment by HVNC1** [comment]
> @HVNC1/@ndcc5На жаль, ми не отримаємо винагород за ці вузли. Дивіться це: [spacemeshos/go-spacemesh#4832 (коментар)](https://github.com/spacemeshos/go-spacemesh/issues/4832#issuecomment-1676426214)
> 
> Усі ми маємо однакову інформацію у ваших журналах.

if you look at the layers, my node will receive rewards from 1 and 2 nodes. although in the guide one of them is 0 coins. check yourself if you have different hash IDs on the nodes

**Comment by scj85** [comment]
> > @HVNC1/@ndcc5На жаль, ми не отримаємо винагород за ці вузли. Дивіться це: [spacemeshos/go-spacemesh#4832 (коментар)](https://github.com/spacemeshos/go-spacemesh/issues/4832#issuecomment-1676426214)
> > Усі ми маємо однакову інформацію у ваших журналах.
> 
> if you look at the layers, my node will receive rewards from 1 and 2 nodes. although in the guide one of them is 0 coins. check yourself if you have different hash IDs on the nodes

Both node IDs are the same :( 
They only have different NumUnits, Nonce and NonceValue but it doesn't matter.

**Comment by GAMBADA1939** [comment]
> No rewards, please check: Smapp version: 1.0.14 OS: Ubuntu 22.4.3
> 
> smesher id : 0x83f0358233f7348bfa45b41fd8a5288d1d42b1ec74e805b2c591bd4a76978bd6
> 
> Log file: [spacemesh-log-7c8cef2b.zip](https://github.com/spacemeshos/smapp/files/12330163/spacemesh-log-7c8cef2b.zip)

Do you need more information?

**Comment by GAMBADA1939** [comment]
> > No rewards, please check: Smapp version: 1.0.14 OS: Ubuntu 22.4.3
> > smesher id : 0x83f0358233f7348bfa45b41fd8a5288d1d42b1ec74e805b2c591bd4a76978bd6
> > Log file: [spacemesh-log-7c8cef2b.zip](https://github.com/spacemeshos/smapp/files/12330163/spacemesh-log-7c8cef2b.zip)
> 
> Do you need more information?

I use now the new version 1.0.16

**Comment by pigmej** [comment]
@diomark a few clarifications. Did you get the rewards? Best is to check to go to your account and check rewards: https://explorer.spacemesh.io/accounts/XXXXXXXX/rewards

Grouping by one smesher id and multiple different coinbases does not work correctly atm because of: https://github.com/spacemeshos/go-spacemesh/issues/4529


Could you please double check?

**Comment by HVNC1** [comment]
can this topic be closed? because it seems like I'm getting rewards but the explorer doesn't display them correctly when I search for smesher id
