### ISSUE TITLE
two nodes have no rewards

### ISSUE THREAD

**Issue by fomosats** [spacemeshos/smapp#1440]

**Comment by HVNC1** [comment]
same

**Comment by HVNC1** [comment]
https://github.com/spacemeshos/smapp/issues/1438

**Comment by dshulyak** [comment]
> {"L":"INFO","T":"2023-08-11T09:47:05.246Z","N":"5b8c8.malfeasance","M":"new malfeasance proof","node_id":"5b8c84d0c38f1e8aa76c5aeed199e42a8a93c8d7dd72f5b4ee3a24d50791ec1c","module":"malfeasance","requestId":"c7cc6766-cb3c-4ab5-aa52-e4f9eadcb970","smesher":"**7c88a798787fc323da3c2148d98ec8f4e7ace8c77ea1b37b1363582f3a19c5b7**","proof":{"generated_layer":8085,"type":"hare equivocation","msgs":{"first":{"layer":8085,"round":3,"msgHash":"0x12b61073f5553633966d8d9e429636e9e089ce9ce4e56ba4ae146dd30617f606"},"second":{"layer":8085,"round":3,"msgHash":"0x83ad4746a5a7f6912d03e6084d77adeca579f5ddc1eec221684c06cb7dd5470f"}},"received":"0001-01-01T00:00:00.000Z"},"hare eligibility":{"layer":8085,"round":3,"smesher":"7c88a798787fc323da3c2148d98ec8f4e7ace8c77ea1b37b1363582f3a19c5b7","count":1,"proof":"105f15de763bef919d93b1e1512d045616d6ecc0c05b35bfc1017d859ae294afffed63f54bc2a1b99d99d32fe3782e020f62a8118d193133c5e0a09ff1d98fc7282c9869a43f87b392f0704fa2ec2a0c"},"name":"malfeasance"}

> {"L":"INFO","T":"2023-08-08T15:39:00.233Z","N":"5b8c8.malfeasance","M":"new malfeasance proof","node_id":"5b8c84d0c38f1e8aa76c5aeed199e42a8a93c8d7dd72f5b4ee3a24d50791ec1c","module":"malfeasance","sessionId":"25ef7949-8091-4951-98a1-8789398f8488","smesher":"**309502ba1bbca4de616ae0b2de8d2a85050c6252881c454241237754d7ab2fdf**","proof":{"generated_layer":4032,"type":"multiple atxs","msgs":{"first":{"epoch":1,"hash":"069e57c78c"},"second":{"epoch":1,"hash":"fff7794603"}},"received":"0001-01-01T00:00:00.000Z"},"name":"malfeasance"}

did you run multiple processes with the same private key?

**Comment by fomosats** [comment]
> > 
> 
> Yes, one of them has been closed now. How do I need to fix it



> > {"L":"INFO","T":"2023-08-11T09:47:05.246Z","N":"5b8c8.malfeasance","M":"new malfeasance proof","node_id":"5b8c84d0c38f1e8aa76c5aeed199e42a8a93c8d7dd72f5b4ee3a24d50791ec1c","module":"malfeasance","requestId":"c7cc6766-cb3c-4ab5-aa52-e4f9eadcb970","smesher":"**7c88a798787fc323da3c2148d98ec8f4e7ace8c77ea1b37b1363582f3a19c5b7**","proof":{"generated_layer":8085,"type":"hare equivocation","msgs":{"first":{"layer":8085,"round":3,"msgHash":"0x12b61073f5553633966d8d9e429636e9e089ce9ce4e56ba4ae146dd30617f606"},"second":{"layer":8085,"round":3,"msgHash":"0x83ad4746a5a7f6912d03e6084d77adeca579f5ddc1eec221684c06cb7dd5470f"}},"received":"0001-01-01T00:00:00.000Z"},"hare eligibility":{"layer":8085,"round":3,"smesher":"7c88a798787fc323da3c2148d98ec8f4e7ace8c77ea1b37b1363582f3a19c5b7","count":1,"proof":"105f15de763bef919d93b1e1512d045616d6ecc0c05b35bfc1017d859ae294afffed63f54bc2a1b99d99d32fe3782e020f62a8118d193133c5e0a09ff1d98fc7282c9869a43f87b392f0704fa2ec2a0c"},"name":"malfeasance"}
> 
> > {"L":"INFO","T":"2023-08-08T15:39:00.233Z","N":"5b8c8.malfeasance","M":"new malfeasance proof","node_id":"5b8c84d0c38f1e8aa76c5aeed199e42a8a93c8d7dd72f5b4ee3a24d50791ec1c","module":"malfeasance","sessionId":"25ef7949-8091-4951-98a1-8789398f8488","smesher":"**309502ba1bbca4de616ae0b2de8d2a85050c6252881c454241237754d7ab2fdf**","proof":{"generated_layer":4032,"type":"multiple atxs","msgs":{"first":{"epoch":1,"hash":"069e57c78c"},"second":{"epoch":1,"hash":"fff7794603"}},"received":"0001-01-01T00:00:00.000Z"},"name":"malfeasance"}
> 
> did you run multiple processes with the same private key?



Yes, one of them has been closed now. How do I need to fix it @dshulyak

**Comment by fomosats** [comment]
<img width="1287" alt="image" src="https://github.com/spacemeshos/smapp/assets/5418173/c932316f-ea79-4c22-9f9b-065eb35c4f1c">
My node 1 has always been online, but why does atxs display information from a day ago?

**Comment by HVNC1** [comment]
As far as I understand, those who created several files with the same hash ID do not receive rewards
I get rewards, but because of a visual bug in the explorer and the program, I thought I wasn't getting them

**Comment by ndcc5** [comment]
> 

It makes no sense to permanently disallow rewards just because two identical nodes are running. Sometimes I open a SMAPP, and then I want to test the CLI running node, and the SMAPP node forgot to close. You can run the same node at the same time without giving rewards, and restore rewards when running the node alone.
