### ISSUE TITLE
NO REWARDS : "not voting on proposal from malicious identity"

### ISSUE THREAD

**Issue by batman69r1** [spacemeshos/smapp#1442]
### Environment

* Smapp version: 1.0.14 | develop
* Node version: v1.0.15
* OS: Windows 10
 
Getting many errors,

"not voting on proposal from malicious identity"

I have multiple nodes which I installed fresh but imported my wallet key on each one so the smeshing coinbase was the same on all.

can't seem to get anymore then 15 peers?

don't really know where to start with this?
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12329125/spacemesh-log-7c8cef2b.txt)

**Comment by HVNC1** [comment]
what is your file size of everyone participating in this epic and what is the total number of rewards?

**Comment by batman69r1** [comment]
> what is your file size of everyone participating in this epic and what is the total number of rewards?

yeah I think this is just a normal warning everyone gets, just haven't seen any rewards and I have 4VM's with 1tb each, that were all registered. for epoch 2 and my coinbase can't be seen in explorer and I haven't seen any rewards.  I've also checked all my node ID and keys they are all different.

**Comment by scj85** [comment]
Are you sure that all of your nodes have different SmesherID? 
I have freshly installed them too, but they still had the same SmasherID. So I generated multiple post data using the same id. :(

**Comment by scj85** [comment]
> > what is your file size of everyone participating in this epic and what is the total number of rewards?
> 
> yeah I think this is just a normal warning everyone gets, just haven't seen any rewards and I have 4VM's with 1tb each, that were all registered. for epoch 2 and my coinbase can't be seen in explorer and I haven't seen any rewards. I've also checked all my node ID and keys they are all different.

Are you sure that all of your nodes have different SmesherID?
I have freshly installed them too, but they still had the same SmasherID. So I generated multiple post data using the same id. :(

**Comment by batman69r1** [comment]
> > > what is your file size of everyone participating in this epic and what is the total number of rewards?
> > 
> > 
> > yeah I think this is just a normal warning everyone gets, just haven't seen any rewards and I have 4VM's with 1tb each, that were all registered. for epoch 2 and my coinbase can't be seen in explorer and I haven't seen any rewards. I've also checked all my node ID and keys they are all different.
> 
> Are you sure that all of your nodes have different SmesherID? I have freshly installed them too, but they still had the same SmasherID. So I generated multiple post data using the same id. :(

mmmmm the latest error i get is "ballot already reported beacon"  I've moved mine to go_smesh but when i had them in smapp, I checked them. it seemed fine, sorry to hear about your trouble. its been a real headache my me too.

**Comment by batman69r1** [comment]
can someone confirm that if you create nodes with the same mnemonic seed phase, that the nodes will conflict?

**Comment by scj85** [comment]
@batman69r1 Possible no any rewards for these nodes.
https://github.com/spacemeshos/go-spacemesh/issues/4832#issuecomment-1676426214
