### ISSUE TITLE
Error Message When Trying to Stop Smeshing During Syncing

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1463]
### Environment

- Smapp version: latest

### Describe the Bug

Currently, there is an issue when the smeshing process or node syncing is ongoing, and the user attempts to stop smeshing. On the Smeshing screen, clicking the "Stop Smeshing" button displays the following message:

![Screenshot](https://github.com/spacemeshos/smapp/assets/54288612/559e3221-88f1-468c-bd63-4143cf2cfe5b)

### Steps to Reproduce

This behavior is not consistent and depends on the node's status.

1. Open Smapp with smeshing enabled.
2. Quickly navigate to the Smeshing screen.
3. Click "Stop Smeshing".

### Expected Behavior

All scenarios where stopping smeshing is not possible should be appropriately handled. If unfeasible, the "Stop Smeshing" button should not be displayed. Alternatively, if an error message appears, it should clarify that this is an expected behavior and encourage the user to try again later.

### Actual Behavior

After clicking the button, an error modal is shown. The user closes it and can attempt the action again. The outcome might still lead to an error message (depending on the situation).

**Comment by brusherru** [comment]
No, I'm sure that's not the point. In fact, this is a bug in the Smap.
The error indicates that the handler for the event is not registered in the main process.

It means that `SmesherManager.subscribeIPCEvents` was not called for some reason OR it was unsubscribed and not subscribed again, or something like this (mb some race condition). However, this function should be called every time we spawn managers...

also `NodeManager.startGRPCClient` calls `SmesherManager.subscribeIPC` — mb this is an excessive call (or mb the opposite and we need to wait for it) — research needed

**Comment by monikasmolarek** [comment]
very easily reproducible along with the #1480
