### ISSUE TITLE
Feature Request: Automatic Reconnection for Network Page

### ISSUE THREAD

**Issue by summer1874** [spacemeshos/smapp#1465]
### Rationale

The current network page occasionally experiences connection disruptions due to network issues. It would be beneficial to incorporate an automatic reconnection feature within the network page to mitigate these intermittent disconnections. This enhancement would relieve users from the need to constantly monitor their computers, thus significantly aiding in the seamless operation of the project.

### Prerequisites

None.

### User story

A typical use case for this feature would involve:

- [ ] User opens the network page
- [ ] User encounters a network disconnection
- [ ] User benefits from the automatic reconnection feature

### Acceptance criteria

For this feature to be considered implemented, the following criteria should be met:

- [ ] The network page can automatically reconnect when a disconnection is detected
- [ ] The automatic reconnection does not disrupt the user's workflow
- [ ] The feature can be enabled or disabled through settings

### Out of scope

The following functionalities are not within the scope of this issue:

- Implementation of additional network diagnostic tools
- Addressing underlying network connectivity issues unrelated to automatic reconnection

### How to implement

One possible implementation approach could involve monitoring the network connection status in real-time. When a disconnection is detected, the page could trigger an automatic reconnection attempt. This could be achieved by implementing a timeout mechanism to periodically check the connection status and initiate reconnection if necessary.

### How to test

To test the implemented feature:

1. Simulate a network disconnection while on the network page.

**Comment by monikasmolarek** [comment]
fixed in #1612
