### ISSUE TITLE
Persisting error modal after wrong file uploaded as wallet

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1477]
### Environment

* Smapp version: any
* Node version: any
* OS: any

### Describe the bug

If we try to open a wallet from a file but choose the incorrect file - any non-empty JSON, smapp will accept it and try to proceed. Of course will not be able to parse it, so we can retry to load the correct file, but once we log out, we get the error modal that persists even after smapp restart. Sometimes we get this error immediately. Only unlinking the wrong file helps to get smapp usable again. 

### Steps to reproduce

1.  Open Smapp
2.  Try to recover wallet from file
3.  Pick any non-empty JSON file
4. try lo log in, wait or try to load the correct file, if still no modal, just log out. 
5. try to restart smapp

### Expected behavior

smapp should drop the file it could not parse (immediately or after app restart), we should be able to use smapp without restraints

### Actual behavior

error modal persists even after restart

https://github.com/spacemeshos/smapp/assets/89876259/81efac7f-5bc0-481a-8665-fec079a719e1

### Logs

[app-log.1.1.1.txt](https://github.com/spacemeshos/smapp/files/12457677/app-log.1.1.1.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12457678/spacemesh-log-7c8cef2b.txt)

**Comment by brusherru** [comment]
### How to fix
In case we have an invalid wallet file (or invalid JSON) in the list of wallet files — let's display a popup message with a dismiss button saying: "Wallet file /path/to/wallet.json is invalid. Please verify it and import the wallet file once again."
And such wallet file should be automatically omitted from the list of wallet files.
