### ISSUE TITLE
GUI gets stuck after update/reinstall

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1480]
### Environment

* Smapp version: 1.1.2
* Node version: v1.1.2
* OS: any

### Describe the bug

The sync progress (probably also all other API related info on rewards/txs etc.) gets frozen / stuck. Smapp does not reflect the changes even though the node is up and seems healthy. 

### Steps to reproduce

1.  Sync smapp to 100%
2.  Keep the node-data dir/contents
3.  install the latest Smapp and use the above mentioned node-data 
4. try to sync/ use smapp

### Expected behavior

We should be able to use smapp with no latency/lags/GUI refresh issues after any update or reinstallation

### Actual behavior

Syncing from scratch, in a clear environment seems to work fine.
Using existing node-data makes the GUI get stuck, refresh is possible only by smapp restart, but it's still stuck. 

![ZBHlkn8iQs](https://github.com/spacemeshos/smapp/assets/89876259/f2a0d1a6-eb29-4b3d-b6ce-e11de12dbca3)

### Logs

[app-log.1.1.2-pr.1472.txt](https://github.com/spacemeshos/smapp/files/12469704/app-log.1.1.2-pr.1472.txt)

**Comment by centny** [comment]
+1

**Comment by maparr** [comment]
will be closing after proper testing new go-sm release.
