### ISSUE TITLE
New nodes cannot mining.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1486]
### Environment

* Smapp version: 1.0.12 | develop
* OS: Ubuntu 22 | MacOS

### Describe the bug

New nodes cannot mining.

### Steps to reproduce

1.  Comlete PoS data.
2.  Just wait round finish time.

### Expected behavior

New nodes can mining completely.

### Actual behavior

1. Initially, the following screen appeared.
![2023-09-04_8 30 28](https://github.com/spacemeshos/smapp/assets/2483747/5e35d41d-87f3-4b69-951d-79c2a7644638)
"Waining for PoET registration window in 8hours" => This is 1 hour before finish round.

2. After one hour before the end of the round, the following screen appeared.
![2023-09-04_8 30 28](https://github.com/spacemeshos/smapp/assets/2483747/d88608fc-8f01-4449-8c82-d9c68599b6a5)

### Logs
[spacemesh-log-7c8cef2b.txt.zip](https://github.com/spacemeshos/smapp/files/12511158/spacemesh-log-7c8cef2b.txt.zip)

**Comment by hryksbt** [comment]
In fact, we have 15 minutes to complete the current round, but the nodes ID does not appear on the following site: https://www.spacemeshcalculator.com/ranking

**Comment by brusherru** [comment]
@hryksbt it seems to me that you need some patience and to read how the protocol works.

In short, you need to wait for the registration window, then your Node will generate the PoS proof, and then in the next epoch you will be eligible for rewards, but to have them you still need to run the node to publish proposals at specific layers (you'll have a list of layers once you'll be eligible).

So please provide more details (by the way, the second screenshot is the same) or close the issue.

p.s.
I will close the issue in a couple of days if there will be no more details.

**Comment by hryksbt** [comment]
@brusherru Thank you for your reply.
Does this mean that there will be an additional 14 days of registration window from the end of the ROUND after the PoS data has been created?
Am I right in understanding that the node I sent in the screenshot will get the reward from epoch 5?
