### ISSUE TITLE
Reward not update 1.1.7

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1498]
### Environment

* Smapp version: 1.1.7
* OS: Windows 10 | macOS High Sierra (12.2) | Ubuntu 22
### Describe the bug

In 1.1.2, the rewards earned were properly updated and displayed. However, in 1.1.7, they are not displayed.

### Steps to reproduce

1.  Update from 1.1.2 to 1.1.7
2.  Start Smapp

### Expected behavior

The latest rewards must be properly displayed.

### Actual behavior

It only shows up halfway through.

1.1.7
![スクリーンショット 2023-09-09 9 31 00](https://github.com/spacemeshos/smapp/assets/2483747/bcc5ecf0-e848-45d5-9cb6-90b541c50e05)

1.1.2
![スクリーンショット 2023-09-09 9 31 08](https://github.com/spacemeshos/smapp/assets/2483747/3d72a168-43c1-4235-8fb3-3b1d95744387)

### Logs

[spacemesh-log-7c8cef2b.txt.zip](https://github.com/spacemeshos/smapp/files/12564286/spacemesh-log-7c8cef2b.txt.zip)

**Comment by hryksbt** [comment]
No one check this issue?

**Comment by wessyde** [comment]
I got same issue.

**Comment by brusherru** [comment]
Should be fixed in release v1.1.9
If not — please open a new issue and attach logs.

**Comment by hryksbt** [comment]
I saw that was fixed in 1.1.9. Good job!
