### ISSUE TITLE
Clean up Smeshing setup panel.

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1502]
## Environment

- **Smapp version:** Latest
- **Node version:** Latest
- **OS:** Any

## Bug Description

We have an old, unused flow that needs to be cleaned up. This outdated flow is no longer in use and is causing confusion for users.

![Screenshot](https://github.com/spacemeshos/smapp/assets/89876259/3ea2ef8a-8752-4905-9652-796859395309)

## Steps to Reproduce

1. Open the app.
2. Go to the Request on the Wallet screen.
3. Click "Set up Smeshing."
4. Observe the screen and the left panel.

## Expected Behavior

The left panel should be hidden, and the codebase should be cleaned up. This applies to both the Smeshing screen and the Set up Smeshing flow.

## Actual Behavior

The left panel is still visible.

## How to Fix

Refactor the codebase and remove the left panel.

**Comment by brusherru** [comment]
It is also related to https://github.com/spacemeshos/smapp/issues/1461 ;)
