### ISSUE TITLE
Announce newer updates

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#1515]
### Describe the bug

Right now, if the user is running version X and version X+1 is released, this will be displayed along with an UPGRADE link. However if version X+2 is subsequently released before the user has updated X -> X+1, this will not be displayed. In this case the user is forced to update twice.

Can we continue to poll for new updates and display the most recent one?

**Comment by maparr** [comment]
based on the investigation, the working cases are:
x+1, x+2, x+3 etc.

Conclusion: The upgrade app feature working as expected.
