### ISSUE TITLE
AppImage, selection gets stuck(?)  [not 100% sure case]

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp#1562]
### Environment

* Smapp version: any (?)
* Node version: any (?)
* OS: Ubuntu 22.04

### Describe the bug

While testing one of the PR on Ubuntu 22.04, Appimage, I was clicking here and there, switching accounts and screens, after some time one of the clicks got stuck and I did not "unclick" as if the mouse button was not released. I couldn’t do anything to cancel this selection. The CPU/RAM usage wasn’t too high, it could not cause any issues with the GUI stuckness.

Why I'm not sure about this bug:
I could reproduce it multiple times, but now I can no longer catch it. 
I encountered it on the VM (Oracle VirtualBox, not the best in terms of the computational resources access).
I could not do anything about it, only restarting VM helped.

### Steps to reproduce

1.  Open Smapp (AppImage) in standalone mode
2.  set up smashing, wait for the rewards
3. spawn the account
4. add an additional account and send some SMH to it
5. click here and there- tx log, contacts, settings, whatever
6. check the mouse movement, if anything gets selected, and if you can still activate input fields, click the buttons. 

### Expected behavior

no issues with using smapp intensively. 

### Actual behavior

https://github.com/spacemeshos/smapp/assets/89876259/86171fec-4005-4ff0-b49d-bb6cc7220e13

### Logs

nothing in logs

### How to fix 

as Kirill explained : 

We need to specify user-select CSS properties, and probably we can specify it on “top” level.
Like disabling it for any elements, and then turning it on only for Address / Inputs / and some specific fields

**Comment by maparr** [comment]
@monikasmolarek I think this case was resolved today, by the @brusherru fix for the transaction screen. I think u can check the current develop or the PR build and it will be resolved

**Comment by monikasmolarek** [comment]
Correct, I couldn’t reproduce. I will open another issue if it comes back anytime in the future
