### ISSUE TITLE
Sing message not working correclty

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#1583]
### Environment

* Smapp version: develop
* Node version: latest
* OS: Windows / Linux / MacOS
### Describe the bug

<img width="873" alt="Screenshot 2023-11-16 at 00 37 50" src="https://github.com/spacemeshos/smapp/assets/54288612/958d8b56-2e2f-49c2-aae9-b10d96aedf4d">
<img width="1001" alt="Screenshot 2023-11-16 at 00 38 05" src="https://github.com/spacemeshos/smapp/assets/54288612/f3fd25c3-8f47-4815-939f-975cb2f2dec9">
<img width="529" alt="Screenshot 2023-11-16 at 00 44 40" src="https://github.com/spacemeshos/smapp/assets/54288612/da8216af-7aa2-4908-adde-a8974e7b3daf">

we have 3 issues in the same area of sign message feature

1. During the node compacting DB state, we cannot use this feature and have an issue as on the first screenshot 
2. Magically only for view-only-wallet with transactions, we have an issue with sing message 
3. it is working , but the result is undefined

### Steps to reproduce

First case:
1.  Open smapp
2. Node should be in Compacting Mode status
3.  Go to the Wallet screen
4.  Try sign a message 
5. See an issue in develop mode

```
Error occurred in handler for 'W_M_SIGN_MESSAGE': TypeError: Cannot read properties of undefined (reading 'secretKey')
    at call (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:105:51)
    at tryCatch (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)
    at Generator._invoke (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)
    at Generator.next (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)

```

Second case:
1.  Open smapp
2. Select view only wallet
3. Check the node is syncing or synced
4.  Go to the Wallet screen
5.  Try sign a message 
6. See an issue in develop mode

```
Error occurred in handler for 'W_M_SIGN_MESSAGE': Error: error:0c0000a2:ASN.1 encoding routines:OPENSSL_internal:NOT_ENOUGH_DATA
    at Object.createPrivateKey (node:internal/crypto/keys:632:12)
    at sign (/Users/max/WP/sm/smapp/desktop/ed25519.ts:9:21)
    at call (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:104:15)
    at tryCatch (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)
    at Generator._invoke (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)
    at Generator.next (/Users/max/WP/sm/smapp/desktop/WalletManager.ts:2:1)
```

### Expected behavior

Sing message feature should work 

<img width="582" alt="Screenshot 2023-11-16 at 00 48 34" src="https://github.com/spacemeshos/smapp/assets/54288612/7c7c3c38-e7eb-4de2-b953-ddb15e91dcb3">

### Actual behavior

Not working in different scenarios

**Comment by maparr** [comment]
Expected to have an issue for our view-only wallets.

**Comment by brusherru** [comment]
View-only accounts are not an official thing: common users cannot add view-only accounts now.
So if we have such an issue it should sound like "add possibility to add view-only account easily" with acceptance criteria that the "sign message" button should be disabled (or hidden).
