### ISSUE TITLE
Sign windows installer

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#162]
Using Spacemesh EV code signing cert

**Comment by avive** [comment]
@IlyaVi Is this done?

**Comment by avive** [comment]
We need an EV cert to sign Smapp installer. We need to do some research about EV certs and CI before purchasing from a vendor. Specifically, which vendor's EV cert supports CI? This is an issue because EV certs typically require a Ubikey device to store private keys. 

- List of Microsoft endorsed EV certs vendors: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate
- Info about signing for windows in CI: 
https://github.com/marketplace/actions/authenticode-cloud-signer

**Comment by avive** [comment]
We have an EV cert from ssl.com - so the task now is to integrate their signing api into Smapp releases CI.

**Comment by brusherru** [comment]
After the research I have such a plan:
1. First job (matrix): Build and pack binaries for all platforms. Store them in the GHA artifacts.
2. Second job (depends on first):
   - download CodeSignTool from ssl.com (win: https://www.ssl.com/download/29773/ or linux/macos: https://www.ssl.com/download/29764/ ). It requires Java 11, but all vEnv images contain it, so we don't have to install it manually, just switch to it. BTW, we'll cache it ;)
   - download artifacts
   - sign it using CloudSignTool: `./CodeSignTool.sh sign -username={{ secrets.EV_USERNAME }} -password={{ secrets.EV_PASSWORD }} -input_file_path=../artifacts/spacemesh.exe -output_dir_path=../signed -totp_secret={{ secrets.EV_TOTP_SECRET }}`
   - upload artifacts to GCS and make a release draft

Note, that `CodeSignTool` works fine on any platform even it signs a binary for a different platform (I sign windows installer on Mac and it works as expected on Windows). So we can run the second job on the fastest and more stable platform, such as `ubuntu-latest`.

Btw, this tool does not send whole files via the internet, just transferring hashes and signatures. And then it signs the file with the received signature.

And as a result, we don't have to store certificates and keys somewhere (E.G. GCS / GKMS), but we'll store few things in the GHA secrets:
- username
- password
- TOTP secret (it is needed to avoid manually typing OTP on each release by someone with access and installed Authy)

--
What do you think? Is it good enough?

**Comment by avive** [comment]
Generally sounds like a decent plan. 
Two questions:
1. Regarding first job - do you mean use existing build flow or a new one? I think we should not change the current way installers are built for now.
2. Did you look into how we sign for macOS? It might be worth to have a look since we do something similar in CI for this platform. e.g. using cloud signing.

**Comment by brusherru** [comment]
@avive 

> 1. Regarding first job - do you mean use the existing build flow or a new one? 

The existing one, but it seems broken. So I just need to fix it a bit (copy some changes from PR-build workflow).

> 2. Did you look into how we sign for macOS?

Yep, and we did it within the package script using `electron-notarize`. But yesterday an idea came to me, to put this part of the code in a separate script. And sign the build for macOS at the same stage as the windows installer. It makes us possible to get rid of `DONT_SIGN_APP` env variable, and even do not try to sign App on dev builds (until we really want to do it and explicitly provide `APPLE_ID` and `APPLE_PASSWORD` env variables), and also we can get rid of `dotenv` package with any `.env` files (modal side-effects are evil). However, it is out of scope, and this idea probably needs more investigation, so I can try to do it after the main thing will be implemented.
I'll be glad to hear your thoughts about that.

--
So, as there are no objections, then I proceed to the implementation :)

**Comment by avive** [comment]
sounds good to me.

**Comment by brusherru** [comment]
@avive, what program name we should provide?

It will be visible here (when run installer and choose option "for all users"):
![image](https://user-images.githubusercontent.com/1897530/128427550-53db4e0d-bcd9-4b30-99f9-546cab5e6f48.png)

It defaults to the `description` field from `package.json` (currently "Spacemesh reference full p2p node, smesher and wallet"), so we can change it here (I'd prefer this option) ~~or overlap using the `-program_name` argument of `CodeSignTool`~~ (UPD: it does not work properly with spaces in the argument even it escaped or enquoted).
I think that "Spacemesh App" or "Spacemesh: Wallet & Smesher" will be better.
Please, choose one of them or propose your option.

**Comment by avive** [comment]
It should be `Spacemesh App`
