### ISSUE TITLE
!! Emergency !! Smapp versions newer than 1.2.7 are unstable on Ubuntu

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1623]
### Environment

* Smapp version: 1.2.14 , 1.2.13, 1.2.12, 1.2.11, 1.2.10, 1.2.9
* OS: Ubuntu 20.04

### Describe the bug

Newer than 1.2.7 are unstable on Ubuntu.
OS hang-up = 1.2.14
SQLite error = 1.2.12(This is occurred Windows 10 too)

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Install 1.2.14 , 1.2.12, 1.2.11, 1.2.9 Smapp.
2. Wait to green lamp.
3. When yellow lamp to green lamp about "SMESHING", this is happen.

### Expected behavior

Just work fine.

### Actual behavior

Newer than 1.2.7 are unstable on Ubuntu.
OS hang-up = 1.2.14
SQLite error = 1.2.12(This is iccurred Windows 10 too)

### Logs

This is 1.2.14 case.
[Uploading spacemesh-log-7c8cef2b.txt.
[syslog.zip](https://github.com/spacemeshos/smapp/files/13758083/syslog.zip)
[spacemesh-log-7c8cef2b 2.txt.zip](https://github.com/spacemeshos/smapp/files/13758084/spacemesh-log-7c8cef2b.2.txt.zip)
zip…]()

### How to fix 

If I downgrade to 1.2.7, this is work fine.
So all newer than 1.2.7 version has problem for Ubuntu Smapp.

I strongly wish to fix this until next round because of this announcement https://discord.com/channels/623195163510046732/691258865861394432/1187731532706754645

**Comment by pigmej** [comment]
It's not valid anymore.
