### ISSUE TITLE
Stuck on booting screen

### ISSUE THREAD

**Issue by Lucas749** [spacemeshos/smapp#1624]
### Environment

* Smapp version: 1.2.14
* OS: Windows 10

### Describe the bug

Application is stuck on the starting screen since it last crashed due to my hard drive running out of memory when saving log files. Restarted the application multiple times, tried to let it run for two days, and updated the client. However, it's still stuck on starting the node.

### Steps to reproduce

(Potentially optional: let Spacemesh crash when writing logs due to running out of memory on the hard drive and deleting the log file)
1.  Open Spacemesh app
2.  Log in

### Expected behavior

Spacemesh app and node should start.

### Actual behavior

Node does not start.

![image](https://github.com/spacemeshos/smapp/assets/48569945/3f708f78-d10c-4f44-b21f-39d82fd1d72b)

**Comment by monikasmolarek** [comment]
it duplicates the #1631
