### ISSUE TITLE
Not letting me download software

### ISSUE THREAD

**Issue by dar2187** [spacemeshos/smapp#1627]
Hi, i tried to download this software in D drive but keep giving me error that close spacemesh in the background. I have plenty space in D drive but don't understand why is this error?
![WhatsApp Image 2023-12-31 at 19 48 46_a9b92649](https://github.com/spacemeshos/post-rs/assets/155326344/4bbc6604-4e39-4cba-aaf6-a5f389eda83d)

**Comment by brusherru** [comment]
@dar2187 please close Smapp manually:
1. Open Smapp
2. Click on the close icon (cross)
3. In the prompt window choose the "CLOSE" option
4. When the Spacemesh icon disappears from the tray — install

**Comment by monikasmolarek** [comment]
It's not a Smapp-related issue per se.
