### ISSUE TITLE
Support the import of 12-word wallets

### ISSUE THREAD

**Issue by dafacto** [spacemeshos/smapp#1632]
### Rationale

I recently launched a web wallet at https://smeshwallet.com. It uses a 12-word mnemonic. I would like that users can later import their wallets into Smapp, if they decide to move to running a full node.

This would require one of two things:

1. Smapp support the import of 12 word wallets.
2. I upgrade SmeshWallet to support optional 24 word mnemonics on wallet creation.

As I'm personally funding the development and operation of SmeshWallet, my preference would be the first, that Smapp is updated to import 12 word mnemonics, but I'm also open to the second.

### Prerequisites

TBD

### User story

TBD

### Acceptance criteria

TBD

### Out of scope

TBD

### How to implement

TBD

### How to test

TBD

**Comment by brusherru** [comment]
Hello and welcome!
The feature is already there ;)
<img width="739" alt="image" src="https://github.com/spacemeshos/smapp/assets/1897530/852bbf02-0e4a-4aeb-ae50-a85b64fc8bcb">

**Comment by dafacto** [comment]
Ah, perfect! So I'd just need to add 24-word import to SmeshWallet, and they'd be fully cross compatible!
