### ISSUE TITLE
App Updater

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#164]

**Comment by avive** [comment]
We need to add the following:
- Add a new App update section to the settings under advanced settings.
In this section:
- Display detailed current app version 
- Have a checkbox for checking auto updates - it should be on by default so users can opt-out of auto-update.
- For users who opt-out of auto-updates, there needs to be a button to check for new app updates and trigger an update if a new update is found or tell the user no new update is available

@liathoffman @IlyaVi @yhaspel @zalmen

**Comment by avive** [comment]
Let's put auto updating on hold for now.

**Comment by brusherru** [comment]
It is a bit outdated. See an actual issue: #863
