### ISSUE TITLE
updated to version 1.3.8, now it doesn't work.

### ISSUE THREAD

**Issue by sbsmith09** [spacemeshos/smapp#1658]
### Environment

* Smapp version: 0.xx.x | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Open this
2.  Press that
3.  Click here and there

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by brusherru** [comment]
@sbsmith09 please make a bug report following the template and attach the logs.

**Comment by sbsmith09** [comment]
![Screenshot 2024-02-05 220125](https://github.com/spacemeshos/smapp/assets/129007803/02c4b135-20d6-4293-bb15-d3fb642cacae)

I cannot get it to start, it is stuck on this.

![Screenshot 2024-02-05 220125](https://github.com/spacemeshos/smapp/assets/129007803/100a6aa0-7b26-44de-8b63-b59c41959680)

**Comment by monikasmolarek** [comment]
Dear @sbsmith09  please provide your log files. 
We do not even know what OS you are using, but I'll assume it's Windows 11. 
You can find your logs here (most probably): C:\Users\{YOUR_USERNAME_HERE}\AppData\Roaming\Spacemesh 
You don't have to have your Smapp running to get the files. Both go-spacemesh and app-log files are needed. 

Also, we would appreciate more information about your case - your Internet connection stability, any custom settings applied, what might have changed etc. 

Thank you in advance

**Comment by sbsmith09** [comment]
Sorry, I don't know what you are asking for. This is all I found.

[image: Screenshot 2024-02-06 220329.png]

**Comment by sbsmith09** [comment]
My harddrive is almost full now, How do I delete all the Spacemesh files?

**Comment by sbsmith09** [comment]
How do I get my hard drive space back?

**Comment by monikasmolarek** [comment]
@sbsmith09, thank you for the additional comments from your side. Based on these slivers of information, I think you most probably encountered the issue described in #1631 
The process of organizing your drives is influenced by your current involvement in the project as well as your forthcoming intentions. This entails considering if you have already generated your PoS data and possibly earned rewards, or if you are in the initial stages and can safely remove all data. Additionally, it's important to evaluate whether you wish to continue participating, or if you feel that your PC/resources may currently be inadequate for participation.

Please check out the [README in this repo](https://github.com/spacemeshos/smapp?tab=readme-ov-file#troubleshooting) to find some basic information for your OS (which I still don’t know). 

In general, probably the biggest Spacemesh files are the node-data directory. (except the POS files of course). If you want, you could replace your state.sql with the one from this link: https://quicksync.spacemesh.network/tmp/1.3_state.sql.zip. (the file there is ~11GB.
