### ISSUE TITLE
Smapp incorrectly reports account not spawned

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#1673]
### Environment

* Smapp version: 1.3.10
* Node version: 1.3.10
* OS: Ubuntu 22.04

### Describe the bug

Smapp incorrectly reports that account is not spawned

### Steps to reproduce

1.  Install, run, and fully sync go-spacemesh
2.  Install and run Smapp
3.  Restore an existing, spawned wallet account

### Expected behavior

Smapp should report that the account is spawned

### Actual behavior

Smapp reports that the account is not spawned, despite the fact that it obviously is - a spend transaction is even visible under Transactions.

![image](https://github.com/spacemeshos/smapp/assets/3316532/f5928e31-0da7-4c16-81c6-dfecf29e60c4)

### Logs

[app-log.1.3.10.txt](https://github.com/spacemeshos/smapp/files/14315933/app-log.1.3.10.txt)

Possibly related: https://github.com/spacemeshos/smapp/issues/1674

**Comment by lrettig** [comment]
This persists even after generating another spawn tx, which of course fails because the account in question is already spawned: 
![image](https://github.com/spacemeshos/smapp/assets/3316532/2a9a3594-cce8-4e52-80cd-fa3a2d97f03e)

https://explorer.spacemesh.io/txs/0x74e0971eaab0b1f389d752e725ffdc7a82565eef45d846867158b3dbcdd24472

**Comment by pigmej** [comment]
On the first screen the network tab is `red` smapp loaded defaults. The second one needs checking.

Is it also the case when you have node running *next* to the smapp?

**Comment by lrettig** [comment]
> Is it also the case when you have node running next to the smapp?

What do you mean?

First of all, the node doesn't need to be _fully_ synced to check whether an account has been spawned. It only needs to be synced up to the point where it sees a spawn tx for the account. If it hasn't seen one yet, and it's not fully synced yet, then rather than saying "this account is not spawned yet," it should say something like, "Please wait until the node is fully synced. In the meantime you can check account status using the explorer" (with a link).

**Comment by pigmej** [comment]
It's caused by you running node that is not managed by smapp, as you pointed here https://github.com/spacemeshos/smapp/issues/1674
