### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by davemase1** [spacemeshos/smapp#1688]
### Environment

* Smapp version: 0.xx.x | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Open this
2.  Press that
3.  Click here and there

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by davemase1** [comment]
THE SPACEMESH NODE SOFTWARE HAS UNEXPECTEDLY QUIT. CLICK ON 'RESTART NODE' TO START IT.

**Comment by brusherru** [comment]
@davemase1 please fulfill the bug report template and provide all required details

**Comment by brusherru** [comment]
OK, I'm closing the issue due to the lack of details.
Next time please provide all the details mentioned in the issue template
