### ISSUE TITLE
smeshing

### ISSUE THREAD

**Issue by Hattrix3** [spacemeshos/smapp#1693]
I cannot click on get smeshing. Nothing is happening. I attached a log to see if this node is fully functional.
Can you let me know
[screen shot and log.zip](https://github.com/spacemeshos/smapp/files/14621897/screen.shot.and.log.zip)

also getting java error when running all benchmakrs see attached
![Screenshot 2024-03-15 202129](https://github.com/spacemeshos/smapp/assets/129607810/087bb43b-8ae9-4572-bcaf-abf5716c195f)

[###]([url]([spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/14621881/spacemesh-log-7c8cef2b.txt))) Environment

* Smapp version: 0.xx.x | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Open this
2.  Press that
3.  Click here and there

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by Saemy1** [comment]
@Hattrix3 why did you close it? I have the same issue
