### ISSUE TITLE
Mot earning for over a month

### ISSUE THREAD

**Issue by Hattrix3** [spacemeshos/smapp#1719]
### Environmentpc windows 11

* Smapp version: 0.xx.x | latest version adevelop
* Node version: v0.x.xx 
* OS: Windows 11| macOS High Sierra (10.13) | Ubuntu 20.04

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Open this
2.  Press that
3.  Click here and there

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by pigmej** [comment]
Hey, I explained to you today already in https://github.com/spacemeshos/smapp/issues/1694#issuecomment-2067936470

Is there anything new on your end?

**Comment by Hattrix3** [comment]
Nothing new There are no earnings what so eever when I finish initializing

**Comment by Hattrix3** [comment]
![image](https://github.com/spacemeshos/smapp/assets/129607810/c167a48a-111c-4576-8d03-458154537142)

**Comment by Hattrix3** [comment]
Going on over a month

**Comment by brusherru** [comment]
@Hattrix3 due to the attached screenshot your node is eligible for reward in layer 84572.
So keep your node working, then it will publish a ballot at this layer and then you'll get a reward.

It seems to me that there is no issue, so I'm closing it.
If you will have any problems or won't get a reward on mentioned layer — please open a new one and provide more details and logs (spacemesh-logs in this case).

**Comment by Hattrix3** [comment]
Joe ***@***.*** Apr 23, 2024, at 6:18 AM, Kirill Shumilov ***@***.***> wrote:﻿
@Hattrix3 due to the attached screenshot your node is eligible for reward in layer 84572.
So keep your node working, then it will publish a ballot at this layer and then you'll get a reward.
It seems to me that there is no issue, so I'm closing it.
If you will have any problems or won't get a reward on mentioned layer — please open a new one and provide more details and logs (spacemesh-logs in this case).

**Comment by Hattrix3** [comment]
Still asking for restarts why would this be?
