### ISSUE TITLE
Create network screen ui

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#19]
![18 – 1@2x](https://user-images.githubusercontent.com/16574879/55409452-bef2fa80-556a-11e9-97dd-a09b8bfc043b.png)
![18 – 2@2x](https://user-images.githubusercontent.com/16574879/55409453-bef2fa80-556a-11e9-8951-d77ee48b6a51.png)

**Comment by ImmanuelSegol** [comment]
@IlyaVi Could you assign me?

**Comment by IlyaVi** [comment]
@ImmanuelSegol after submitting PR you need to connect it to this issue and this way you'll become contributor to the project
