### ISSUE TITLE
Help users w/o sufficient disk space

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#207]
We need to do a better job informing the users what to do in case they have insufficient disk space when trying to setup a miner. At least a message telling them that this is an issue and linking to a help page on our site. So:

In the select drive screen, if no drive with 256GB or more free space is found, display this message:
'Insuffient disk space. You need a local hard drive with at least 256GB of free space to setup mining. [Learn more...]'

@liathoffman

**Comment by moshababo** [comment]
Not to replace a higher level check, but FYI we have this as well: https://github.com/spacemeshos/post/blob/develop/initialization/initializer.go#L241

The OS stats are not always stable, so I added an option to disable it.
