### ISSUE TITLE
Testnet coin awards docs tracking

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#213]
For the open testnet release:
1. How total awards are computed per epoch?
2. When an award is expected for a full node coin account?
3. What is the expected award SMC amount for running 1 full node in an epoch?

Required for the guide.

@zalmen @antonlerner

**Comment by antonlerner** [comment]
> For the open testnet release:
> 
> 1. How total awards are computed per epoch?
> 2. When an award is expected for a full node coin account?
> 3. What is the expected award SMC amount for running 1 full node in an epoch?
> 
> Required for the guide.
> 
> @zalmen @antonlerner

Total rewards per layer are calculated as following:
All TX fees of eligible transactions are accumulated and split among all miners who have created a block in the same layer.
In addition to TX fees a layer reward is added and split among all miners who have created a block.
Rewards are split between miners using a penalty reward system - miners that include less than 15 txs per layer are penalised by reducing their reward by 15%, the penalty is then distributed as bonus to all miners who have included more than 15 TXs.

Currently, Each layer will have a 1 SMC total reward distributed among participating nodes. Not including TX fees found in layer TXS.

**Comment by antonlerner** [comment]
Also, Rewards are on,y applied 5 layers after block has been processed.

**Comment by avive** [comment]
How's this guide to testnet users about awards? https://testnet.spacemesh.io/#/awards
