### ISSUE TITLE
Miner setup: routability test

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#221]
Adding this for tracking. We want to provide a button that the user can click in the miner screen to verify that his full p2p node is Internet routable. When clicked, we need to initiate a remote connection to the full node from the Internet and show a desktop notification when a ping request was successfully received by the full node. Alternatively, a full node should report via its API if it was able to receive remote incoming connections from other nodes.

**Comment by lrettig** [comment]
Not adding? Because we plan to eliminate the routability requirement?
