### ISSUE TITLE
Mining setup on windows

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#229]
On the lab's Windows 10 Pro - there are 3 drives with lots of space. In the mining setup only 2 drives are displayed and the free space displayed is wrong. Showing 2GB for drive D and 4GB for drive E. Drive C is not displayed.

**Comment by IlyaVi** [comment]
Need to remove rounding up to TB and leave it at more precise GB level. Also right now there is filtering of flash drives, this also probably removes logical disks with OS installed on it
