### ISSUE TITLE
Delete all on Windows 10 Home (virtual)

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#241]
Click delete all from settings.
Result: app is not closed and after restart, old wallet and password exist.
Expected: start a clean run - first time user experience after all settings deletion.

**Comment by IlyaVi** [comment]
It can't execute delete on virtual machine because of wrong path to app settings folder. Have to tested on real Windows machine as most of the actions with file system on virtual OS are prone to failure

**Comment by IlyaVi** [comment]
Also possible suspect is this line 116 in file fileManager
`const curPath = `${path}/${file}`;`
