### ISSUE TITLE
Allocate Space Screen Text Changes

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#261]
Left area:
`Setup Node` -> `Setup Smesher`
`Allocate Space` -> `Commit Space`

Main area:
Title: `Allocate Space` -> `Commit Space`
`Allocate how much...` -> `Set how much free space on xxxx you'd like to commit for Smeshing`.

- Remove all options besides the first one (256GB) - for Spacemesh 0.1 there's only 1 option. We keep this UX in preparation for Spacemesh 0.2 where hopefully we'll be able to allow variable storage allocation per node.

**Comment by yhaspel** [comment]
@avive @IlyaVi resolved as part of #256
