### ISSUE TITLE
Spacemesh Full Node Screen Text Changes

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#262]
title: 'Spacemesh full node` -> 'Smesher`
main body copy:
`Success! You are now a Spacemesh Testnet member!
- You will get a desktop notification about your smeshing rewards in about 48 hours
- You can close this window and chose to keep running smeshing the background

Important (remove the `:`)
- Leave your computer on 24/7 to smesh and to earn smeshing rewards
(Remove the `important` label from the network config line - we already say important in the title of this section)
- Learn more about smeshing
(Make the disable computer from going to sleep a link - link to this url in the guide: https://testnet.spacemesh.io/#/no_sleep)

---
`mining guide` command -> `Smeshing Guide`.

**Comment by yhaspel** [comment]
@avive I suggest changing:
You can close this window and chose to keep running smeshing the background
to
You can close this window and choose to keep smeshing the background
