### ISSUE TITLE
Confirm quit dialog box copy

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#264]
Quitting the App stops smeshing and may cause loss of smeshing rewards.

- Click RUN IN BACKGROUND to close the App window and to keep smeshing in the background.
- Click QUIT to close the app and stop smeshing.

[ Cancel]    [Quit]     [Run in Background]

**Comment by barakshani** [comment]
App version 0.0.3
The App used to ask, when being closed, whether to close it or let it run in the background. Now the App just closes.

**Comment by avive** [comment]
The implemented behavior is that if the app decides that smeshing is not setup then it will not prompt the confirmation. So, the issue is most likely the app deciding that POST is not setup by the user, and this issue is related to the other several POST related issues we see in 0.0.3.

**Comment by avive** [comment]
The current issue here is a typo in the copy. missing `and` before `may` in the description

**Comment by IlyaVi** [comment]
fixed in pr for #359
