### ISSUE TITLE
Start node for mining on 2nd run after smeshing setup is done

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#331]
- When the user has setup mining for the first time in the app (e.g. the app called the StartMining method on the node) we need to persist the coinbase address in the app persistent settings - ideally outside of the wallet file itself. 
- On future app starts, if we know that the app started the smeshing process previously, e.g. we have a coinbase account in the settings, it should start the node with the start mining flag and with the coinbase account.

- The node is supposed to continue w smeshing setup in case it was incomplete.
- If the node started with these flags then it should respond with the correct mining status to the app when queried.

**Comment by avive** [comment]
@noamnelke

**Comment by noamnelke** [comment]
👍🏻

Note that this also holds if the smapp restarts the node for any reason, even in the same session of the smapp.
