### ISSUE TITLE
Rewards display issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#357]
@barakshani - I produced 2 blocks at same layer, so I get rewards twice at the same time. My balance is correct, but under the Transaction log only one reward appears

**Comment by IlyaVi** [comment]
@avive this is definitely node issue cause app doesn't do any manipulation on received rewards list

**Comment by barakshani** [comment]
Pretty sure this has been fixed here: https://github.com/spacemeshos/go-spacemesh/pull/1789
@noamnelke please confirm

**Comment by avive** [comment]
We need to verify but it is a bit difficult because currently the app crashes on 2nd run each and every time and we moved to 24 hours epochs to test closer to f&f release params on GC. Might need to revert back GC to 30 minute epochs.

**Comment by noamnelke** [comment]
Only one reward should appear there, as discussed. The reward amount should be the sum of the reward for both blocks.

There's only an issue if the sum of transactions (incl. rewards) is different than the balance.
