### ISSUE TITLE
Node status display overhaul

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#358]
## Status control spec:

- Use the status control in the wallet screen to display the node statuses (p2p network, sync status) so we keep the smeshing screen just about mining.
- Get rid of the retry / refresh error message and consolidate error messages into the status control.
- Use /v1/nodestatus api to get the node status instead of ping - call it every 30 seconds to get up-to-date status. Note that any field may be omitted from the result json as currently implemented. For more info see https://github.com/spacemeshos/go-spacemesh/issues/1662 .
- 3 background colors of bars: error (red), attention (orange), all good: (green).
- All statues bar are close-able - same as error bar.

- When there's no response from the nodestatus API display this red bar: `Offline. Please quit and start the app again`.

- If peers is null || 0 in the api result:
  - Start p2p timer if it is not started and display orange: `Connecting to the p2p network...` 
  - If timer >= [config_network_timeout_min] display red: `Can't connect to the p2p network. [link to network config in the guide]`.
- if peer > 0:
  - stop p2p timer
  - if synced == true: display green bar: `Synced with the mesh. At layer: [syncedLayer].`
  - if synced == null || false: display orange bar: 'Mesh is syncing... [syncedLayer] / [currentLayer] layers ...

## New transaction button state (SEND):
- if peers < 1 || (synced == (null || false) then disable the 'SEND' button as currently new txs will not be broadcasted to the network. When user clicks on it show a message: `Please wait until your app is synced with the mesh`.
- if peers > 0 and synced == true then enable the 'SEND' button.

**Comment by noamnelke** [comment]
I'd add:
- If `peers > 0 && peers < minPeers && isSynced` display a red error that the node is experiencing network issues and that it might be under an eclipse attack and that you shouldn't trust the mesh it provides until more peers are connected.

Since we don't currently separate dialed-in and dialed-out peers, it's easy to overcome this protection (by just providing an eclipsed node with incoming peers) but it's good to implement this anyway and we can make it better in the future.

**Comment by avive** [comment]
Summary of bars:
Red Bars
- `Offline. Please quit and start the app again. [Get help]`
- `Can't connect to the p2p network. [get_help]`

Orange Bars
- `Connecting to the p2p network...`
- `Syncing the mesh... 3 / 232`

Green Bars
- `Synced with the mesh. Current layer 333. Verified layer 321`

**Comment by IlyaVi** [comment]
@avive Create this as epic in zenhub and create separate tasks under this epic

**Comment by avive** [comment]
Ilya - this just a github issue - you can view it with zenhub. There is nothing special about zenhub issues as far as I understand. This is basically one feature but you can open sub-issues for tracking of sub-tasks if you like. The send button state should be separated out to its own issue as well but it is good to have high-level epics like this that describe the whole flow / possible states that make this feature.

**Comment by avive** [comment]
<img width="1134" alt="Screen Shot 2020-02-10 at 11 10 44 AM" src="https://user-images.githubusercontent.com/96002/74215403-a33ba300-4ca9-11ea-8240-25ca28e1bb99.png">

**Comment by avive** [comment]
Is the disable / enable of the send tx button also implemented? We should implement it asap to prevent users from attempting to do tx we know are going to fail.

**Comment by IlyaVi** [comment]
Yes in Tx confirmation screen. I'll move it to the fist screen
