### ISSUE TITLE
Transactions IDs display

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#359]
Do not format tx ids like account ids - it is very confusing for users. 
Transaction ids should be formatted like this: `0x[first 6 hexa chars`. e.g. `0xf1aec2`.

**Comment by IlyaVi** [comment]
Done in previous prs

**Comment by avive** [comment]
Transactions still formatted like accounts - they should be formatted as specified in this issue's description.

**Comment by IlyaVi** [comment]
@avive can you point specific places where it is formatted incorrectly cause I can't find

**Comment by avive** [comment]
1. Transaction log - tx collapsed (summary view). Main display is something like 0x[10chars...10chars].
2. Transaction log - tx expanded - after label `transaction id`. format is 0x[20bytes].

<img width="1392" alt="Screen Shot 2020-03-20 at 11 49 07 AM" src="https://user-images.githubusercontent.com/96002/77152532-d3dcdc80-6aa0-11ea-9e55-849abcab3224.png">

**Comment by avive** [comment]
Please add 0x before transaction id - see above.
