### ISSUE TITLE
Smesher reweds date display bug

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#375]
Behavior: All rewards date/time are the identical and set to the last reward date/time.
Expected: Dates to display the reward assignment time.

<img width="1552" alt="Screen Shot 2020-02-14 at 9 24 52 PM" src="https://user-images.githubusercontent.com/96002/74561172-c8156c00-4f70-11ea-9aa3-a1817929c7fb.png">

**Comment by avive** [comment]
Still an issue with release 0.0.3

**Comment by IlyaVi** [comment]
@noamnelke something with return rewards function in node, got 18 rewards total, 9 with one timestamp and 9 with another timestamp, but rewards were given in different times

**Comment by noamnelke** [comment]
The rewards endpoint doesn't return timestamps, it returns layer numbers. Maybe the problem is with the conversion?

**Comment by noamnelke** [comment]
I see that we send transactions with a timestamp, so I don't mind adding a timestamp to the rewards as well, but let's first find out if this is the cause for the issue.

**Comment by IlyaVi** [comment]
On app side I don't do any manipulation with timestamp, it's displayed as received. I can add timestamps on my side and discard timestamps provided by node

**Comment by noamnelke** [comment]
This is the structure of the reward object:
```protobuf
message Reward {
    uint64 layer = 1;
    uint64 totalReward = 2;
    uint64 layerRewardEstimate = 3;
    // totalReward - layerRewardEstimate = feesEstimate
}
```

There's no timestamp in there, so not sure what you're displaying as-is...
