### ISSUE TITLE
Linux .deb installer package not working on Ubuntu

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#390]
**Describe the bug**

I fired up a fresh Ubuntu 18.04.3 server, downloaded the installer .deb file, and tried to install it, but clicking "Install" does nothing.

**To Reproduce**

Fire up a new Ubuntu VM
Follow instructions [here](https://medium.com/google-cloud/graphical-user-interface-gui-for-google-compute-engine-instance-78fccda09e5c) to set up gnome packages and VNC server: `sudo apt-get install gnome-core vnc4server`
`.vnc/xstartup` contains:

```
#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &

metacity &
gnome-settings-daemon &
gnome-panel &
```

**Desktop (please complete the following information):**
Ubuntu 18.04.3
Gnome 3.28.2
Metacity

**Additional context**

I was able to install the app using `gdebi` by following the instructions at https://www.ubuntupit.com/cant-install-deb-files-ubuntu-heres-possible-ways-install-deb-packages/.

**Comment by lrettig** [comment]
To upgrade to the latest package I did the following:

```
> sudo apt-get remove smapp
> sudo gdebi <new package.deb>
> rm -rf ~/post ~/.config/Spacemesh
```

**Comment by avive** [comment]
How do we resolve this?

**Comment by lrettig** [comment]
I upgraded the app today, and I installed the package with this command, which worked fine:

> sudo dpkg -i ~/Downloads/spacemesh_app_0.0.3_amd64.deb

**Comment by avive** [comment]
So maybe to close this we just need to add to the guide how to install using dpkg?

**Comment by lrettig** [comment]
I think that's fine for now. I tried on several VMs and was not able to get
the app to install by double-clicking the pkg file on any of them. I'm not
a Linux expert, I have no idea why this isn't working. Happy to dig deeper
on it if you think it's valuable, but all of our Linux users should be
comfortable running things on the command line and I can't imagine any of
them will struggle to run dpkg. I'll update the docs if we're in agreement
on this.

**Comment by lrettig** [comment]
Added here: https://github.com/spacemeshos/testnet-guide/commit/a9faa5ecc471eaee55d64a08b39e0d782fc2b261#diff-ac890c1ed8e54fcb56710db1a649959f
