### ISSUE TITLE
TX log sorting

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#403]
The transaction log txs should be sorted by time descending, showing the most recent txs and first.
In this view you can see that earlier transactions appear on top before newer ones.

<img width="1344" alt="Screen Shot 2020-02-26 at 6 15 29 AM" src="https://user-images.githubusercontent.com/96002/75311543-c47ec080-585f-11ea-8021-c97455a3783a.png">

**Comment by IlyaVi** [comment]
duplicate of #391
