### ISSUE TITLE
App forgets about post setup complete

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#411]
1. Install fresh 0.0.2 app and setup post.
2. Wait until post setup is complete.
3. Quit the app and start it again.
4. Go to Smesher screen.
Result: app prompts user to setup smeshing again.
Expected: App to show that post setup is complete and smesher is online.

**Comment by avive** [comment]
This is still an issue with 0.0.4_rc - just reproduced the issue. After starting meshing, sync and restart - the app prompts the user smesh again. We need to work on this together from both the app and the node perspectives until we figure out the true cause of this issue. @noamnelke @IlyaVi  @moshababo

**Comment by noamnelke** [comment]
From your description it sounds like 100% an app issue. If the node has some part in it, I need to know what it is before I can help.

**Comment by avive** [comment]
We are adding app logging to debug the API responses for StartSmining - I might also try to do a built with a diff TOML file that provides more node loggings - what I'm asking here is that both Node devs and App dev will work closely together to get to the bottom of this super annoying bug - we don't know yet what are the cause(s) and we should.

**Comment by noamnelke** [comment]
I never turn back @IlyaVi if he needs help investigating an issue. Here there's nothing I can do unless he finds that the node returns something it shouldn't. Even then the fix for this particular problem is on the app side, because an illegal response from the node shouldn't cause the app to forget that mining started (if the app doesn't know that mining started, then it shouldn't hide the prompt in the first place and it should show an error to the user).

**Comment by IlyaVi** [comment]
@noamnelke the main issue in this case that node postpones gRPC sever initialization until cache warmup is finished. Almog already fixed it and merged to develop. Can you cherrypick his pr and merge it to testnet branch? On app side I'm adding additional checks for mining status and adding protection to not allow mining until status was really retrieved for node

**Comment by avive** [comment]
I think that similar to the sync status, the app default state should be - 'please wait getting node status...' until the grpc API starts returning responses and definitely not default to offline and smeshing not started. This way even if it takes long time to warm-up or for the API to become available then we don't present wrong state to the users. This also takes care of the warmup issue. It is mostly a question of default state that we can fix without having to rely on a node update.

**Comment by yaelmhoffman** [comment]
This has not been fixed, testing on build 0.0.6.RC2 on Windows 10 Home.
![smeshing_not_set_up_on_restart](https://user-images.githubusercontent.com/56118594/77844370-f660ab00-71ae-11ea-8780-a5659def1f7e.png)

**Comment by avive** [comment]
FYI - I just reproduced this on 0.0.6.RC4 on Linux.

**Comment by avive** [comment]
I think we should change the node in the next release to log POST related API responses so we can figure out if and in what cases the node returns an unexpected value.
