### ISSUE TITLE
Wrong p2p error message on app startup

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#415]
1. Close the app and start it again after at least 10 minutes so it has mesh to sync.

Result: User gets the red bar `Offline. Please quit and start the app again. [Get help]` - close the app red error bar although the node is syncing just fine. The message changes to orange syncing after few minutes.

Expected: Do not display the red error bar in this case.

Possible fix: increase number of attempts and the time required to display the message so it is displayed less aggressively. It is too aggressively displayed. New node cache warmup can take few seconds...

**Comment by barakshani** [comment]
I experienced this bug and it remains red / offline all the time (for clarification, I was synced and created blocks). This was on App version 0.0.2. Upgraded to 0.0.3 (with the same database) and it turned blue / synced.

**Comment by avive** [comment]
If you look at the log, you can see that the recently added cache warmup may take few minutes, in which it is not clear what status the api returns to the app if at all. If you wait few minutes then the sync starts.

**Comment by avive** [comment]
Still an issue when starting up a node - shows red error for few seconds before getting sync status.
