### ISSUE TITLE
User is prompted to smesh when smeshing is already set up

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#416]
1. Sync the mesh, start smeshing and quit the app.
2. Wait 10 minutes and start it up.
3. Go to smeshing tab.

Result: App reports that smeshing is not set up although it is.
Expected: App display that smeshing is set up.
Note: happens also if user waits until mesh is synced again before going to the smeshing tab.

**Comment by avive** [comment]
@moshababo - maybe you can assist @IlyaVi on getting to the root cause of this issue?

**Comment by avive** [comment]
This is still randomly happens - we must get to the root cause(s) of this issue - it is the most severe release 0.0.3 issue.

**Comment by barakshani** [comment]
On App version 0.0.2 I experienced this bug. However, even without setting the folder for the init (on the second time) the node created an ATX, so it had access to the original post file to create a post proof.
Moreover, I did try to set init again, and after choosing the folder, I could not press the _next_ button (the button was grey / disabled).

When upgraded to App version 0.0.3 once again I was asked to set smeshing (node's log file shows that the original init was found), and could click on _next_. This time, after choosing 4GB, I got the "something wrong here... Retry failed action or refresh page." error message. Retrying doesn't help.

In both cases, I created a new folder (using the app) for the new post, and it was created (and remained empty).

**Comment by barakshani** [comment]
eventually, without re-doing init, i get the message "Your Smesher is online." in the smeshing section

**Comment by avive** [comment]
notice that if you attempt to start smeshing after you get this wrong message, it will fail showing the refresh / retry error message. Looks like the API result of StartMining returns an error to the app from the node.

**Comment by avive** [comment]
@IlyaVi - maybe you can write few words about what was the app-side fix to this issue and what should be expected now?

**Comment by IlyaVi** [comment]
rewrote closing app logic to make sure app closed after sending kill signal to node and small improvements in retrieving smeshing status from node
Also disabled "Start Smeshing" button after sending api call to smesh

**Comment by lrettig** [comment]
Not sure of the difference between this and #411 but I can confirm that this is happening on my OS X system right now with the latest 0.0.4rc build. I deleted all data files (Spacemesh dir, post dir) before starting it yesterday.
