### ISSUE TITLE
Delay quit until go-sm proc is terminated

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#419]
If the user quits and starts the app again before the go-spacemesh process has terminated then the app will fail on startup with an error. 

We should change the app shutdown process to wait up to 60 seconds while go-spacemesh is doing its pre-shutdown cleanups before shutdown and only quit once the managed process has been terminated.

**Comment by IlyaVi** [comment]
fixed in #412

**Comment by IlyaVi** [comment]
@avive what is the reason for reopening?

**Comment by avive** [comment]
Close when the new logic we spoke about is implemented - wait up to 60 secs but not 60 secs on each close...

**Comment by IlyaVi** [comment]
app waiting 60 sec only if node process is still there - if node already gone app will quit immediately, else it will wait for 60 sec. This logic is already merged to dev
