### ISSUE TITLE
Error on App quit - unhandled Promise Rejection

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/smapp#420]
App version 0.0.2
First time I closed the App I got the following error.
![Screenshot from 2020-03-02 12-09-49](https://user-images.githubusercontent.com/35497694/75697208-6ca7e580-5cb5-11ea-9644-c541a263842c.png)
Could not reproduce again.

**Comment by IlyaVi** [comment]
Unable to reproduce on version 0.4.0
