### ISSUE TITLE
Multiple init files

### ISSUE THREAD

**Issue by barakshani** [spacemeshos/smapp#421]
Installed App version 0.0.2 and after a while I've noticed that I have 3 init files for 2 different node ids, all of the size of 4.3GB.
- For the _actual_ node id, there is one init file in the folder I've chosen (Spacemesh/post/real_node_id)
- For a different node id, there are 2 init files, one in the same folder as mentioned above (Spacemesh/post/other_node_id) and the other one under Spacemesh/other_node_id

**Comment by avive** [comment]
As mentioned in other related bugs, we have yet to get to the bottom of these post setup issues. Regardless - please try to repro with 0.0.3 as POST related setup is one of the biggest change of this release over 0.0.2.

**Comment by avive** [comment]
Need to try to repo with 0.0.4
