### ISSUE TITLE
Add state root hash to mesh info in settings

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#422]
Use /v1/stateroot

@IlyaVi - in some cases this field is empty even when the node is synced. We need to improve this API and also return the layer number of the state root hash and display it. @noamnelke - part of API changes.

**Comment by IlyaVi** [comment]
if you will continue to reopen tasks without adding comments I'll close without doing anything

**Comment by IlyaVi** [comment]
@avive what is missing here? additional data from node?

**Comment by avive** [comment]
Add layer # of this state root. @noamnelke - is it always the last verified layer # ?

**Comment by avive** [comment]
The state root displayed should always be the last state root known to the node and the layer that the hash is for.

**Comment by avive** [comment]
Verified that you should use the last known verified layer. The root has is the root hash of that layer.

**Comment by avive** [comment]
@IlyaVi - new global-state api returns both layer # and hash - please display layer when you migrate global state to use api 2.0

**Comment by avive** [comment]
This is a nice feature but not as important as the core basic use cases of smapp 0.2 - wallet, transactions, etc... I would only work on it once the happy path for the basic use cases are fully working.
