### ISSUE TITLE
Rewards address display issue

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#423]
Should be 0x[20_bytes] canonical account display format - not the full public key.

**Comment by IlyaVi** [comment]
already fixed

**Comment by avive** [comment]
Still an issue with latest code in develop

**Comment by IlyaVi** [comment]
@avive address is displayed as "0x[20 last bytes === **40** chars] as per required in description. New requirement should be in new ticket

**Comment by avive** [comment]
Look at the rewards address. Currently displayed as: `e9ca7274c8813c010c3a46a7321abab6b65fa0fb2277bdca4336cf64607e05c5`
