### ISSUE TITLE
Logout user when app is minimized

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#424]
1. Run the app.
2. Click on minimize window button (or minimize in any other way. e.g. minimize menu command).
3. Open app again. e.g. click on it in the tray (or click show app command from the app widget menu).

Result: app opens at same screen and user has access to wallet.

Expected: app to logout user when it is minimized and prompts the user to unlock his wallet when it is unminimized.

**Comment by IlyaVi** [comment]
@avive it's not a bug but change in requirements, app was not logging out before when in background to display tx and rewards notifications

**Comment by avive** [comment]
hmm... I thought this was what we planned for security reasons. Let's revisit this in later app iterations.

**Comment by avive** [comment]
Ilya - when user minimizes the app window - can't you just execute the same code as you do when the user clicks on the log-out button?

**Comment by yaelmhoffman** [comment]
**Tested on**
Build: v0.0.6RC4.
OS: Windows 10 Pro.
Machine: Spacemesh Lab 1 

This issue is not fixed. App still logs out of wallet when minimized.

**Comment by IlyaVi** [comment]
Reopening was caused by not reading the description

**Comment by avive** [comment]
Clarified desc and desired behavior.

**Comment by avive** [comment]
Per @IlyaVi recommendation - let's not implement this enhancement right now as it got ux issues.
