### ISSUE TITLE
Do not display node error dialog box when node shutdown was initiated from the app.

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#435]
Still very easy to repro with 0.0.5. The app almost always displays can't connect to p2p - restart the app red bar on startup for few seconds while p2p is warming up. Please default to an orange bar with 'Node starting up, please wait....' message instead of this red bar on startup.

**Comment by IlyaVi** [comment]
Dialog error will appear only in dev or prod_debug mode only
