### ISSUE TITLE
Duplicated transactions display

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#444]
See screen shot - 2 incoming txs w the same tx id are displayed as distinct transactions.

**Comment by avive** [comment]
<img width="1392" alt="Screen Shot 2020-03-20 at 11 44 16 AM" src="https://user-images.githubusercontent.com/96002/77152258-44372e00-6aa0-11ea-896d-2a138be53185.png">

**Comment by IlyaVi** [comment]
@avive does it happens on latest version?

**Comment by avive** [comment]
can't repro.

**Comment by avive** [comment]
Repro case:
1. Send a transaction.
2. Go to tx log.
Result: tx with same id is displayed twice. 
Expected: tx displayed only once.
System: os x, 0.0.6

<img width="1392" alt="Screen Shot 2020-04-15 at 11 36 38 AM" src="https://user-images.githubusercontent.com/96002/79316798-8a4fa800-7f0d-11ea-9e1f-55c480533aff.png">

**Comment by avive** [comment]
Also an issue with 0.0.7 and also duplicated txs don't go away after app restart.
