### ISSUE TITLE
Invalid Date for new rewards in Smesher Screen

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#447]
- Not displayed in full tx log anymore.
- Invalid date in transaction summary view.
- Invalid date in smeshing log (smeshing tab)

**Comment by lrettig** [comment]
I'm seeing "invalid date" now too
![image](https://user-images.githubusercontent.com/3316532/77248435-b67a5080-6c0f-11ea-8354-525c256cfeda.png)

**Comment by avive** [comment]
yes, this is the issue.

**Comment by yaelmhoffman** [comment]
Not fixed. See screenshots and log file. 
![invalid_reward_date](https://user-images.githubusercontent.com/56118594/77794136-69b5d000-707c-11ea-9af6-29b4a461bf91.png)
![transaction_log](https://user-images.githubusercontent.com/56118594/77794160-720e0b00-707c-11ea-894b-9b004979ef74.png)

[spacemesh-log.zip](https://github.com/spacemeshos/smapp/files/4395651/spacemesh-log.zip)

**Comment by avive** [comment]
I see it too - in Smesher screen, new rewards dates in SMapp v0.0.6.RC2 are `Invalid Date`.

**Comment by avive** [comment]
As of 0.0.6.RC5 - still getting invalid dates in smesher screen. Dates in tx summary and log looking good for the same rewards.

<img width="1392" alt="Screen Shot 2020-04-01 at 9 10 25 PM" src="https://user-images.githubusercontent.com/96002/78171984-f6d29d80-745d-11ea-93c3-dc13e45d7839.png">

<img width="1392" alt="Screen Shot 2020-04-01 at 9 10 19 PM" src="https://user-images.githubusercontent.com/96002/78172004-fc2fe800-745d-11ea-9917-14a9dcb9e8d1.png">

<img width="1392" alt="Screen Shot 2020-04-01 at 9 10 30 PM" src="https://user-images.githubusercontent.com/96002/78171950-ecb09f00-745d-11ea-84df-07271f95be85.png">

**Comment by IlyaVi** [comment]
<img width="1230" alt="Screen Shot 2020-04-05 at 12 40 22" src="https://user-images.githubusercontent.com/16574879/78471740-42c26280-773c-11ea-8694-c940bdb67367.png">
fixed on latest dev code.
Note that the fix is not backward compatible - requires clean install
