### ISSUE TITLE
Don't reuse data folder across nets

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#455]
Motivation: as another layer of defense to avoid nodes using data from a different net.

Proposed enhancement:  Add the net id to the spacemesh local data folder.

If we do this then we can ensure that a local data folder from net x is never going to be used when running the app on net y.

**Comment by IlyaVi** [comment]
@noamnelke node is ok with any arbitrary folder name for storing it's data? Right now data is saved in "spacemeshtestdata" folder, can it be changed to "spacemeshtestdata{#netId}"?

**Comment by avive** [comment]
Ilya, I think that we want is the directory above it - the whole Spacemesh directory be unique per network id so no of the stored data is reused between networks. e.g. `Spacemesh113`, `Spacemesh114`.  And we should also rename the `spacemeshtestdata` to something more descriptive and a bit less confusing such as `data`.

**Comment by noamnelke** [comment]
Yeah, the node doesn’t care.

We should probably add similar functionality in the node itself, as well. Perhaps put a subfolder named after the net id inside any folder found in config (e.g. our whale probably doesn’t use the app).

**Comment by avive** [comment]
yes, rename `spacemeshtestdata` hard-coded into the node with `data-###` where ### is the net id.

**Comment by avive** [comment]
> Yeah, the node doesn’t care.
> 
> We should probably add similar functionality in the node itself, as well. Perhaps put a subfolder named after the net id inside any folder found in config (e.g. our whale probably doesn’t use the app).

Having the data folder the full node uses include the netid is a great idea that will make it unnecessary for users to remember to delete their data folder when moving between networks. Did you open a go-spacemesh issues about this? Current folder name is `spacemeshtestdata`.

**Comment by noamnelke** [comment]
Not sure what the node has to do... It gets the datadir as a configuration param.

We should change the datadir in the config, no code changes required.

**Comment by avive** [comment]
@IlyaVi  - I've looked at the code `spacemeshtestdata` is set by the app. Any reason we can't just rename it to `node-data` as part of the solution to this issue?

**Comment by noamnelke** [comment]
I just realized that it was me that suggested that the node should do something 🤦🏻‍♂️

Anyway, I think we could do what I suggested in March (put subfolder inside main datadir) or what I suggested today (change the whole datadir in the config). The main advantage of what I suggested in March is that even if the user overrides the config they can't mix the data from two netids.

@avive WDYT?
