### ISSUE TITLE
Add layer # to pending and approved txs

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#464]
Display layer id for confirmed txs. Currently no layer is displayed. If API doesn't return it then we need to address this on the API level. @noamnelke

**Comment by noamnelke** [comment]
A pending transaction may not be in a block yet, so what layer would you assign to it?

If it’s in a block we can tentatively put a layer on it, but it would be subject to change.

Approved transactions should have a layer in the api. If they currently don’t it’s a bug.

**Comment by noamnelke** [comment]
I don’t think assigning me to SMApp issues is great. If there’s work on the node to fix this (even if there might be and you’re not sure) please create an additional issue in `go-spacemesh` and put a link on it to this issue. I don’t look at this repository on a regular basis.
