### ISSUE TITLE
Outgoing tx address validation

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#466]
1. Start a new TX
2. Paste a valid address as the destination and remove 1 char from it
3. Click Next

Result: flow moves to confirmation screen. Click next - you'll get an error screen.
Expected: validate destination address and don't allow to go next if the dest address is invalid. Display the orange invalid address.

**Comment by IlyaVi** [comment]
@avive - can't reproduce it, validation is simple and solid: 42 chars if has '0x' and 40 chars without '0x' prefix; empty - longer - shorter trigger error
