### ISSUE TITLE
Settings tab malfunctioning after experiencing issue #470 (v0.0.6RC4)

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/smapp#469]
App build: v0.0.6RC4
OS: Windows 10 home

Expected:

User restarts app after it malfunctions, logs in to wallet, and can use all the features of the app.

Actual:

User restarts app after it malfunctions, logs in to wallet, and finds that clicking on settings makes them unable to use any of its main features.

Repro steps:

1. User restarts app because is was not connected to the network and had no status bar telling them why. This is caused by the app not running the go-spacemesh.exe process. See issue: https://github.com/spacemeshos/smapp/issues/470
2. User logs in to their wallet.
2. Status bar is back. "Syncing the mesh".
3. User clicks on 'settings'
4. Vague error dialog appears, with refresh button. User cannot click on "smeshing", "wallet", or "contacts". 
![refresh_prompt_after_clicking_settings](https://user-images.githubusercontent.com/56118594/77993661-3cde1300-7331-11ea-8e9c-2636c71576e3.png)

5. The refresh button can be clicked, but nothing happens.
6. Nothing happens when the user presses the 'settings' button, either. 
7. Logout button works as expected. User may log back in again to find the expected application display.
8. Error repeats when user clicks the 'settings' button.

**Comment by yaelmhoffman** [comment]
This appears to be a problem with the wallet itself. When I uninstalled and reinstalled the app, and restored the wallet, this exact issue occurred again.

**Comment by IlyaVi** [comment]
in 0.0.7 Settings tab is functional even when node is down or failed to start
