### ISSUE TITLE
If the app is reopened soon after it was closed, the go-spacemesh.exe is terminated while the app is loading, causing malfunctions

### ISSUE THREAD

**Issue by yaelmhoffman** [spacemeshos/smapp#470]
App build: v0.0.6RC4, v0.0.6RC5
OS: Windows 10 home

Expected:
User closes app, or restarts their computer. When the application is opened within a few minutes, it works correctly.

Actual:
User closes the app, or restarts their computer. When the application is opened within a few minutes of this, it displays the following malfunctions:
- No status bar 
![no_bar](https://user-images.githubusercontent.com/56118594/78120836-43dd5200-7413-11ea-8da8-4aac7bfcfc4a.png)

- Attempting to send smesh from the wallet results in an error message 
![refresh_prompt](https://user-images.githubusercontent.com/56118594/78120866-4b046000-7413-11ea-8ef8-f57c7e8936d5.png)

Repro steps:

1. Install app.
2. Run app.
3. Close app.
4. Open task manager.
5. Open app.
6. Expand Spacemesh process.
7. Note how the go-spacemesh.exe process starts, but is terminated before the app is finished loading. 
![processes_on_app_after_computer_restart](https://user-images.githubusercontent.com/56118594/78122557-991a6300-7415-11ea-8d68-b7c801627d1e.png)

7. Enter wallet password.

Note: if the user waits a few hours before opening, the issue does not occur.

**Comment by avive** [comment]
@yaelmhoffman - is this on the sm-lab1 desktop pc? might be useful to mention the test machine so we can have a look at it...

**Comment by yaelmhoffman** [comment]
This is on my home PC laptop.

**Comment by yaelmhoffman** [comment]
The issue does not reproduce in r0.0.6RC2

**Comment by IlyaVi** [comment]
tested on v0.0.15 in windows, app closes only after closing smesher process, no killing smesher process on app restart does not happen
