### ISSUE TITLE
Handle node crash situation

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#478]
We had few users who experienced the node crash on startup upnp bug. They didn't see a Smesher error dialog box and just waited for hours for the app to show it starts to sync...
Proposed fix: monitor the node while the app is running and if it is down (not responding to api calls) then show red error bar telling the user that the smesher has crashed ask the user to restart the app.

**Comment by IlyaVi** [comment]
this already exists in the app, red tab appeared in my app yesterday after node couldn't connect to any peer after some attempts

**Comment by avive** [comment]
Ilya - no red error tab when node crashes on startup - please check this case...

**Comment by IlyaVi** [comment]
@avive I just saw error bar when node failed to connect after 20 attempts, can't fix something that is working ok
