### ISSUE TITLE
Not all transactions and rewards displayed

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#482]
Account :0x40a21738d8a48805d390ffa1473b5ec24236b4f1
App version: 0.0.7 (internal) os x.
Behavior: Smapp displays only 3 txs and no rewards. Balance doesn't correspond to txs history.
Expected: Display all account txs and rewards.

Notes:
- Data via node API on same node used by smapp: 11 transactions and 4 rewards.
- Tried setting layerNumber in wallet file to 0 for the txs

**Comment by avive** [comment]
@IlyaVi - the transactions is a node issue but the rewards is not.

**Comment by IlyaVi** [comment]
fixed as part pof #495 
now app on start will retrieve all tx and rewards which happened while app was logged out/closed
