### ISSUE TITLE
Coin amounts mismatch

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#483]
- System: sm-mini
- App version: 0.0.6

Behavior: Balance: 446.602 smh but yearly coin 276.126 SMH. Smeshed: 393.314 SMH. Send: 5.0.2 SMH.
Expected: yearly coin stats to correspond to true balance.

**Comment by avive** [comment]
<img width="1392" alt="Screen Shot 2020-04-10 at 2 34 05 PM" src="https://user-images.githubusercontent.com/96002/78988014-66b8e600-7b38-11ea-9066-a633afb6d850.png">

**Comment by lrettig** [comment]
Hi. Why was this closed without any code changes?

**Comment by IlyaVi** [comment]
@lrettig it was fixed while fixing another issue

**Comment by lrettig** [comment]
@IlyaVi gotcha - can we link that issue here? Thanks!

**Comment by IlyaVi** [comment]
actually it is linked to PR #492 
see it above

**Comment by lrettig** [comment]
@IlyaVi thanks
