### ISSUE TITLE
No indication in app if node dies

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#491]
My go-spacemesh process died a few times (due to a time sync issue, unrelated to the app). The red bar that shows the syncing status in the app disappeared, but otherwise there was no indication that the underlying process had died, and no way to restart it. Under Main wallet on the main screen it still said "Syncing..." which is misleading.

Can we indicate loud and clear when the process dies--and let the user view the logs and/or restart the app when this happens?

**Comment by avive** [comment]
See #478

**Comment by avive** [comment]
@IlyaVi - not sure if you fixed it - when the node dies we don't see the red error bar saying that it is dead - this is what @lrettig noticed as well. I know there's logic to show the red error bar if the app can't connect to the nodes but it is not working in all cases and the status just remains syncing...

**Comment by avive** [comment]
@lrettig - what app version 0.0.7 or 0.0.6 ?

**Comment by avive** [comment]
In 0.0.7 if I kill go-spacemesh the node will show the red error bar as expected in 5 minutes so I think that this is a 0.0.6 issue that was already fixed.

**Comment by lrettig** [comment]
0.0.6

**Comment by lrettig** [comment]
Just saw the red warning bar pop up in 0.0.7, cool! This appears to be fixed :)
