### ISSUE TITLE
Account Commands

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#494]
We need to have a robust way to let user access account commands from the wallet without having to go through the settings. This UI mechanism is needed to add 2 important account features that we'd like to add soon: 1. set coinbase account. 2. Sign a message...

Right now we have a drop-down next to the account name in the wallet that is only displayed if the user has more than one account and we use it to enable user to switch between accounts.

We want to do the following changes:
1. Display the drop-down even if there's 1 account in the wallet.
2. Change the drop-down content to be a list of account-related commands.
3. Design a list of commands to be displayed when user clicks the drop-down icon.
4. Add the following commands to the menu:

I. `Set coinbase` - set the account as the coinbase address. When user selects it - use the node API to set the current account as the smesher's coinbase account.

II. `Sign message` - display the sign-message screen. TODO: Add issue about this feature.

III. `Accounts....` - display a list of wallet accounts and allow the user to click on one to make it the current account (like we have today). Only display this when there's more than 1 account in the wallet.

We can add additional account-specific commands to the menu once we decide to implement them.

**Comment by avive** [comment]
We need this to move forward on the sign-message feature which is important for the testnet community programs such as the swag store and the rewards program.
@IlyaVi @noamnelke @lrettig

**Comment by avive** [comment]
We already have designs for drop-down in the UI Kit - we can use them to implement this new drop-down. See: https://raw.githubusercontent.com/spacemeshos/product/master/resources/smapp%20ui%20kit%20light%20mode.png

**Comment by lrettig** [comment]
Aren't we going to want something akin to Metamask, that lets you sign a
message (or, in the future, a tx) in the browser?

>

**Comment by noamnelke** [comment]
@avive why did you tag me here - isn't this a wallet-only feature? You want to sign using the account's key, which only the wallet has, no?

**Comment by avive** [comment]
> Aren't we going to want something akin to Metamask, that lets you sign a message (or, in the future, a tx) in the browser?
> […](#)

Yes - signing a message. The cli wallet already supports it. Similar idea.

**Comment by avive** [comment]
> @avive why did you tag me here - isn't this a wallet-only feature? You want to sign using the account's key, which only the wallet has, no?

Sorry about that - mistake.

**Comment by avive** [comment]
@AskalAl

**Comment by avive** [comment]
Small tweak: please left align the command with the text above it - it is a bit too much to the left now.

**Comment by IlyaVi** [comment]
already implemented in pr #532
