### ISSUE TITLE
App displays waiting for smesher response for a long time while node is already syncing and api responsive.

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#501]
- It can take more than 30 minutes to show synced but in some cases even after 50 minutes - there's no status.
- Repro easily on os x with 0.0.7

1. Quit synced app
2. Wait 20 minutes or more
3. Start app again

**Comment by lrettig** [comment]
Happening to me too, on Windows, from time to time

**Comment by avive** [comment]
We have an emergency patch for this that is verified to fix this problem. Please install 0.0.7 again and it should be fixed.

**Comment by lrettig** [comment]
This is still happening for me on the latest build

**Comment by avive** [comment]
For me as well. @IlyaVi @antonlerner - please prioritize investigating this - it is not clear if this is a node or an app specific issue. In my tests, the node is synced but without full app logs it is hard to say what api responses it is getting from the node that may cause it to get stuck in this state. I currently can't get the app on one of my nodes to go blue, no matter what I try and how many times I restart it. This issue makes the app quite unusable.
0.0.7 OS X.

**Comment by IlyaVi** [comment]
fixed in app release 0.0.8
