### ISSUE TITLE
Node id is reused across installs on same system

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#510]
1. Install smapp, run it and set post. Take note of the node id and the post folder name.
2. Stop smapp, uninstall it. Delete the post data folder and verify the Spacemesh local data folder is gone.
3. Install the app, start it and setup post.

Result: same node id is used from the previous install.
Expected: new node id to be created and used.

Where is the old node id coming from? Electron storage of app data?

**Comment by avive** [comment]
@y0sher - fyi.

**Comment by IlyaVi** [comment]
app can't set or make any other decision on node id, this ticket refers to node
