### ISSUE TITLE
Malformed address display

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#511]
1. Start a new tx.
2. Paste destination address.

Result: In summary, destination address (TO field) has only first 2 hex chars. e.g. `0x42...5b3b`
Expected: display canonical short-form string for address. e.g. `0x42b5...5b3b

**Comment by avive** [comment]
<img width="1392" alt="Screen Shot 2020-05-08 at 1 07 04 PM" src="https://user-images.githubusercontent.com/96002/81395851-07e18f00-912d-11ea-989e-ac535167d6ed.png">

**Comment by IlyaVi** [comment]
fixed as part of #495
