### ISSUE TITLE
Display time for rewards in the tx log

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#517]
App knows the net genesis timestamp, the layer duration and the reward's layer id. Based on that it can compute a timestamp of when this reward was given based on the layer number in the reward's data. This date-time should be displayed in the tx log. Right now, only the layer number is displayed in the expanded view of a reward.

**Comment by avive** [comment]
This is the case when rewards are received when the app is open. If they are received when it is closed then they will be displayed when it opens again with time stamp as expected.

**Comment by lrettig** [comment]
@IlyaVi here's my current `config.json`: https://gist.github.com/lrettig/64b943826d2f3e1b0a3c74da219185d3

**Comment by IlyaVi** [comment]
@lrettig when the fix is deployed you have to delete this file before the first app start

**Comment by lrettig** [comment]
@IlyaVi okay, thanks for the heads up
