### ISSUE TITLE
Spec wallet file format

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#519]
Provide detailed spec for the smapp wallet file format so we can implement it in CLIWallet and support the same wallet files across the 2 reference wallets.

**Comment by IlyaVi** [comment]
```
{
  "meta": {
    "displayName":  string <wallet name>,
    "created": string <UTF timestamp>,
    "netId": int,
    "meta": { "salt": "Spacemesh blockmesh" }
  },
  "crypto": {
    "cipher": "AES-128-CTR",
    "cipherText": string encrypted with AES block cipher algorithm,
         decrypted form is:
          {
             "mnemonic": string of 12 words used as seed for key derivation,
             "accounts": array of 
                {
                   "displayName: string,
                    "created": string <UTF timestamp>,
                    "path": string of form "0/0/<accountNumber>" - for future usage,
                    "publicKey: string,
                    "secretKey": string
                  }
            }
},
  "contacts": array of { "address": string, "nickname": string }
}

@avive for your review
```

**Comment by avive** [comment]
Minor edits:
{
  "meta": {
    "displayName":  string <wallet name>,
    "created": string <UTF timestamp>,
    "netId": int,
    "meta": { "salt": "Spacemesh blockmesh" }
  },
  "crypto": {
    "cipher": "AES-128-CTR",
    "cipherText": string encrypted with AES block cipher algorithm,
         decrypted form is:
          {
             "mnemonic": string <12 words used as seed for key derivation>,
             "accounts": array of 
                {
                   "displayName": string,
                    "created": string <UTF timestamp>,
                    "path": string of form "0/0/<accountNumber>" - for future usage,
                    "publicKey: string,
                    "secretKey": string
                  }
            }
},
  "contacts": array of { "address": string, "nickname": string }
}

- Please add a concrete example of a real wallet json and also the json of the same decrypted wallet.
- Please add the key derivation algorithm used to generate the AES symmetric key from user entered password.

**Comment by IlyaVi** [comment]
@avive look in the attached PR

**Comment by IlyaVi** [comment]
https://github.com/spacemeshos/smapp/pull/524
