### ISSUE TITLE
Migrate app to use API 2.0 services

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#536]
Opening this as a placeholder to track this project. The API design has been finalized and implementation is happening now in spacemeshos/go-spacemesh#1764.

**Comment by lrettig** [comment]
When trying to run smapp against the latest go-spacemesh build (v0.1.18) I get this error in the app log: `unknown flag: --grpc-server`. This needs to be updated to use the CLI args for the new API, as the old API has been removed from the latest go-spacemesh build.

**Comment by avive** [comment]
What are the updated cli flag that the node should be started with which are not provided via the config file?

**Comment by lrettig** [comment]
> What are the updated cli flag that the node should be started with which are not provided via the config file?

Not needed if specified in the config, just drop the `--grpc-server` arg
