### ISSUE TITLE
Created new wallet and old transactions showing reversed

### ISSUE THREAD

**Issue by whoabuddy** [spacemeshos/smapp#549]
**Describe the bug**

After reading [this message from Cheshire_Cat](https://discordapp.com/channels/623195163510046732/691261757921951756/723183114804920370) about the wallet/contacts issue when upgrading from 0.0.13 to 0.0.14, I upgraded the software, then decided to send my SMH around and empty out my old wallet before creating a new one. 

These were the four transactions:
- [0xec0b4d9eaede81a8450fc6afa2aa080c5ec82e9a419b49db75ccfa7c78384f71](https://calistra.com/explorer/tx/0xec0b4d9eaede81a8450fc6afa2aa080c5ec82e9a419b49db75ccfa7c78384f71)
- [0x5f4288018c442ca887bcc361bbe6d8e2ef681d3cf07f379a7da6f13a2325d916](https://calistra.com/explorer/tx/0x5f4288018c442ca887bcc361bbe6d8e2ef681d3cf07f379a7da6f13a2325d916)
- [0xfe9c0088ebb789e6a67b2ed7b752a5e2b8cbd132492339cba7a34eb233b19da9](https://calistra.com/explorer/tx/0xfe9c0088ebb789e6a67b2ed7b752a5e2b8cbd132492339cba7a34eb233b19da9)
- [0x7aafcfbea95243a46f6861f5bd38b899b4e7672f02f59f98171ea04108012c4e](https://calistra.com/explorer/tx/0x7aafcfbea95243a46f6861f5bd38b899b4e7672f02f59f98171ea04108012c4e)

Once I saw the transactions were confirmed via the explorer (after the below screenshot was taken), I closed the smapp, deleted the `my_wallet_` file from `~/.config/Spacemesh`, then opened it again. After creating the new wallet, the transactions flipped from `sent` to `received` in the logs.

**To Reproduce**
1. Install the 0.0.14 .deb file via dpkg
2. Send a few transactions
3. Wait for confirmation
4. Close the smapp
5. Delete the `my_wallet_` file from `~/.config/Spacemesh`
6. Open the smapp
7. Configure a new wallet password
8. View the transaction log

**Expected behavior**

I expected the log to either start fresh with no entries, or to correctly show the past transactions.

**Screenshots**

![VirtualBox_SmeshLikeAMofo_20_06_2020_14_46_31_13to14upgrade](https://user-images.githubusercontent.com/9038904/85212434-9d189b80-b307-11ea-9905-119225308476.png)

![VirtualBox_SmeshLikeAMofo_20_06_2020_14_41_38_very_merry_unbirthday](https://user-images.githubusercontent.com/9038904/85212435-9f7af580-b307-11ea-90f6-feae694d715e.png)

![VirtualBox_SmeshLikeAMofo_20_06_2020_14_56_06_after_upgrade](https://user-images.githubusercontent.com/9038904/85212436-a1dd4f80-b307-11ea-908a-9ec1a5a98591.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu Desktop 20.04

**Additional context**

Zipped copy of the log file: 
https://envl.app/whoabuddy/7zSdpV!fZIXy7rFykbNAL5L

**Comment by IlyaVi** [comment]
It's not a bug - it follows the app logic of retrieving history of transactions for each account in the wallet from the mesh. The network did not change, so those transactions are in mesh: for sender they are outgoing, for receiver - are incoming. Removing log file won't make a difference - final state will be the same as you see it.
If you'd like to remove transactions log before future release - delete 'config.json' file in the same directory as wallet file

**Comment by whoabuddy** [comment]
@IlyaVi I am not sure I understand why it shows these as positive / received values. I was not the recipient in this case, I only created a new wallet.

I know the transactions were confirmed so I expected them to stay valid, but they were to 4 different addresses randomly grabbed from the tap channel in Discord, not to my own wallet.

Shouldn't the account history show that I sent those amounts, not received them?

**Comment by lrettig** [comment]
This looks like a bug to me - @IlyaVi could you take another look? As OP said, he did not swap to the recipient account, the transactions were sent to third party accounts.

It seems like something funny is happening with the old tx data in `config.json` when a new wallet is set up. Shouldn't the app just totally clear the tx history when switching wallet accounts?

**Comment by avive** [comment]
The desired behavior is that the app should clear these locally saved transactions unless they are to or from an account which is in the currently loaded wallet.
