### ISSUE TITLE
Wallet "To" address display issue

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#566]
**Describe the bug**
When I paste a wallet address into the "To" field on the "Send SMH" screen, the address I see displayed to the right under Summary doesn't match the address I pasted.

**To Reproduce**
1. Go to WALLET
1. Go to Send SMH
1. Paste an address into the first field, the "To...." field

**Expected behavior**
The TO address displayed under Summary to the right should match the pasted address. (It appears to display the final few bytes of the address, not the full address)

**Screenshots**
![image](https://user-images.githubusercontent.com/3316532/91750886-d4ba8400-eb91-11ea-8d92-125379dc5232.png)

**Desktop (please complete the following information):**
 - OS: Linux
- Version: 0.1.0

**Comment by avive** [comment]
We have this canonical form for a string that displays a tx which is 0x1234...5678 that we used everywhere in smapp where 1234 are the first 4 hex chars of the address and 5678 the last. 
It looks like this breaks in the To field - 0x1e3d....6a94 should be displayed.
@IlyaVi

**Comment by lrettig** [comment]
Looks like this was fixed in https://github.com/spacemeshos/smapp/pull/567 -
thanks Ilya!

>
