### ISSUE TITLE
Support Mainnet wallets

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#576]
# Motivation
We need to provide users with a way to create a wallet to be used in main-net few months prior to genesis. 

# Challenges
Unlike a testnet, we don't have a network params file for mainnet until close to mainnet launch and in addition the mainnet network params file is going to include accounts that were specified with this feature (mainnet wallets in smap) so we kind of have a catch-22 situation and need to special handle the case when user selects to create a mainnet wallet. We also need to provide a solution for using this wallet post-genesis so these wallets are usable on mainnet.

**Comment by monikasmolarek** [comment]
no longer applicable
