### ISSUE TITLE
Improve add contact feature

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#601]
Change placeholder text in address text box from `Wallet Address` to `Account address 0x24f7...` in all places in the ui where user can create a contact.
Motivation: we don't have wallet addresses, only account addresses and give hint of the expected address format.

@noamnelke

**Comment by noamnelke** [comment]
I would add labels to the text boxes, with smaller hints about the content between the label and the text box. The hint of the address should be: `Example: 0x24f789c9057a6007b235933520ae0f23276a906f` - I think it's important to show the length of the address with no ellipsis.

It's generally [discouraged](https://www.smashingmagazine.com/2018/06/placeholder-attribute/) in [the UX field](https://feedbackguru.com/articles/form-without-labels-dont-use-placeholder-text/) to use [placeholder text](https://www.nngroup.com/articles/form-design-placeholders/).

**Comment by avive** [comment]
We will find a solution. There's not enough space for a whole long address w/o making it very small. Placeholders are awesome for hints and user-education - this article you shared by a hip designer that is wrong.
