### ISSUE TITLE
Handling explorer links from dashboard

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#616]
# Motivation

Dashboard includes links to explorer. Current behavior is that explorer opens when user clicks on such a link in a new smapp window for display. This is not optimal because that screen doesn't have standard browser address bar and navigation buttons which are required for the full explorer experience.

Proposed fix: Open explore links in user's system default web-browser instead of a custom smapp window so user has access to url and navigation buttons, can set bookmarks, etc... We want to avoid having to build a mini browser ui for this screen as the user already has a full browser on his desktop which he's used to...

**Comment by IlyaVi** [comment]
@avive after long research there is no way to catch links from inside web view in electron and open those in external browser

**Comment by avive** [comment]
There must be a way. Please do some more research. The current config is unusable. Someone must have had this issue in Electron and solved it.
