### ISSUE TITLE
Smesher log area layout

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#645]
The smesher log area is vertically misaligned. It should be vertically aligned with the smesher display and have same height.

<img width="1003" alt="Screen Shot 2020-12-06 at 5 49 17 PM" src="https://user-images.githubusercontent.com/96002/101284988-944f4f80-37eb-11eb-8495-b1134afb5539.png">

**Comment by IlyaVi** [comment]
fixed as part of #637
