### ISSUE TITLE
Vaults Screens Design Review

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#661]
Note: only reviewed dark mode for now.

# All Screens
- Missing `back button` in almost all screens. See purple back button in all relevant mocks on figma.

# New Vault Screen
- Set default vault name to 'My Vault' so in many cases user can just click next with default new vault name. Code need to check for unique new vault name to avoid duplicated vaults in one account.

# Vault Type
-`simple vault` and `multi-sig vault` titles are black but should be white - see figma mock.
- Radio box design has white circle frame and not black.

# Vault Master Account (See figma page name New Vault Step 3 - Simple Vault)
- Label is wrong `vault name` - needs to be `Account`. This is a bug in the figma mock.
- There should be ... white dots and the drop-down should be right-aligned - see figma mock.
- Drop down should display all account's addresses in the drop-down and be wider. In the simple case of one account in a wallet, display this account as the vault's master account in the drop-down by default.

# Vault Master Accounts (2/3 multisig vault)
- Similar to simple single account vault, address 1 drop-down should be populated with all accounts in the current wallet.
- Missing button `save and finish later` - important in case user needs to paste 2 addresses from the other account holders to finish setup.

# Daily Spending
- Replace `Accnt` with `Account` in the label.

# Create Vault Transaction 
- Missing `save and finish later` button.

# Review New Vault 
- All data items are in black and should be white.
- Gray background in main data area is cropped and doesn't include the last line - see mock.
- Missing Cancel button.
- Green button label should be 'CREATE VAULT' and not 'NEXT'.

# New Vault Submitted 
- The large big icon is meant to be a celebration animation - please ask Vince for the gif file for it.
- Green button label should be 'DONE' and not 'NEXT'.

**Comment by Motzart** [comment]
> The large big icon is meant to be a celebration animation - please ask Vince for the gif file for it.

@avive  you mean change this icon from 
<img width="521" alt="Screenshot 2021-01-14 at 15 20 54" src="https://user-images.githubusercontent.com/6236839/104596259-71327e00-567c-11eb-8833-a0143f45b825.png">
to this
<img width="368" alt="Screenshot 2021-01-14 at 15 21 24" src="https://user-images.githubusercontent.com/6236839/104596279-77c0f580-567c-11eb-8f56-d8004d90a9dd.png">
?

**Comment by avive** [comment]
yes

**Comment by avive** [comment]
@vomcent please provide animation for new vault creation celebration.

**Comment by vomcent** [comment]
Attached is the fireworks animation in both black and white.

![Fireworks-Redo-white](https://user-images.githubusercontent.com/49878947/104616206-066f4b80-5658-11eb-8b75-d4a6e37c1b66.gif)
![Fireworks-Redo](https://user-images.githubusercontent.com/49878947/104616260-12f3a400-5658-11eb-9471-31c0812a6e10.gif)
