### ISSUE TITLE
Min Window Size and Margins

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#670]
The min window size is too big. It appears like wide margins are enforced.
Repro: try to make the smapp main window as small as you can.
Result:

Expected:
Let the user make the window smaller and resize down the margins around the content. Min size should include the current inner content area with some small margins around it. I think that we can have a constant inner content area which is applicable to almost all screens where some screens have taller min size. It is okay if the bottom area of such screen is cropped when user set the app size to min size and we expect him to resize the main window to display the full content in this case which is acceptable.

@vomcent - please provide min margin sizes that work well visually. 
 
<img width="1392" alt="Screen Shot 2021-01-18 at 2 36 18 PM" src="https://user-images.githubusercontent.com/96002/104916480-cdf2a900-599a-11eb-9ee6-3e5638c28230.png">

**Comment by vomcent** [comment]
Here are examples:

Normal margins as they exist now:
![Normal Margins](https://user-images.githubusercontent.com/49878947/106187782-1157cf00-6174-11eb-8b80-f0f6bf48597e.png)

Minimized margins are as follows: 32px from rectangle module edges on left, bottom, and right. Top has 32 pixels from rectangle module top to the bottom of the 4 buttons in top right corner. Space between top nav + buttons and the top edge of the screen does not change. top Nav is anchored to the left side, top buttons are anchored to the right side.
![Minimized Margins](https://user-images.githubusercontent.com/49878947/106187783-11f06580-6174-11eb-974d-b0bc7d1acd6b.png)

@avive mentioned that when more things take up the space (for example, a status bar or back button appears) it should just resize the window to compensate.

**Comment by Motzart** [comment]
@avive @vomcent not so clear for me, what i should do?
