### ISSUE TITLE
Duplicated transaction row in log

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#671]
1. Send a transaction and wait until it gets confirmed.
Result: 2 rows for the tx - one pending (stays pending) and one for the cofirmed one.
Expected: Only 1 row per unique transaction. Don't display the pending transaction once the confirmed one is displayed.

<img width="1392" alt="Screen Shot 2021-01-18 at 2 52 36 PM" src="https://user-images.githubusercontent.com/96002/104918017-d4822000-599c-11eb-9382-c8e6c4a79137.png">

**Comment by avive** [comment]
Notice that this is also an issue in the transactions preview in the wallet screen - duplicated entry. The 10 SMD transaction is the same transaction.

![Uploading Screen Shot 2021-01-18 at 2.55.59 PM.png…]()

**Comment by avive** [comment]
@IlyaVi - is this issue fixed?

**Comment by IlyaVi** [comment]
No, but the logic in new version for api 2.0 will be different so such bug won't be possible

**Comment by IlyaVi** [comment]
new tx logic saves txs by their ids so no duplicate txs will appear in ui
