### ISSUE TITLE
Tooltip text cropped in dash screen

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#672]
1. navigate to dashboard screen.
2. hover over main commands in top toolbar.

Result: tooltip appears behind dash area.
Expected: tooltip to appear above so its text is not cropped and readable.

<img width="1392" alt="Screen Shot 2021-01-18 at 5 35 03 PM" src="https://user-images.githubusercontent.com/96002/104935187-95ab9480-59b3-11eb-80ab-55911974caf2.png">

**Comment by Motzart** [comment]
i don’t think that we can do it,
main window and dashboard it is two separate windows, and dashboard overlap main window,  
i just can add a little more space for for tooltip between navbar and iframe window(dashborad)
<img width="604" alt="Image-1" src="https://user-images.githubusercontent.com/6236839/105342027-7c3f5e00-5be8-11eb-9b5f-96e5fd36a84b.png">
