### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#680]
Some community smeshers have complained about their go-spacemesh node logs getting too big. I've got log files that have grown as big as 5GB after a few weeks of smeshing on the testnet. While we can probably find ways to reduce log verbosity (CC @noamnelke), regardless, logs will still continue to grow and eventually we will need a log rotation strategy.

This should be in smapp, not in go-spacemesh, since go-sm does not write to any log files by default.

**Comment by avive** [comment]
Should be trvial to add 'clear logs' command to settings that just deletes the go-sm and app log files as a sort term solution and auto clean logs as soon as they grow over a certain size automatically soon after. @IlyaVi what do you think?

The logs are indeed huge and this is a problem for a long running testnet. Are we 100% sure that all log info is useful for debugging? I know that @moshababo just started a log refactoring initiative so I hope that reducing logs size will be part of it.

**Comment by lrettig** [comment]
Can we rotate and compress, rather than discarding logs, for now? Or else at least set the limit very very large for now, to make debugging easier for testnet.

**Comment by avive** [comment]
There are currently 2 logs: Smapp logs and full node logs. The handling of go-sm logs - enabling rotation, compression, etc... should be done in go-sm and not in Smapp. Smapp should enable user to change go-sm log related startup flags. So this should IMO go to go-sm. In the short term, we can add the 'clear logs' command I proposed above to make it easier for users to delete old logs but this is just a temp hack until there's better logs handling features in go-sm.

**Comment by noamnelke** [comment]
`go-spacemesh` emits the logs to `stdout`, it therefore cannot be responsible for rotation, as it's not the component that stores the logs in files in the first place.

**Comment by avive** [comment]
so, I'm a smesher running go-sm and cliclient? Do I need to write my own log rotation logic?

**Comment by noamnelke** [comment]
There are CLI tools that do it. If you're comfortable running the node in the terminal yourself, this is a legit requirement.

I'm not against writing a wrapper that will handle this for you and maybe also run the node in the background as a daemon, with keepalive etc., and allow you to shut it down by running some command, but it makes less sense to make it part of the node.

**Comment by lrettig** [comment]
Agree. That's why I opened this issue in this repo in the first place.

**Comment by brusherru** [comment]
I think it shouldn't be complicated.

The easiest solution is to use https://www.npmjs.com/package/node-log-rotate and just clean all logs older than one or a couple of days every 24h.

Much more complicated solution is to make something like circular buffer. But I'm not sure that it is handy (it will be harder to find a start of the log) and such file should also contain a byte number of the latest EOL to make it easier to append/overwrite lines.

So I propose to implement an easiest solution and leave it until we need some changes in it.

@avive @lrettig what do you think?

**Comment by maparr** [comment]
@lrettig , @oriya, @brusherru  
I want to take this task in the next dev iteration, can I work on this task, or still on-hold ?

**Comment by lrettig** [comment]
Not on hold, I think you can work on this, and it would be helpful to have for the next stage of the testnet.

> The easiest solution is to use https://www.npmjs.com/package/node-log-rotate and just clean all logs older than one or a couple of days every 24h.

I don't think this will work, at least not for rotating node (go-spacemesh) logs. This library is for logging from within the JS application. In our case, we need to rotate logs generated by an external, child process.

**Comment by maparr** [comment]
Hi @lrettig , I created a [PR](https://github.com/spacemeshos/smapp/pull/953) and attached a demo video
we have getting all logs from stdout/err  and piping it to the log file , so go-spacemesh logs also will be rotated
