### ISSUE TITLE
Dashboard Nav Label Disappearing

### ISSUE THREAD

**Issue by vomcent** [spacemeshos/smapp#688]
when hovering on dash, the text from hover nav gets covered as if its behind an invisible rectangle.

Expected when hovering over DASH: 
<img width="590" alt="Screen Shot 2021-01-26 at 5 04 15 PM" src="https://user-images.githubusercontent.com/49878947/106031494-58bf5c00-609d-11eb-94f3-f735e2e24cb0.png">

Incorrect when hovering:
 <img width="594" alt="Screen Shot 2021-01-26 at 5 04 23 PM" src="https://user-images.githubusercontent.com/49878947/106031492-58bf5c00-609d-11eb-9343-04029ae5d361.png">

**Comment by Motzart** [comment]
i explain this issue here - https://github.com/spacemeshos/smapp/issues/672
