### ISSUE TITLE
Create Wallet/Unlock Wallet/Restore Wallet Flows

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#7]

**Comment by ImmanuelSegol** [comment]
@IlyaVi Could I take this?

**Comment by IlyaVi** [comment]
@ImmanuelSegol we are already working on this epic, I've created a new epic and it has this 
[task](https://github.com/spacemeshos/smapp/issues/19) which is fine for the starter
The corresponding screen in design is screen number 18

**Comment by yhaspel** [comment]
[https://xd.adobe.com/spec/82a02ed8-aecc-466a-4107-10c94808ade3-f491/screen/d77898a8-40ff-4ea1-a86d-a880e8f0ad3a/1/](url)

[https://xd.adobe.com/spec/82a02ed8-aecc-466a-4107-10c94808ade3-f491/screen/f75eee79-46df-49ba-bb1b-2f9556ef5b6c/2/](url)

[https://xd.adobe.com/spec/82a02ed8-aecc-466a-4107-10c94808ade3-f491/screen/d20665d7-706e-4582-be85-7026bf9daa5c/3/](url)

[https://xd.adobe.com/spec/82a02ed8-aecc-466a-4107-10c94808ade3-f491/screen/ca8dffe0-90b3-4031-804a-a89c2ecb72f6/4/](url)
