### ISSUE TITLE
Don't show spinning wait icon forever at startup

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#717]
When issues like the one described in #716 occur at startup, and the node crashes, the Spacemesh icon should not continue to spin forever. Smapp should detect that the underlying node died and present the user with an error message, ideally with a link to open or find the logfile with a single click. If a timeout is needed, it should probably be 30-60 secs.

**Comment by avive** [comment]
@lrettig  - there's a whole new smapp startup flow which includes not using a local node so it makes little sense to patch the spinning startup screen now. Smapp will handle the case that node crashes on startup when it starts a local node in the new flow will not wait forever. I think this is described in the new startup flow for smapp 0.2.

**Comment by avive** [comment]
All node crashes should be reported in the network screen in smapp 0.2 as long as they are reported via the api and also after long timeout of api not being available when managed node was started. As the new api usage is a complete rewrite of how Smapp 0.2 handles node errors I'm going to close this issue.
