### ISSUE TITLE
Run smapp as a cli tool

### ISSUE THREAD

**Issue by kinrokinro** [spacemeshos/smapp#722]
Thats will be extremly short, but i guess you will understand my suggestion:
$ smapp --create-wallet --password 'foobar' - it will return a wallet address (i.e. 0xdeadbeef)
$ smapp --start-smashing --wallet 0xdeadbeef - will running a node with coinbase receiver as 0xdeadbeef

**Comment by avive** [comment]
Smapp is designed to be a GUI app - not a terminal one. It is better to add these feature requests as an sm-repl issue https://github.com/spacemeshos/smrepl - the reference Spacemesh terminal wallet and api client. Can you please do that?
