### ISSUE TITLE
Default port is wrong

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smapp#724]
https://github.com/spacemeshos/smapp/blob/9e854387701f859e878e1ecea3b5d5538acee373/desktop/NodeManager.ts#L21

This should match the setting in go-spacemesh (7513):

https://github.com/spacemeshos/go-spacemesh/blob/972c550f045b48c95bb1590e4b3d8408155b375c/p2p/config/config.go#L20

Or, better yet, don't include any default, and somehow get it from the running node.

**Comment by IlyaVi** [comment]
closing as outdated - no hardcoded tcp port in smapp
