### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by andreivcodes** [spacemeshos/smapp#729]
Hello,

Can we please have build instructions on the main readme? yarn install / yarn package won't do it.

First of all, there seems to be a problem with webpack at 

https://github.com/spacemeshos/smapp/blob/7724ff06adb8c5b39368224009354ceadbfaaeaa/configs/webpack.config.main.prod.babel.js#L23

I believe it should be `./desktop` instead of `../desktop`

Second, even if I fix that, I can't package

`orphanStack: 'Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.\n' +
  `

I believe I'm missing some dependencies I am not aware of.

Thank you!

**Comment by IlyaVi** [comment]
If you want to build from source you should use master branch with npm
Develop branch is WIP of application 2.0 and it's not usable or packable
