### ISSUE TITLE
Node and API Error Handling

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#739]
Node errors should include:
1. Errors reported by the node api.
1. A non-responsive node api - smapp can't get response from api calls to node after few attempts.
1. Node process panicked.

All of these kind of node errors must be displayed in this screen. For non-responsive ai and node panic, always give the user the option to restart the node. For node errors, only enable restart button if error is critical and reported that a restart is required.

When a node error occurs:

1. Display node errors in the new network screen.
1. Enable restart node button on critical node errors reported by the api (all panics should be reported) 
1. Restart node when user clicks on `restart node` button.

The network screen visual mocks consider all of the above.

![node_error](https://user-images.githubusercontent.com/96002/125414113-b9bcc05b-465f-4327-a562-365499adda57.png)

This feature is one of the most important smapp features while the node is in beta. We know that user hate it when smapp stops working and 1. they don't know why. 2. they don't know how to recover smapp from the node error.

**Comment by avive** [comment]
We need to remember to handle 2 types of critical node errors as currently implemented in the node:
1. Errors reported via the errors streams (which might include errors that panic the node after being reported).
2. Node panics which are not reported in the errors stream.

Both cases should be handled in the same way as described in this issue.

**Comment by avive** [comment]
Updated issue description to consider 3 types of node errors that we need to deal with.

**Comment by avive** [comment]
In terms of all smapp issues for the July 5th sprint - this is one of the most important ones in terms of impact on the user experience. Should be high-priority.

**Comment by brusherru** [comment]
@avive should we notify the User about non-critical errors (level less than `dpanic = 5`)?

**Comment by avive** [comment]
I don't think so. If a node error is not critical then it means that basically the node keeps functioning and doesn't need user restarted. We should log these in the app log. 

I hope that you are seeing a descriptive short error description for critical node errors to display in the network screen. If not, please let me know so we can file node issues for these.
