### ISSUE TITLE
Dev mode net config

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#756]
I think it will be useful if smapp can be started in dev mode with an url of a config file for a network that doesn't come from the discovery service so we can keep testing it while the open testnet is having issues by easily switching over to a devnet. The original design was that all long-running networks will be provided via the discovery service and smapp user being able to chose from one of the available network, but we only manage to implement one network at a time via it for now so this change is needed.

For example, current devnet config file url: `https://storage.googleapis.com/spacecraft-data/mininet-archive/config.json`. I'd like to be able to start smapp dev build and having it use the config file from this url instead of the one from the discovery service.

**Comment by IlyaVi** [comment]
Add DEV_NET_URL entry to .env file to work against devnet
