### ISSUE TITLE
Inconsistent SYNCED status

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#765]
Here are the screenshot explaining the issue:
![image](https://user-images.githubusercontent.com/1897530/126143991-e76c4557-98da-48fa-8cad-8abaa891ea6f.png)

- A yellow bulb next to the "NETWORK" link on the top are still yellow
- Meanwhile, the network screen says that status is synced (bulb are green)
- But verified and synced layers are not equal to the top layer and to each other

I'm expecting that the color of the bulb on the top and in the network screen should be the same.
I suspect that in fact the status is not synced, especially since the Node itself gives the `isSynced ' flag, which is false for such values.

If so, we had to replace some custom logic in the `NetworkStatus` component:
```
const getSyncLabelPercentage = (): number => {
    if (status && status.syncedLayer && status.topLayer) {
      return Math.round((status.syncedLayer * 100) / status.topLayer);
    }
    return 0;
  };
...
{progress >= 100 ? (
          <>
            <NetworkIndicator color={smColors.green} />
            <ProgressLabel>synced</ProgressLabel>
          </>
        ) : (...);
```
with just looking for the `isSynced` flag.

Am I right?

**Comment by avive** [comment]
I'm not sure about the code itself but definitions-wise, both traffic-lights/bulbs should aways be the same color. The idea of the bulb on the top is to let the user know about sync status without accessing the network screen.  The status should be orange if the node api  returns `synced:false`, green if returns true and red if the there was a critical node error that requires user to restart the node via the `restart node` button on the network screen (this includes node api not being available and not reporting status).

Note: Verified layer number should not affect the sync status.  Also the check currentLayer / topLayer should not be used as the node has a notion of isSynced which may change from false to true after the currentLayer is equal to the topLayer.

**Comment by brusherru** [comment]
Yep. So we should show the green bulb and "SYNCED" message in the Network screen only if the Node sends the status with the `isSynced: true`. It's a quick fix.
However, I'm still waiting to get a fully synced state and it seems like the top layer updates, but `syncedLayer` and `verifiedLayers` keep the same. Just want to ensure that this may happen at all :)

**Comment by avive** [comment]
In the current testnet, the node keeps going in and out of sync so it is actually a good api server to test this feature with :-)
If you keep getting issues from the public testnet you should consider moving to the devnet. Did you add the feature to use a custom config file to smapp? It enables this kind of configuration...

**Comment by avive** [comment]
Also making sure that smapp subscribes on NodeService:: StatusStream() and doesn't only require polling after calling Status() once in a new app session.
