### ISSUE TITLE
Display node info in settings screen

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#771]
Display Node Build and Version data items in settings.

![Screen Shot 2021-07-21 at 11 41 42 AM](https://user-images.githubusercontent.com/96002/126459113-90da43e5-f24b-4c03-b71e-b7dfe7b9ca3d.png)

**Comment by brusherru** [comment]
@avive looks like this are not actual.
I've already touched some parts of code related to it: https://github.com/spacemeshos/smapp/pull/764/files#diff-0e9c78b6209a81be37df60ca8f7b90f25717ad80685e4de9c5f5337a64758205R172
And it seems like it works right now. Please, check it out (on the develop branch) and if this one is still actual, provide the Node version.

**Comment by avive** [comment]
Checking on dev now.

**Comment by avive** [comment]
Looks like it is working okay in develop branch.
