### ISSUE TITLE
Current screen indicator in main nav bar

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#773]
Repro:
1. Navigate to the wallet screen - notice wallet command in top nav bar is selected.
2. click on `all transactions`.
Result: Top nav bar wallet command is deselected.
Expected: Wallet command to keep being selected as the transaction log is in the wallet. 
3. Go back to wallet screen.
Result: wallet command is not selected in nav bar.
Expected: wallet command to remain selected.

**Comment by brusherru** [comment]
I've already caught the same one when opens SMESHER -> SETUP (screen where you can choose a folder) and then click on "SKIP" button.
It is one of the problems with `react-router`.
Will try to handle it or force to switch to `react-redux-router` or something similar.

**Comment by avive** [comment]
`react-router := the root of all evil 🤣`

**Comment by brusherru** [comment]
Closed by #800
