### ISSUE TITLE
Input Focus for Screens with text boxes

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#779]
All screens which include a text input box, such as enter new password or enter wallet password should set the text input focus to the first text box on the screen, so user doesn't have to click on it in order to enter text. 

Some screens have this feature, some don't.  For example, set wallet password doesn't but login with password does. 
Another example - send transaction screen - input focus should go to the `To` input field.

**Comment by brusherru** [comment]
Closed by #800
