### ISSUE TITLE
Improve waiting for api provider user experience

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#784]
# Motivation
Improve the user experience when smapp is trying to connect to node api (local node or remote api provider).

# Changes

Add a message below the spinning wait animation:
- When working with local node api provider: `Please wait, starting up Spacemesh node...`
- When working with remote api provider: `Please wait, connecting to Spacemesh api...`.

Current screen:

![Screen Shot 2021-07-25 at 11 33 30 AM](https://user-images.githubusercontent.com/96002/126892967-80e0f04c-ec1c-4574-b3f7-c2f3beb6d548.png)

@vomcent - please provide updated visual design in Figma and assign back to me when done.

**Comment by vomcent** [comment]
Figma links for each screen:
[Spacemesh Node](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=8758%3A37161)
[Spacemesh API](https://www.figma.com/file/6bbFkIAzVu36bIpUNnMqoy/Smapp-Designs?node-id=8758%3A37368)
