### ISSUE TITLE
Don't block startup on provider api availability

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#785]
Smapp should not block on starutp with the loading modal screen until the api is available from the current api provider (local node or remote api). 

It should load using cached data for the unlocked wallet and display any locally cached data it has while it attempts to check api health in the background.

The app should periodically check for api health in the background and if api is not available after several attempts then it should display an error in the network screen and if the provider is a local node, present and enable the restart node button.

When a user clicks on a button that triggers a command that requires api usage and the api is not available, Smapp should display a modal error regarding no available api and not try to execute the operation that requires an api method.

The number of attempts and the period duration for the health check should be app constants and should be set to consider up to 1 minute of api being unavailable from local node due to slow warmup.

**Comment by avive** [comment]
This is for long-term smapp 0.3 discussion notes and not for 0.2 - should be be built until proper discussion in smapp team.

**Comment by avive** [comment]
@brusherru - what's been implemented as of v0.2.3 of the above requirements?

**Comment by brusherru** [comment]
First two paragraphs still not implemented yet. However, in case if no network / api is available we can skip it without any additional waiting time.
Implementing it should not be a complicated but most likely it will require some refactoring.

So it is almost implemented, but we are still waiting until the node will response successfully on echo message via GRPC on a startup, and then show a next screen after it. We have to get eid of it, show next screen asap, and ensure that there are no racing cases (refactor if needed).

**Comment by brusherru** [comment]
Not actual. We're not blocking anymore :)
