### ISSUE TITLE
Improve node is down error message

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#791]
1. Start Smapp with a managed node.
2. Kill node process via OS.
3. Navigate to the network screen.

Result: 

Error message is `CONNECTION DROPPED`.

Expected:

A more descriptive sentence. e.g. `Can't connect to the managed node`.

Generally speaking, user-facing error messages should be complete and descriptive english sentences.

**Comment by brusherru** [comment]
We've discussed the error message for such cases should be:
"The Spacemesh node software has unexpectedly quit. Click on 'restart node' to start it."
Is it still actual?

**Comment by brusherru** [comment]
Closed by #800
