### ISSUE TITLE
macOS small  app icon is missing

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#802]
This has been with us for a while.
Add missing small icon in macOS builds.

![Screen Shot 2021-08-19 at 4 44 00 PM](https://user-images.githubusercontent.com/96002/130079442-0044e5b1-6278-46d8-8e97-7e09f218b687.png)

**Comment by brusherru** [comment]
@avive 
The icon set is generated from `icon.png`, so actually, it has all sizes.
I can't reproduce the icon corruption on my machine.

Can you provide more information:
- MacOS version
- Smapp version

It will be handy if you also can attach the generated icons file, which can be found here: `/Applications/Spacemesh.app/Contents/Resources/Spacemesh.icns`

**Comment by avive** [comment]
[Spacemesh.icns.zip](https://github.com/spacemeshos/smapp/files/7039248/Spacemesh.icns.zip) - it looks fine.
My macOS is 11.5.1 but this has been an issue at least in last 2 macOS releases.
