### ISSUE TITLE
Save selected theme between App sessions

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#806]
At the moment we have two themes in the App: light and dark theme. But there will be the third one in the nearest future.

On the App start, it uses `electron.nativeTheme.shouldUseDarkColors` to determine which theme to use. Then the User can switch the theme on the Settings screen. However, selecting another theme is not saved in the persistent store. So on the next App start, the User gets the default theme for his OS.

We need to save the selection to the persistent store and use this value. But in case that store does not contain a selected theme — use the default provided by `electron.nativeTheme.shouldUseDarkColors`.

Feel free to refactor code related to the persistent store.
If you have an idea of how to make a robust and maintainable code — do it. But if it requires a lot of refactoring, please, propose the solution in the comments below first.

### User Story
1. User runs Smapp for the first time on MacOS with the dark theme
2. Smapp opens with the dark theme
3. User opens Settings screen and switches to the light one
4. User closes Smapp
5. User opens Smapp again and see that the Smapp opened with the light theme

**Comment by maparr** [comment]
The issue is not relevant anymore. We are using storage for the selected theme.
