### ISSUE TITLE
Get rid of blinking on Node screen while progress updates

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#812]
### Environment
* Smapp version: https://github.com/spacemeshos/smapp/tree/post-gpu-setup

### Describe the bug
When Smapp creates PoS data and notifies GUI about its' progress, the whole Node screen blinks.

### Steps to reproduce
1.  Run Smapp (with working gpu-post)
2.  Start Smeshing with a big enough PoS data size to have time to check it out (E.G. >=4MB)
3.  See on Node screen

### Expected behavior
Progress updates. Nothing blinks, twitches and etc.

### Actual behavior
Progress updates, but the whole screen component blinks.

**Comment by avive** [comment]
@brusherru is this fixed or still an open issue?

**Comment by brusherru** [comment]
I have to check it, but I'm pretty sure that this is still actual. I didn't optimized rendering of that screen and components inside.

**Comment by maparr** [comment]
hi @brusherru , will take this issue for work.

**Comment by maparr** [comment]
@brusherru , right now cannot reproduce this issue, the Node screen is not blinking, can we close this issue?
