### ISSUE TITLE
Store Smesher log on fs

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#813]
### Rationale
The smesher log should show relevant log messages, such as:
- start time
- pause/resume events
- rewards
- errors

Most of these events can't be retrieved from the Node by the current GRPC API and maybe never will be.
Smapp should create the log on his own and keep it actual.
In case post data deletion or changing Smesher ID the log should be dropped.
In other cases, it should be updated with proper messages.

### User story
- [ ] Run Smapp
- [ ] Setup smeshing
- [ ] The log should have a message with time when the creation of Pos data started
- [ ] Then there should be a message when it is done and started smeshing
- [ ] If User paused/resumed smeshing it should be there
- [ ] If some error occurred in the Smeshing process, it should be there
- [ ] If User got a reward for smeshing — it should be there
- [ ] If the User cleaned up all app data on his PC and runs Smapp (from scratch) — the log should be empty (@avive ?)
- [ ] If the User removed only `key.bin` file — the log should be empty (@avive ?)

### Acceptance criteria
- [ ] The smesher log should be stored in the persistent store
- [ ] The log should be updated by the main process (not components)

### Out of scope
Encryption of the log. Probably we don't need it all, since we're not encrypting `smesher-coinbase` in the `node-config.json`.

### How to implement
- Store the log file on fs, instead of localStorage
- Manipulate the log file from the separate service (`SmesherLogService`)
- `SmesherManager` is a consumer of `SmesherLogService`
- `SmesherManager` will put the log through IPC

### How to test
We can test `SmesherLogService` for:
- it adds lines to the log,
- read the log,
- cleans it up if needed.

**Comment by avive** [comment]
Low-priority feature which is a left-over from an old design.

**Comment by avive** [comment]
I still think we shouldn't build this feature in Smapp yet. I think it is much more important to allow users to submit an error report that will include the node and smapp logs as uploads. We should compress the huge node logs file before uploading and have a centralized place to review such errors and logs. Upload should include all the info needed for debugging - @brusherru - the things you've been asking in bug reports... It is hard for users to provide all of these files but easy via an auto-upload of these files per error report once we'll automate this...

**Comment by avive** [comment]
I think that this log should go into the Smapp log file and that we should add some of the info you include in the issue in a more concise way to users in the smesher screen.

**Comment by brusherru** [comment]
Smesher log is back and it changed a look: https://github.com/spacemeshos/smapp/pull/925
But implementing of proper smesher log (and logging rewards as well) is still actual.

**Comment by brusherru** [comment]
Not actual anymore.
