### ISSUE TITLE
Error setting up post

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#815]
### Environment

* Smapp version: dev build from https://github.com/spacemeshos/smapp/pull/810#issuecomment-939204083
* OS: macOS 11.6 / M1
 
### Describe the bug
Error setting up post.

### Steps to reproduce

1. Fresh install (no local data), proceed to setup post.
2. Select post directory and click `next`

### Expected behavior
Be able to resume post setup.

### Actual behavior

![Screen Shot 2021-10-09 at 9 15 26 AM](https://user-images.githubusercontent.com/96002/136646638-de681ce6-8484-4f4e-9d31-10e1e747aef6.png)

Tried with several different dirs.

**Comment by avive** [comment]
Occasionally I get this error on startup of first session on a machine w/o local data:
<img width="684" alt="Screen Shot 2021-10-10 at 10 25 53 AM" src="https://user-images.githubusercontent.com/96002/136686732-d500e275-afeb-4686-8e8f-bba6b5f26481.png">

**Comment by avive** [comment]
I haven't seen this issue in beta0 yet - it might not be reproducible anymore.

**Comment by brusherru** [comment]
Confirm. It looks outdated and these bugs are not reproducible.
If someone will catch some of it — please, feel free to reopen an issue (or create a new one) and provide logs, steps to reproduce and etc
