### ISSUE TITLE
Expected gpu provider not available

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#820]
### Environment

* Smapp version: https://storage.googleapis.com/smapp/pr-c57e2c9c64e347300d782d9a9d24f59298caa3bd/Spacemesh-0.1.2.dmg
#810 
* OS:  macOS High 11.6, Mac Mini M1, 16GB.

### Describe the bug

No gpu provider for M1 gpu.

### Steps to reproduce
1. Clean install on a machine w/o prior spacemesh data.
2. Proceed to setup wallet and smeshing.

### Expected behavior
GPU provider for M1 to be displayed in pos processor screen.

### Actual behavior
Only cpu provider is displayed. 

### Notes
It looks like go-sm node is able to load the lib dynamically because user can create post. Perhaps it is an issue with the Vulkan runtime config? We don't have this issue in Linux and Windows (at least for CUDA gpus systems) - builds of the same release.

@moshababo @brusherru @sudachen

**Comment by brusherru** [comment]
@sudachen @moshababo
I've found a quick solution: specifying node directory to `cwd` for spawn go-sm process does the work.
So we don't need further investigation. Probably when we'll have more time we can experiment with the "recommended" solutions (E.G. use paths where Vulkan should search for icd by default, but I tested it and it doesn't work for me).
