### ISSUE TITLE
Handle errors of fetching discovery and network configs

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#822]
### Environment

* Smapp version: develop

### Describe the bug

In case if discovery URL or network config URL is not responding or returns a wrong response, the Smapp should show a proper error message to the User and ask to retry (or fallback to something?)

### Steps to reproduce
Clean-up is not required.

1. Turn off the internet (or set `DEV_NET_URL=http://some.non.existing.url/`)
2. Start Smapp

### Expected behavior
The Smapp should show one of the error messages:
- Check your internet connection
- Can not connect to the discovery service
- Can not retrieve network config

### Actual behavior
The app throws an error `No handler registered for 'W_M_READ_WALLET_FILES'` because the main process crashed before and as a consequence, no Services have been started.

### How to fix
Refactor code related to fetching discovery config and network config (in `main.dev.ts`) in a separate function which will handle these errors properly and return either resolved Promise with configs or rejected with the error message, that should be shown to the User.

--
@avive please take a look. Probably you have another vision of how to make UX of this thing better.

**Comment by avive** [comment]
It is fine for this release to have one modal error dialog box in all error cases (Internet down, Spacemesh discovery service is down or network config file not available on its expected url) with the following copy.

Title: `Something Went Wrong`
Body: `Can't download network configuration. Check your Internet connection and click 'retry' to try again.`
Button at bottom: [Quit] [Retry]


We don't need to worry about a fallback for now. Maybe will add it in the future as an enhancement.
