### ISSUE TITLE
Missing transaction from log in wallet-only mode

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#842]
## Environment

* Smapp version: 0.2.0.beta0

## Rerpo Steps
- Setup smapp in wallet-only mode on devnet210 network.
- Send a transaction from another node to the new wallet's account and wait for it to confirm.

## Behavior
Balance is updated with the tx amount as expected, but the transaction is not listed in the transactions logs or in the transactions summary in the wallet screen.

## Expected 
The transaction should be listed for the wallet in the app.

**Comment by brusherru** [comment]
Can't reproduce it 🤔 
![image](https://user-images.githubusercontent.com/1897530/146772294-758177e1-90f3-4284-b995-4f1f87e73c12.png)

**Comment by brusherru** [comment]
On the second app session, it doesn't appear as well?
I've got it right via GRPC stream, but probably you caught up some issue with streams, so on the second session you definitely should see this transaction in the log, I hope :)
Also, please try to reproduce the bug

**Comment by avive** [comment]
Not reproducible on k-6 - it was on devnet210. I will re-open if I see this again in beta1.
