### ISSUE TITLE
I cant get my smh

### ISSUE THREAD

**Issue by qingrong123** [spacemeshos/smapp#848]
### Environment

* Smapp version: 0.xx.x | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04

### Steps to reproduce

Try to narrow down your scenario to a minimal working/failing example. That is, if you have a big program causing a problem, start with deleting parts not relevant to the issue and observing the result: is the problem still there? Repeat until you get the most straightforward sequence of steps to reproduce the problem without any noise surrounding it.

1.  Open this
2.  Press that
3.  Click here and there

### Expected behavior

What should happen?

### Actual behavior

What’s happening now?

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by brusherru** [comment]
@qingrong123 please provide all the required information for the bug report. Otherwise, we will close the issue soon due to the lack of details.
Also, please, share your account address, so we can check the transactions and rewards history in the network.

**Comment by qingrong123** [comment]
Thank you, I have already solved the problem
My address is 0xbf4847999b7202e984f0b42700d8f5f1adcf1f93




| |
黄青容
|
|
***@***.***
|
On 12/29/2021 17:19，Kirill ***@***.***> 0xbf4847999b7202e984f0b42700d8f5f1adcf1f93wrote：

@qingrong123 please provide all the required information for the bug report. Otherwise, we will close the issue soon due to the lack of details.
Also, please, share your account address, so we can check the transactions and rewards history in the network.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brusherru** [comment]
@qingrong123 ok, I'm closing the issue now.
However, if it was something unexpected and you think it is a bug, we will appreciate it if you post details, so we can make Smapp work better.
Anyway, thanks for participating in the Spacemesh test network.
