### ISSUE TITLE
UI doesn't start on failure to fetch networks

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/smapp#856]
### Environment

* Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-62-generic x86_64)

### Describe the bug

SMapp UI is not loading

![image](https://user-images.githubusercontent.com/21037839/150139480-84ef3fcb-b5cb-4d84-9f62-a10d0883e684.png)

### Steps to reproduce

Waiting to see what did user run
User tries to run it from VPS and from terminal

**Comment by Mus156** [comment]
I had this problem. After starting the network, everything worked. Apparently the problem appears when the network is down.

**Comment by brusherru** [comment]
@Mus156 you're right.
The Smapp counts that the discovery service is always available and has at least one network listed there. As a consequence, Smapp can't run in a normal way without at least one available network.
But I have good news! My PR #862 fixes it and makes it possible to run Smapp when retrieving networks from discovery service fails for any reason.

@antonlerner @Mus156 thanks for the report!
