### ISSUE TITLE
when first installing SMapp, it cannot connect to node

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/smapp#866]
### Environment

* Smapp version: 2.1.0-beta
Os: Mac Mojave

### Describe the bug
<img width="1437" alt="Screen Shot 2022-02-10 at 16 29 42" src="https://user-images.githubusercontent.com/21037839/153428688-fd29bb2f-376c-473b-8f4a-8013af403e44.png">

[app-logs.txt](https://github.com/spacemeshos/smapp/files/8041818/app-logs.txt)

node logs seems to be fine, no panics
### Steps to reproduce

install the node and follow instructions

**Comment by antonlerner** [comment]
seems like an incorrect flow, POST should be allowed to be crated while node is syncing, users can't advance from this stage until node is synced and having the node not synced blocks the flow of onboarding

**Comment by avive** [comment]
@brusherru  Smapp should allow creation of POSTs without the node being synced but the node's api obviously needs to be available. Node must be synced to create the first ATX. @noamnelke

**Comment by noamnelke** [comment]
If the node doesn't behave as expected - we need to figure out why. Can you distill the logs that Anton attached and tell me exactly what the unexpected behavior is?

**Comment by avive** [comment]
@antonlerner - I'm testing now with Smapp v0.2.3 - you can create POST before the node is synced. The issue you have been seeing is likely the node being down and api unavailable. When the node is syncing the status street-light is orange. When node (or api) is down - network status is red like in the screen shot you have shared. Please try to repro again with current devnet and smapp release.
