### ISSUE TITLE
Change temporary key derivation function with new one

### ISSUE THREAD

**Issue by IlyaVi** [spacemeshos/smapp#88]
Expose it through WASM, update WASM repo and Wallet app

**Comment by IlyaVi** [comment]
Expose it through WASM, update WASM repo and Wallet app

**Comment by avive** [comment]
@IlyaVi - isn't this done?

**Comment by avive** [comment]
@IlyaVi - is this still an open issue?

**Comment by IlyaVi** [comment]
can be closed, Barak approved existing derivation function some time ago
