### ISSUE TITLE
Can not setup a new wallet: it's impossible to select a spacemesh network

### ISSUE THREAD

**Issue by DarthVanger** [spacemeshos/smapp#880]
### Environment

* Smapp version: 0.2.1-beta.2
* Node version: I can't find the "settings" screen to see the node version.
* OS: macOS Catalina (10.15.7)

### Describe the bug

When setting up a new wallet, on the "Select Network" step the dropdown is empty and nothing happens when I click it. It is impossible to proceed with the setup, as the "Next" button doesn't work.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6686679/159588472-7b4367cd-61f7-47f4-aca7-0115cf29157e.png">

### Steps to reproduce

1.  Open spacemesh app (fresh install, new user).
2.  Click "Setup"
3. Click "Wallet + Node"
4. Click "Standard wallet"
5. Click the dropdown to select network (nothing happens).
6. Click the "Next" button (nothing happens, so it's impossible to proceed with the setup).

### Expected behavior
The dropdown should open and allow to choose a network.
Also testnet being preselected would be nice.

It should be possible to go the next step by clicking on the "Next" button.

### Actual behavior
The network selection element is empty (no network is selected).
Clicking it doesn't do anything (nothing happens, no dropdown shown).

Clicking the "Next" button also doesn't do anything.
It's impossible to proceed with the setup.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/6686679/159588472-7b4367cd-61f7-47f4-aca7-0115cf29157e.png">

### Logs

>Attach `app-logs.txt` and `spacemesh-log.txt`

I couldn't find no logs on my mac:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/6686679/159587891-e4a5668b-8ed8-40b8-8325-0b3af289a549.png">
(both of the `000003.log` files are empty)

**Comment by brusherru** [comment]
Thanks for the report!

The reason that right now there is no available networks on [discovery service](https://discover.spacemesh.io/networks.json ). If you update to the latest Smapp (0.2.2) you'll see a reasonable message inside the dropdown and SKIP button that will run Smapp without connecting to any network (pretty useless). 😃
