### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#882]
### Rationale

We'd like to enable user to submit an error report and collect these on one of our servers.

### Requirements
- Error report should always include all log and config files used by smapp, including the currently used node config file.
- Logs should be compressed prior to uploading
- User should be able to input a short error description or issue before submitting.
- Ideally report will include a screen shot of Smapp main window at time of the report.
- There should be a clear 'submit error' button on the main window so it is always visible. @vomcent - please provide some design options. Clicking it should display a modal Error Reporta dialog box.
- Clicking on submit should close the dialog box and start uploading the report's data.
- Smapp should display the report uploading status. e.g. submitting... and remove the status when the report has been submitted.
- If node crashes while Smapp is open - it should display an error report dialog allowing the user to send the error report about that crash.

**Comment by maparr** [comment]
Hi @avive, after researching for this improvement I found a few ways how we can implement this.
1. we can add crash UI dialog with a client and as u described, all these features with custom API calls, logging, etc.
2. we can add [sentry](https://sentry.io/for/electron/) to catch these issues in the background.

In case of custom implementation, in this case:
- custom implementation, means support on API level and open API  that have to block DDOS and other attacks
- the work with the number of files 
- add server/release configuration before starting on this way, collect it before the app launch ( based on the system we can fail low-level cases )
-  only during some amount of time preparing a stable version
- in case of a crush ( it should display an error report dialog allowing the user to send the error report about that crash ), we have to make additional dialog like on macOS/windows that do mean not something interesting for the end client. He expects a working and stable app, he doesn't want to work on our app, only use it.

In case of sentry implementation
-  we have stack trace/platform logs, without dialogs
- we can send additional information/logging for the application, to track steps, that were before the issue. Have to be separated, but we can provide id's of pages and track, how clients use our app for steps to reproduce ( not only log files that we have right now )
- API for logs on their side 
- track performance issues 
- sure easy to implement/use 
- cost around 25$ per month in case clean-up logs. 

if we decide to use sentry, for user feedback we can add, first of all, the tracking, and add a button with a title report about an issue, but without a dialog, just to track how many clients using this button, and enable it through a/b testing, show to not 100% clients. In case of failure, we will remove the button, in case of success will provide the dialog. In the dialog they need to describe steps to reproduce, better to add a help icon or so, where a client can click and say, hey I have an issue with this feature, I don't understand how to open the wallet or so, and we will be tracked through the sentry steps to reproduce and what client don't understand and want to know. It's more about client feedback that we can provide, but still working solutions from my perspective.

**Comment by avive** [comment]
Sentry looks like a good first option to try. Cost is reasonable as well. If we observe that they have production bugs that block us and in the case that they don't fix them quickly enough, then we can always switch to our own custom implementation.

**Comment by maparr** [comment]
Sentry integration definition of done: 
- [x] sentry account was created for our team
- [x] connect Sentry to Electron via SDK
- [x] cover main screens with route detection, check the integration
- [x] test stack trace and client platform information
- [x] add Slack alerts integration
- [x] add GitHub integration with commits and auto-assign 
- [x] add build version integration with sentry 
- [x] separate UI and Backend errors

**Comment by maparr** [comment]
#893
