### ISSUE TITLE
Smapp gets stuck on unlocking wallet file, which points to non-existent network

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#885]
### Environment
* Smapp version: 0.2.3

### Describe the bug
When User updates Smapp to 0.2.3 and tries to unlock his old wallet file (which points on non-existent network) Smapp will stuck on the loading screen. After restart of Smapp (or creating a new wallet file) it works fine.

### Steps to reproduce
1. Change `netId` in the wallet file to non-existent one (aka `200`)
2. Run Smapp, type password
3. Choose an available network

### Expected behavior
Smapp shows a wallet screen after a couple of seconds of spinning logo.

### Actual behavior
Logo spins forever.

**Comment by avive** [comment]
I have experienced this issue yesterday when testing 0.2.3 as well.
