### ISSUE TITLE
POST setup improvement

### ISSUE THREAD

**Issue by avive** [spacemeshos/smapp#890]
### Rationale

Make it easier to setup post.

### User story

User wants to setup post. He gets to the processor screen and is presented with 1 or more processors. Smapp should automatically select the processor with the fastest hashes per seconds - there's always 1 processor like this, in the worse case it is the CPU processor. By implementing this enhancement we will save many users 1-click in the process because next will be enabled and some/most users can just click it without having to think about which processor to select or just click on the cpu processor in the worse case.

**Comment by oriya** [comment]
FYI
-
SMAPP does select something by default, yet it isn't clear to end user. First the wording instructs to select something. Second, the default selection isn't clear, unless you know the color scheme - that white means "selected". I suggest that we make it clear by
- 1. Change the wording to say, your fastest GPU is chosen by default, feel free to change it
- 2. Add a "check / selected icon" to the selected GPU so it is clear that user can just click on next without doing anything.

**Comment by avive** [comment]
@vomcent what do you think about Oriya's ideas?

**Comment by avive** [comment]
> SMAPP does select something by default, yet it isn't clear to end user. First the wording instructs to select something. Second, the default selection isn't clear, unless you know the color scheme - that white means "selected". I suggest that we make it clear by

In the current build I'm testing, next button is disabled and smapp doesn't select a processor by default - they are all grey... maybe it was fixed in the devnet build you are using. @brusherru ?

![Screen Shot 2022-04-15 at 10 45 34 AM](https://user-images.githubusercontent.com/96002/163541458-70f4a8c3-1f35-4d6a-ae6c-b049d0e95043.png)

**Comment by oriya** [comment]
I'll double-check again. Regardless, your original suggestion to make the fastest be selected by default (making it clear that is it selected) alongside  some text changes is appropriate and would make it smoother for your everyday SMAPPer.

**Comment by brusherru** [comment]
Nope, by default, nothing is chosen. I'll tweak it.

Regarding selection/icons — when you have only two options it is always hard to understand which one is chosen if only you don't see a familiar GUI (like a radio button or iOS switch). But I'm not sure that additional icon will fit well here, and actually, I think it is some kind of visual garbage :)

So I propose 
- choose fastest by default,
-rewording the sentence "Select a supported processor for creating proof of space. The fastest one is chosen by default."
😈

**Comment by oriya** [comment]
I like 👽

Maybe highlight 

**The fastest one is chosen by default**

**Comment by oriya** [comment]
Maybe highlight **The fastest one is chosen by default**
