### ISSUE TITLE
The password request upon wallet opening (Windows/Linux/MacOS)

### ISSUE THREAD

**Issue by Stizerg** [spacemeshos/smapp#906]
Currently the user have to enter the password at the smapp start (for Windows, not sure about other platforms).
Smeshing/Sync doesn't start until user enters correct password.
It prevents unattended smeshing (automatic smeshing start after Windows loads).

### Acceptance criteria

Smapp should start without the password prompt
Smeshing / Sync should start automatically after smapp loads
The user should be asked for the password after the click on the wallet tab for the first time (or the click on any tab other then 'Network')

**Comment by avive** [comment]
I assume you mean that smeshing/sync will start only if the current wallet that the user is prompted to open is configured to run with local node? Smeshing/sync and local node startup should not happen if the wallet was last used with a public sm api provider....

**Comment by Stizerg** [comment]
Obviously the wallet have to be configured before as default destination for smeshing rewards.
Is there anything that prevents sync without configured wallet?

**Comment by brusherru** [comment]
@Stizerg thanks for the report.
I think I understand the pain and we really should tweak it.

User Story:
1. User opens Smapp, creates wallet (running local note), syncing, and also started smeshing...
2. User also turns on autostart of Smapp.
3. Then User rebooted OS

Expected:
- Smapp should continue syncing and smeshing on startup without any questions.
- So User may forget about it until he wants to check the balance or send some SMH.

Actual:
- Smapp autostarted, but it does nothing until the User will type the password.

From the technical side:
- If the User runs the local node in the previous App session — then Smapp should start the Node using the same node-config and arguments on Smapp startup.

@Stizerg am I understood it right?

**Comment by avive** [comment]
It should def work this way - we had an old issue about it but I guess it was lost...

**Comment by Stizerg** [comment]
Yes, that's all correct @brusherru 
Thanks

**Comment by maparr** [comment]
Seems #785 is relevant to this issue, will check on the investigation step.
