### ISSUE TITLE
Doesn't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by dimisjim** [spacemeshos/smapp#909]
### Environment

Ubuntu 22.04 latest

### Describe the bug

The app fails to startup on a standard ubuntu 22.04 installation

**Comment by maparr** [comment]
Hi @dimisjim , thank u for the report. Can u inform me, which app version do u tried to install?

**Comment by dimisjim** [comment]
latest one, 0.2.5

**Comment by brusherru** [comment]
@dimisjim thanks for the report.

It will be very helpful if you can provide some additional information:
1. Could you attach a log file: `~/.config/Spacemesh/app-logs.txt`?
2. Try to run it from the terminal — some uncaught errors might be printed. Please, share if there are some.

**Comment by dimisjim** [comment]
Hey @brusherru 

Sure, this is what I am getting when trying from a terminal:
```
➜ /opt/Spacemesh/spacemesh_app                                                                         [26/05 | 9:54am]
(node:7981) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:7981) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[7981:0526/095735.998195:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Failed to generate minidump.[1]    7981 illegal hardware instruction (core dumped)  /opt/Spacemesh/spacemesh_app
```

The crash report shows these logs too:
![image](https://user-images.githubusercontent.com/6890249/170444986-bc718aeb-9c3d-45ae-93c2-01c956858ec2.png)

It seems to be a graphics problem

**Comment by dimisjim** [comment]
I can confirm that 0.2.8 works

**Comment by maparr** [comment]
@dimisjim , thank you for ur report and the confirmation!
