### ISSUE TITLE
Integrate a Storybook for our components.

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#917]
We have a lot of components that are not standardized for our pages and we have requested to refactor them, to make them smaller and more useful. 
I'm proposing to add [Storybook](https://storybook.js.org) and integrate it into our app.

Before starting to refactor dropdowns or text components that we copy-pasting, it's better to summarize where and which functional components, with different styles we have in our system. After this task, we can start to work on refactoring and scaling our components.

**Comment by maparr** [comment]
hey @brusherru , what do u think about this step?

**Comment by avive** [comment]
It is a great idea - it should be the next version of the UK Kit Figma page with the reference controls design for the 3 skins
