### ISSUE TITLE
Fix displaying rewards in transactions log

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#932]
### Environment
* Smapp version: 0.2.6

### Describe the bug
As a Smesher, I can see my rewards on the Smesher screen and see my positive balance on the Wallet screen. But there are no rewards in the log on the Wallet screen. Previously, it worked and it also stored transactions and rewards on fs.
The transactions log still working.

**The main question: do we want to show two different logs of the same data?**
If yes — then, we should fix it.

### Steps to reproduce
Sync the node and get some rewards. Then check out Smesher and Wallet screens.

### Expected behavior
The smesher screen and Transactions log show up the same list of rewards.

### Actual behavior
Smesher screen displays rewards, transactions log shows only common transactions.

**Comment by oriya** [comment]
At first glance, I would think that the transactions log should be specific to the wallet-activity and not earning rewards. 

Seeing why something has stopped working is always a good ideas, but I don't see a reason why we would list reward earnings in transactions log, now that we have that data on the smesher screen.
