### ISSUE TITLE
Create a proxy backend for api error integration

### ISSUE THREAD

**Issue by maparr** [spacemeshos/smapp#942]
We have to create a proxy API, to prevent attacks.
https://docs.sentry.io/platforms/javascript/guides/vue/troubleshooting/

**Comment by pigmej** [comment]
@maparr I think that belongs more to the Infra instead of here, isn't it?

**Comment by maparr** [comment]
@pigmej , yeah, you 're right.

**Comment by maparr** [comment]
move it to the infra side.
