### ISSUE TITLE
Fix navbar styles

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#963]
### Environment
* Smapp version: develop

### Describe the bug
<img width="510" alt="image" src="https://user-images.githubusercontent.com/1897530/187174220-4a4179ef-2688-41c6-b919-78ad605ce8c1.png">

I believe that only selected menu item should be colored in purple, other links should be white.

**Comment by tadeork** [comment]
Hey @brusherru, I think I can solve this. Could you assign to me this issue?
