### ISSUE TITLE
Add internal queue for outgoing transactions

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp#973]
### Rationale
Right now Users can send transactions only when Network is fully synced.
But sometimes the network proceeds one layer more and the local node requires some time to sync up to the latest one.
It causes the User can't send the transaction and have to wait for it.

So I have an idea to introduce an internal (in Smapp) queue for transactions, that will wait for syncing and then send the transaction if possible (projected balance is enough for tx) or show an error message. This feature should be turned on (that User can send the tx) only in cases when the network is just a couple of layers behind and the latest projected balance is enough for the transaction.

Besides this, we need to show up that Smapp has some outgoing transactions in the queue, to make it clear to the User and avoid sending the same tx a few times. Probably, we also need to count queued transactions in the latest known projected balance.

### User story
- [ ] Start Smapp, sync the node
- [ ] Wait until it became unsynced for 1-2 layers (or just turn off internet / Smapp for 1-2 minutes and then turn it on)
- [ ] Send the transaction without waiting to sync

### Acceptance criteria
- [ ] The basic scenario works as described
- [ ] Show up queued transactions in the log (and probably show some icon on every screen)
- [ ] When the User closes the Smapp with queued transactions — warn, that these transactions won't be sent and lost after restart.
- [ ] When a transaction is sent — notify the User about it (but we don't have a "global snack bar messages" so we need to decide how to do that)
- [ ] Projected balance should be corrected using the queued transactions
- [ ] Make it possible to cancel queued transactions

### Out of scope
- Saving queued transactions in the persistent store to make it possible to restart Smapp without losing this queue.
   Probably it is not only out of scope, but also we should not do that :)

**Comment by countvonzero** [comment]
> But sometimes the network proceeds one layer more and the local node requires some time to sync up to the latest one.

this doesn't sound right. the node has tolerance for falling out of sync (3 layers i think).

> introduce an internal (in Smapp) queue for transactions, that will wait for syncing and then send the transaction if possible 

assuming the node is not synced, is it easier to have the node relay the tx to other peers?

but on a more general level, it seems confusing for smapp to rely only on localnode to get information for the smesher account.
for example, the app was offline for a period of time and come online, it naturally need time to become synced.
but in order to see incoming funds to the smesher account when it's offline, it needs to wait for the node to become synced?
or am i completely wrong?

**Comment by brusherru** [comment]
> this doesn't sound right. the node has tolerance for falling out of sync (3 layers i think).

Alright, then we just need to ease it in Smapp :)
Right now UI does not allow sending a tx if GRPC API tells that node is not synced (we're looking at a boolean value, so it does not matter how many layers are ahead).

> assuming the node is not synced, is it easier to have the node relay the tx to other peers?

Sounds good to me. Do we already have it in the go-spacemesh?

> but in order to see incoming funds to the smesher account when it's offline, it needs to wait for the node to become synced?

That's almost right. So to show up incoming funds (and balance) we need to sync the node. But it should show up "latest known balance" and transactions, even if it is not fully synced. Aka there were incoming txs at layers 121, 122, 123, 124, and 125. If the node is synced only up to 123 — it will show all transactions (and calculated account balances) only up to this point.

So Smapp works only with one node (the local or remote) and just show the information that it got from GRPC responses.

**Comment by pigmej** [comment]
👍  from my side, it's sometimes frustrating when you need to hit the exact spot when you're fully in sync.

**Comment by countvonzero** [comment]
>> assuming the node is not synced, is it easier to have the node relay the tx to other peers?

> Sounds good to me. Do we already have it in the go-spacemesh?

no. but not too difficult to add. tho if we wants to add feature to relay tx, we most likely should relay other GRPCs as well. see my reasoning below.

> So Smapp works only with one node (the local or remote) and just show the information that it got from GRPC responses.

my amateur opinions: when a user uses smapp, it not only uses it for mining, but also for explorer-like functions for their accounts. i think there is an usability issue here. the fact that the node is mining/syncing, should not affect the functionality of viewing the account state.

let's say go-spacemesh adds the tx-relay functionality, without the ability to get state from elsewhere, smapp won't be able to show the state of the tx it just sent.

i think the simpliest design is to add middleware to go-spacemesh GRPC service that forwards all GRPC calls to a synced node when the node itself is not synced.

**Comment by brusherru** [comment]
It sounds perfect to me, as a Smapp developer, but I'm not sure that it will sound good to "privacy-nerds".

If you take a look at some clients, that may run their own node, like Monero / ZCash / smth else (bitcoin has the same option, but usually it is not so user-friendly) — they usually work only with the RPC / node that the User chose. So if you worry about privacy you run the node and have to wait, or you can switch to the remote API and trust it.
And usually running your own node in such clients is not only about mining and earning rewards for it, but mostly about privacy. In the same way, we can run the local node and sync in Smapp without turning smeshing on.

So I believe to make the right decision on it we need to listen to opinions of our "philosophy leaders".

cc: @lrettig @noamnelke @tomerafek

**Comment by countvonzero** [comment]
@brusherru 
i imagine this works effectively as a p2p blockchain browser. and tx itself is forwarded as a opaque blob. i am raking my brains to understand what can trigger privacy concerns here. can you provide some examples?

**Comment by brusherru** [comment]
@countvonzero for example, deanonymisation of account addresses. E.G. if you're requesting balances of some accounts (at least more often than others) from some public RPC — the owner of this RPC may store and associate your IPs with these accounts. That's the point why some privacy nerds running their own bitcoin nodes without mining.

Of course, you may say that they may use VPN / TOR / etc to hide their IPs and so on. I don't have any argument against it (I'm not a privacy nerd), but I know that for some reason they still prefer to run their own node :)

I do not insist on it, as I said, it will be much easier for me to use such middleware, instead of implementing a special mechanism. But I think that we must take into account such aspects.

**Comment by countvonzero** [comment]
thank you @brusherru 

we can always provide such relay option for the owner to turn on/off, and explicitly state the pros and cons of both options (state delay vs potential privacy concerns)

**Comment by lrettig** [comment]
I'm not a huge fan of the "RPC relay" proposal for two reasons: the privacy concerns @brusherru highlighted above, and also that it just seems nonstandard. I'm not aware of any other protocol or wallet that does something like this.

Let me propose a few ideas:

1. As an immediate stop-gap, allow smapp to send a tx even if the node is "just a little bit" out of sync (e.g., 1-3 layers). And/or add a "force send" option that allows the user to transmit the tx to the node even when it's not synced, with the understanding (and a warning) that they won't be able to see tx status unless/until the node is more synced.
2. Add links to the explorer as a fallback. If a tx is sent and its status cannot be viewed in smapp for any reason, the user should have the option to click a link to track the tx in the explorer. By the same token, if the node isn't synced and current account state isn't available, the user should be presented with a link to view the account state in the explorer.
3. Allow smapp to talk to multiple RPC providers. We should be running public endpoints, anyway. Ideally, smapp would talk to a (fully synced, reliable) public endpoint until the local node is synced, at which point it would switch to the local endpoint. (The user should be notified of this and have the option not to do it, to avoid any privacy concerns.)
4. Ultimately, we'll want some sort of "fast snapshot state sync" option (which geth has) where the node _first_ downloads a snapshot of the current state, and only then proceeds to download all previous blocks and verify everything historically. This would allow the node to at least provide up-to-date information on account state pretty quickly.

**Comment by countvonzero** [comment]
> I'm not a huge fan of the "RPC relay" proposal for two reasons: the privacy concerns @brusherru highlighted above, 

ok

> and also that it just seems nonstandard. I'm not aware of any other protocol or wallet that does something like this.

rpc relay is not novel. it's often used for bridging services that have different APIs, especially during service updates/upgrades.
in the blockchain world, i know hedera has something similar to bridge calls from ethereum tools to hedera nodes

> 1. As an immediate stop-gap, allow smapp to send a tx even if the node is "just a little bit" out of sync (e.g., 1-3 layers).

node already tolerate out-of-sync'ness for 3 layers.

> 3. Allow smapp to talk to multiple RPC providers.
> (The user should be notified of this and have the option not to do it, to avoid any privacy concerns.)

this move the burden from node to smapp. i have no objections. but the privacy issue remains.

> 4. Ultimately, we'll want some sort of "fast snapshot state sync" option

that sounds like a long way away...

**Comment by brusherru** [comment]
To sum it up:
1. We have everything to end up with the simplest (and pretty effective) solution:
    - > node already tolerate out-of-sync'ness for 3 layers
       
       need to loosen the condition in Smapp, to allow sending transactions within the same 3 out-of-sync laters
       `syncedLayer >= topLayer - 3`

    - > Add links to the explorer as a fallback
       
       We already have it. So no changes are needed anymore.

2. Two other @lrettig  ideas sound cool, but will require a lot of work and tests. So I'm not sure we can afford it for now and I'd propose to name them "features" and postpone for better times ;)

Any objections?

**Comment by brusherru** [comment]
Ok, seems actually we don't have this tolerance 3-out-of-sync.

I've tried to send TX, having 314 synced layers from 314 topmost layer, but not changed to `isSynced: true` yet (but then it switched to true within a minute). And got an error: "Cannot submit the transaction, node is not in sync yet, try again later"...

And then I discovered these things:
1. https://github.com/spacemeshos/go-spacemesh/blob/7080babb5c32c8b7e1f50a1a26d483aac0897a8a/api/grpcserver/transaction_service.go#L65-L68
2. https://github.com/spacemeshos/go-spacemesh/blob/5170566958147cc880936042df332d6d25ca4afa/syncer/syncer.go#L211-L219

So. Am I right, we don't have it yet on go-spacemesh side?
@countvonzero

**Comment by countvonzero** [comment]
the tolerance is the other direction. when a node is already synced, if syncedLayer starts to lag topLayer, it will stay synced until topLayer - syncedLayer > 3. the idea is to avoid entering notSyned state because it needs to go thru gossipSyned state to get to syned state again.

**Comment by countvonzero** [comment]
https://github.com/spacemeshos/go-spacemesh/blob/5170566958147cc880936042df332d6d25ca4afa/syncer/syncer.go#L434

**Comment by countvonzero** [comment]
i dont think smapp need to do anything additionally to what the node is already doing. the logic in smapp can be as simple as "only send tx when isSyned is true" because the lag tolerance is already built-in in the node's isSynced response.

**Comment by brusherru** [comment]
Ah, ok. Got it.
Thanks, @countvonzero!

Just checked, it works well:
1. Synced the Node
2. Turned internet off
3. Waited when Node become a bit unsynced (but it still returns `isSynced: true`)
4. Send transaction
5. Turn internet on

All works, funds was successfully sent to another account.
So I'm closing the issue for now.
